import { bi, item } from './helpContentUtils'

export const clinicalHelpSections=[

  item('start','Γρήγορη έναρξη','Quick start','Μια σύντομη διαδρομή για να καταλάβετε πώς είναι οργανωμένη η εφαρμογή και από πού ξεκινά κάθε εργασία.','A short orientation to understand how Healthcare Suite is organised and where each workflow starts.',{
    purpose:bi('Να βοηθήσει έναν νέο χρήστη να κινηθεί με ασφάλεια στην εφαρμογή χωρίς να χρειάζεται εξωτερικό εγχειρίδιο.','Help a new user navigate the application safely without needing an external manual.'),
    audience:bi('Όλοι οι χρήστες.','All users.'),
    steps:{el:['Συνδεθείτε με τον λογαριασμό σας ή χρησιμοποιήστε την επιλογή Demo για εκπαίδευση.','Χρησιμοποιήστε το αριστερό μενού για να επιλέξετε την ενότητα εργασίας.','Η «Νέα καταχώρηση» ξεκινά από το Dashboard και σας οδηγεί στη σωστή φόρμα.','Χρησιμοποιήστε αναζήτηση και φίλτρα πριν ανοίξετε μια υπάρχουσα εγγραφή.','Ανοίξτε την καρτέλα της εγγραφής για λεπτομέρειες, ιστορικό και αρχεία.','Χρησιμοποιήστε το ? οποιαδήποτε στιγμή για βοήθεια σχετική με την οθόνη που βλέπετε.'],en:['Sign in with your account or use Demo for training.','Use the left navigation to choose your working module.','New record starts from the Dashboard and routes you to the correct form.','Use search and filters before opening an existing record.','Open a record card for details, history and files.','Use ? at any time for help related to the screen you are viewing.']},
    important:{el:['Το Demo είναι ξεχωριστό από την παραγωγική λειτουργία.','Οι βιβλιοθήκες αποτελούν κοινά master data και δεν είναι λειτουργικές εγγραφές.','Μην χρησιμοποιείτε το κουμπί Back του browser ως υποκατάστατο της πλοήγησης της εφαρμογής όταν υπάρχει διαθέσιμο «Πίσω στο …».'],en:['Demo is isolated from production operation.','Libraries are shared master data and are not operational records.','Do not rely on the browser Back button when the application provides a “Back to …” action.']},
    related:bi('Dashboard · Προφίλ · Βοήθεια · Demo','Dashboard · Profile · Help · Demo')
  }),
  item('dashboard','Dashboard','Dashboard','Η κεντρική εικόνα της εφαρμογής: προτεραιότητες, δείκτες, πρόσφατη δραστηριότητα και συγκριτικά analytics.','The application overview: priorities, indicators, recent activity and comparative analytics.',{
    purpose:bi('Να δίνει γρήγορη επιχειρησιακή εικόνα και να οδηγεί στις ενότητες που χρειάζονται προσοχή.','Provide a fast operational overview and route users to areas requiring attention.'),
    audience:bi('Διοίκηση, Επιτροπή Λοιμώξεων, Προϊστάμενος Λοιμώξεων, εξουσιοδοτημένοι χρήστες.','Management, Infection Control Committee, Infection Control Lead and authorised users.'),
    steps:{el:['Ελέγξτε τις κάρτες προτεραιοτήτων και τα βασικά KPIs.','Πατήστε «Νέα καταχώρηση» για να ξεκινήσετε νέα εργασία.','Χρησιμοποιήστε «Ανάλυση δεδομένων» για 6μηνο ή 12μηνο.','Επιλέξτε δείκτη και συγκρίνετε με την αμέσως προηγούμενη αντίστοιχη περίοδο.','Πατήστε σε στοιχείο/γράφημα όταν υπάρχει drill-down για να μεταφερθείτε στη σχετική λίστα.'],en:['Review priority cards and main KPIs.','Select New record to start a new workflow.','Use Data analysis for 6- or 12-month periods.','Choose an indicator and compare it with the immediately preceding equivalent period.','Select a chart/data point when drill-down is available to open the relevant filtered list.']},
    important:{el:['Οι μεταβολές και τα ποσοστά έχουν νόημα μόνο όταν υπάρχουν επαρκή δεδομένα και στις δύο περιόδους.','Το Dashboard δεν αντικαθιστά την αναλυτική καρτέλα της εγγραφής.'],en:['Changes and percentages are meaningful only when both comparison periods contain adequate data.','The Dashboard does not replace the detailed record workspace.']},
    related:bi('Δείκτες · Εργαστήριο · Ασθενείς · Ποιότητα','Indicators · Laboratory · Patients · Quality')
  }),
  item('patients','Ασθενείς & κλινική επιτήρηση','Patients & clinical surveillance','Πλήρης καρτέλα ασθενούς με μητρώο, ενεργές/παλαιές επιτηρήσεις, δείγματα, αγωγή, μέτρα απομόνωσης, ΕΟΔΥ και ιστορικό.','Complete patient workspace with registry data, active/previous surveillance, samples, therapy, isolation precautions, statutory notifications and history.',{
    purpose:bi('Να κρατά σε μία ιχνηλάσιμη ροή την κλινική επιτήρηση και τις συνδεδεμένες εργαστηριακές/θεραπευτικές ενέργειες.','Keep clinical surveillance and linked laboratory/therapeutic actions in one traceable workflow.'),
    audience:bi('Ομάδα λοιμώξεων, ιατροί ελεγκτές και εξουσιοδοτημένο κλινικό προσωπικό.','Infection control, reviewing physicians and authorised clinical staff.'),
    steps:{el:['Αναζητήστε ασθενή ή πατήστε «Νέος ασθενής». Η νέα καρτέλα ανοίγει στην ίδια πλήρη μορφή και διαθέτει Αποθήκευση/Ακύρωση.','Οι Ημέρες νοσηλείας υπολογίζονται αυτόματα από την ημερομηνία εισαγωγής έως την έξοδο ή έως σήμερα.','Στη Σύνοψη ελέγξτε μητρώο και γρήγορες ενέργειες. Η περιοχή περιεχομένου σκρολάρει χωρίς να μετακινούνται τα κύρια tabs.','Στην Επιτήρηση ανοίξτε ενεργό περιστατικό ή δημιουργήστε νέο. Μέσα στο περιστατικό τα tabs Κλινική αξιολόγηση, Δείγματα και Αντιμετώπιση έχουν δικό τους περιεχόμενο/scroll.','Στα Δείγματα ανοίξτε την εργαστηριακή εγγραφή για λεπτομέρειες ή επανέλεγχο.','Στην Αγωγή & Μέτρα η αντιμικροβιακή αγωγή και τα μέτρα απομόνωσης εμφανίζονται σε ξεχωριστές περιοχές.','Στο ΕΟΔΥ ανοίξτε τις δηλώσεις και επιστρέψτε στην ίδια θέση της λίστας.','Στο Ιστορικό χρησιμοποιήστε το χρονολόγιο και τα αρχεία για πλήρη ιχνηλασιμότητα.'],en:['Search for a patient or select New patient. The new record opens in the same full workspace with Save/Cancel.','Hospital days are calculated automatically from admission to discharge or today.','In Summary review registry data and quick actions. Content scrolls while the main tabs remain stable.','In Surveillance open an active case or create a new one. Inside the case, Clinical assessment, Samples and Management have their own content/scroll areas.','In Samples open the laboratory record for details or follow-up.','In Therapy & Precautions antimicrobial therapy and isolation precautions are shown in separate areas.','In statutory notifications open each record and return to the same list position.','Use Timeline and Files for full traceability.']},
    important:{el:['Θετικό εργαστηριακό αποτέλεσμα μπορεί να συνδεθεί με ενεργή επιτήρηση· επανέλεγχος δεν πρέπει να δημιουργεί διπλό περιστατικό.','Αρνητικό follow-up δεν κλείνει σιωπηρά την επιτήρηση. Το κλείσιμο είναι ρητή ενέργεια.','Σε create/edit κάρτες χρησιμοποιείτε το κοινό ζεύγος Ακύρωση + Αποθήκευση.'],en:['A positive result may link to active surveillance; a follow-up must not create a duplicate case.','A negative follow-up does not silently close surveillance. Closure is an explicit action.','Create/edit cards use the common Cancel + Save action pair.']},
    related:bi('Εργαστήριο · Αντιμικροβιακή Επιτήρηση · Απομόνωση · ΕΟΔΥ','Laboratory · Antimicrobial Surveillance · Isolation · statutory notifications')
  }),
  item('employees','Εργαζόμενοι','Employees','Κεντρική καρτέλα εργαζομένου με στοιχεία προσωπικού, εμβολιασμούς, εκπαίδευση, Ιατρό Εργασίας, ιστορικό και προαιρετικό λογαριασμό πρόσβασης.','Central employee workspace with staff data, vaccinations, training, Occupational Health, history and an optional access account.',{
    purpose:bi('Να συνδέει πρόληψη, εκπαίδευση και επαγγελματική υγεία με μία μοναδική εγγραφή εργαζομένου.','Link prevention, training and occupational health to one unique employee record.'),
    audience:bi('Ομάδα λοιμώξεων, Ιατρός Εργασίας και εξουσιοδοτημένοι διαχειριστές.','Infection control, Occupational Health and authorised administrators.'),
    steps:{el:['Πατήστε «Νέος εργαζόμενος»: ανοίγει απευθείας η πλήρης καρτέλα, όχι διαφορετική μικρή φόρμα.','Συμπληρώστε στοιχεία και επιλέξτε Τμήμα/Ιδιότητα από τις κοινές βιβλιοθήκες. Χρησιμοποιήστε Αποθήκευση ή Ακύρωση.','Στην υπάρχουσα καρτέλα ελέγξτε Εμβολιασμούς, Εκπαίδευση, Ιατρό Εργασίας και Ιστορικό & Αρχεία.','Η «Δημιουργία/Διαχείριση λογαριασμού» ανοίγει τη διαχείριση πρόσβασης. Με επιτυχημένη αποθήκευση επιστρέφετε στην καρτέλα εργαζομένου.','Για μαζικές ενέργειες χρησιμοποιήστε τις ειδικές λειτουργίες Εκπαίδευσης ή Εμβολιασμών.'],en:['Select New employee to open the full employee workspace directly, not a separate small form.','Enter details and select Department/Professional category from shared libraries. Use Save or Cancel.','For an existing employee review Vaccinations, Training, Occupational Health and History & Files.','Create/Manage account opens access management. After successful save you return to the employee workspace.','Use dedicated Training or Vaccination workflows for bulk actions.']},
    important:{el:['Καρτέλα εργαζομένου και λογαριασμός σύνδεσης είναι διαφορετικές οντότητες.','Τμήμα και Ιδιότητα πρέπει να χρησιμοποιούν την κοινή ονοματολογία των βιβλιοθηκών.'],en:['An employee record and a sign-in account are different entities.','Department and Professional category must use shared library terminology.']},
    related:bi('Εμβολιασμοί · Εκπαίδευση · Ρόλοι & Δικαιώματα','Vaccinations · Training · Roles & Permissions')
  }),
  item('environment','Επιφάνειες & Νερό','Surfaces & Water','Περιβαλλοντική δειγματοληψία με σαφή διαχωρισμό ανάμεσα στη λήψη δείγματος και στο εργαστηριακό αποτέλεσμα.','Environmental sampling with a clear separation between specimen collection and laboratory result entry.',{
    purpose:bi('Να επιτρέπει ασφαλή καταχώρηση λήψης δείγματος χωρίς ο χρήστης της δειγματοληψίας να μεταβάλλει εργαστηριακό αποτέλεσμα.','Allow safe specimen collection without letting the collection user alter laboratory results.'),
    audience:bi('Ομάδα λοιμώξεων/επιτήρησης για τη λήψη και Εργαστήριο για το αποτέλεσμα.','Infection control/surveillance for collection and Laboratory for results.'),
    steps:{el:['Ανοίξτε Επιφάνειες ή Νερό από την Επιτήρηση. Το αριστερό μενού παραμένει μαρκαρισμένο στην υποκατηγορία που χρησιμοποιείτε.','Καταχωρήστε ημερομηνία, σημείο/τμήμα και στοιχεία λήψης.','Κατά τη λήψη το αποτέλεσμα παραμένει «Εκκρεμεί». Δεν συμπληρώνετε μικροοργανισμό, CFU/ATP ή αποδοχή.','Ανοίξτε τη σχετική εγγραφή από το Εργαστήριο για αποτέλεσμα, μικροοργανισμό, CFU/ATP και αποδοχή/απόρριψη.','Χρησιμοποιήστε φίλτρα για επαναλαμβανόμενα ευρήματα ανά σημείο και περίοδο.'],en:['Open Surfaces or Water from Surveillance. The left navigation keeps the active subcategory highlighted.','Record date, point/department and collection details.','At collection time the result remains Pending. Do not enter microorganism, CFU/ATP or acceptance.','Open the linked Laboratory record for result, microorganism, CFU/ATP and acceptance/rejection.','Use filters to review recurring findings by point and period.']},
    important:{el:['Αποτέλεσμα, μικροοργανισμός και αποδοχή είναι ιδιοκτησία της εργαστηριακής ροής.','Μην δημιουργείτε δεύτερη παράλληλη καταχώρηση για το ίδιο δείγμα.'],en:['Result, microorganism and acceptance belong to the Laboratory workflow.','Do not create a second parallel record for the same sample.']},
    related:bi('Εργαστήριο · Επιτήρηση · Βιβλιοθήκες σημείων/τμημάτων','Laboratory · Surveillance · point/department libraries')
  }),
  item('laboratory','Εργαστήριο','Laboratory','Ενιαίο workspace για στοιχεία δείγματος, αποτέλεσμα, μικροοργανισμούς, κρίσιμη γνωστοποίηση και αντιβιόγραμμα.','Unified workspace for specimen details, result, microorganisms, critical-result communication and antibiogram.',{
    purpose:bi('Να αποτελεί την πηγή αλήθειας για το εργαστηριακό αποτέλεσμα και να διατηρεί ασφαλή σύνδεση με ασθενή/εργαζόμενο/περιβάλλον.','Act as the system of record for laboratory results with safe linkage to patient/staff/environment sources.'),
    audience:bi('Εργαστήριο και εξουσιοδοτημένη ομάδα λοιμώξεων.','Laboratory and authorised infection-control staff.'),
    steps:{el:['Δημιουργήστε δείγμα και επιλέξτε πηγή: ασθενής, εργαζόμενος, επιφάνεια ή νερό.','Για ασθενή μπορείτε να επιλέξετε υπάρχοντα ή να δημιουργήσετε νέο μέσα στην ίδια ροή· η διαδικασία δείγματος συνεχίζεται.','Στα Στοιχεία δείγματος καταγράψτε τύπο, λήψη, παραλαβή και αποδοχή/λόγο απόρριψης.','Στο Αποτέλεσμα καταχωρήστε κατάσταση, ημερομηνία και απομονωθέντες μικροοργανισμούς.','Αν σημειωθεί «Κρίσιμο αποτέλεσμα», απαιτούνται ο αποδέκτης και η ημερομηνία/ώρα γνωστοποίησης πριν την αποθήκευση.','Σε θετικό αποτέλεσμα καταχωρήστε αντιβιόγραμμα όπου υπάρχει.','Για επανέλεγχο χρησιμοποιήστε τη σχετική λειτουργία ώστε να διατηρείται η lineage του αρχικού δείγματος.'],en:['Create a specimen and select the source: patient, employee, surface or water.','For a patient select an existing record or create one within the same workflow; specimen processing continues.','In Sample details record specimen type, collection, receipt and acceptance/rejection reason.','In Result record status, date and isolated microorganisms.','If Critical result is enabled, recipient and communication date/time are required before save.','For a positive result record an antibiogram when available.','Use the follow-up function to preserve lineage to the original sample.']},
    important:{el:['Το Εργαστήριο είναι το μόνο σημείο καταχώρησης τελικού αποτελέσματος για περιβαλλοντικά δείγματα.','Διόρθωση αποτελέσματος πρέπει να ενημερώνει με ιχνηλασιμότητα τη συνδεδεμένη κλινική ροή.','Κρίσιμο αποτέλεσμα δεν θεωρείται closed-loop μέχρι να τεκμηριωθεί η γνωστοποίηση.'],en:['Laboratory is the only final-result entry point for environmental samples.','Result correction must traceably update the linked clinical workflow.','A critical result is not closed-loop until communication is documented.']},
    related:bi('Ασθενείς · Επιφάνειες/Νερό · Ειδοποιήσεις · Audit Trail','Patients · Surfaces/Water · Notifications · Audit Trail')
  }),
  item('hand-hygiene','Υγιεινή Χεριών WHO','WHO Hand Hygiene','Συνεδρία άμεσης παρατήρησης WHO με αυτόματο υπολογισμό επαγγελματιών, ευκαιριών, ενεργειών και συμμόρφωσης.','WHO direct-observation session with automatic calculation of professionals, opportunities, actions and compliance.',{
    purpose:bi('Να καταγράφει με συνεπή τρόπο τις ευκαιρίες των WHO 5 Moments και να υπολογίζει συγκρίσιμη συμμόρφωση.','Record WHO 5 Moments opportunities consistently and calculate comparable compliance.'),
    audience:bi('Παρατηρητές υγιεινής χεριών και ομάδα λοιμώξεων.','Hand-hygiene observers and infection control.'),
    steps:{el:['Δημιουργήστε νέα συνεδρία και επιλέξτε Τμήμα από τη βιβλιοθήκη και Παρατηρητή από το ενεργό προσωπικό.','Η ημερομηνία χρησιμοποιεί ημερολόγιο και οι ώρες έναρξης/λήξης επιλογέα ώρας.','Στο πεδίο «Αριθμός επαγγελματιών» χρησιμοποιήστε διαδοχικό αριθμό για τον επαγγελματία που παρατηρείτε (π.χ. 1). Ο συνολικός αριθμός διαφορετικών επαγγελματιών υπολογίζεται αυτόματα από τις καταγεγραμμένες τιμές.','Επιλέξτε Επαγγελματική κατηγορία, WHO Moment, ενέργεια HR/HW/Παράλειψη και γάντια.','Πατήστε «Προσθήκη ευκαιρίας». Στην ίδια συνεδρία διατηρούνται ο αριθμός επαγγελματιών και η κατηγορία για την επόμενη ευκαιρία μέχρι να τα αλλάξετε.','Οι κάρτες Επαγγελματίες, Ευκαιρίες, HR, HW, Παραλείψεις και Συμμόρφωση WHO ενημερώνονται από την ίδια κοινή λογική υπολογισμού.','Πατήστε «Αποθήκευση συνεδρίας WHO». Με επιτυχημένη αποθήκευση η κάρτα κλείνει.'],en:['Create a new session and select Department from the library and Observer from active staff.','Date uses a calendar and start/end use time pickers.','In Professional number use a sequential number for the professional being observed (e.g. 1). The total number of distinct professionals is calculated automatically from recorded values.','Select Professional category, WHO Moment, HR/HW/Missed action and gloves.','Select Add opportunity. Within the same session the professional number and category remain for the next opportunity until you change them.','Professionals, Opportunities, HR, HW, Missed and WHO Compliance cards use the same shared calculation logic.','Select Save WHO session. After a successful save the card closes.']},
    important:{el:['Δεν υπάρχει ξεχωριστό χειροκίνητο πεδίο συνολικού αριθμού επαγγελματιών.','Ο ίδιος αριθμός σε πολλές ευκαιρίες σημαίνει τον ίδιο παρατηρούμενο επαγγελματία. Νέος αριθμός σημαίνει διαφορετικό επαγγελματία.','Η Αποθήκευση δεν πρέπει να κλείσει αν η backend αποθήκευση αποτύχει· εμφανίζεται μήνυμα σφάλματος.'],en:['There is no separate manually entered total-professionals field.','The same number across multiple opportunities represents the same observed professional; a new number represents a different professional.','Save does not close if backend persistence fails; an error is shown.']},
    related:bi('Δείκτης Υγιεινής Χεριών · Τμήματα · Εργαζόμενοι · LIRA','Hand Hygiene indicator · Departments · Employees · LIRA')
  }),
  item('prevention','Εμβολιασμοί, Αντιβιοτικά & Bundles','Vaccinations, Antibiotics & Bundles','Οι βασικές λειτουργίες πρόληψης για προσωπικό και ασθενείς.','Core prevention workflows for staff and patients.',{
    purpose:bi('Να συγκεντρώνει παρεμβάσεις πρόληψης που απαιτούν παρακολούθηση, συμμόρφωση ή έγκριση.','Bring together prevention interventions that require follow-up, compliance or approval.'),
    audience:bi('Ομάδα λοιμώξεων, Ιατρός Εργασίας, ιατροί ελεγκτές και εξουσιοδοτημένοι χρήστες.','Infection control, Occupational Health, reviewing physicians and authorised users.'),
    steps:{el:['Στους Εμβολιασμούς επιλέξτε ενεργό εργαζόμενο και καταγράψτε το σχετικό εμβόλιο/δόση.','Στα Προωθημένα Αντιβιοτικά χρησιμοποιήστε τη λίστα εγκρίσεων και όχι ελεύθερη παράλληλη καταχώρηση.','Στα Bundles επιλέξτε το κατάλληλο bundle και καταγράψτε τα επιμέρους στοιχεία συμμόρφωσης.','Ελέγξτε πάντα ημερομηνία, τμήμα και υπεύθυνο πριν την αποθήκευση.'],en:['In Vaccinations select an active employee and record vaccine/dose details.','For Restricted Antibiotics use the approval list rather than a parallel free-text workflow.','For Bundles select the relevant bundle and record each compliance element.','Always verify date, department and responsible user before saving.']},
    important:{el:['Οι βιβλιοθήκες φαρμάκων, εμβολίων και bundles πρέπει να αποτελούν την κοινή πηγή επιλογών.','Η έγκριση προωθημένου αντιβιοτικού δεν πρέπει να συγχέεται με απλή καταχώρηση θεραπείας.'],en:['Drug, vaccine and bundle libraries must remain the shared source of selectable values.','Restricted antibiotic approval is not the same as simply recording therapy.']},
    related:bi('Εργαζόμενοι · Ασθενείς · Κέντρο Διαχείρισης','Employees · Patients · Management Center')
  })
]
