import { bi, item } from './helpContentUtils'

export const clinicalHelpSections=[

  item('start','Γρήγορη έναρξη','Quick start','Μια σύντομη διαδρομή για να καταλάβετε πώς είναι οργανωμένο την εφαρμογή και από πού ξεκινά κάθε εργασία.','A short orientation to understand how Healthcare Suite is organised and where each workflow starts.',{
    purpose:bi('Να βοηθήσει έναν νέο χρήστη να κινηθεί με ασφάλεια στην εφαρμογή χωρίς να χρειάζεται εξωτερικό εγχειρίδιο.','Help a new user navigate the application safely without needing an external manual.'),
    audience:bi('Όλοι οι χρήστες.','All users.'),
    steps:{el:['Συνδεθείτε με τον λογαριασμό σας ή χρησιμοποιήστε την επιλογή Demo για εκπαίδευση.','Χρησιμοποιήστε το αριστερό μενού για να επιλέξετε την ενότητα εργασίας.','Η «Νέα καταχώρηση» ξεκινά από το Dashboard και σας οδηγεί στη σωστή φόρμα.','Χρησιμοποιήστε αναζήτηση και φίλτρα πριν ανοίξετε μια υπάρχουσα εγγραφή.','Ανοίξτε την καρτέλα της εγγραφής για λεπτομέρειες, ιστορικό και αρχεία.','Χρησιμοποιήστε το ? οποιαδήποτε στιγμή για βοήθεια σχετική με την οθόνη που βλέπετε.'],en:['Sign in with your account or use Demo for training.','Use the left navigation to choose your working module.','New record starts from the Dashboard and routes you to the correct form.','Use search and filters before opening an existing record.','Open a record card for details, history and files.','Use ? at any time for help related to the screen you are viewing.']},
    important:{el:['Το Demo είναι ξεχωριστό από την παραγωγική λειτουργία.','Οι βιβλιοθήκες αποτελούν κοινά master data και δεν είναι λειτουργικές εγγραφές.','Μην χρησιμοποιείτε το κουμπί Back του browser ως υποκατάστατο της πλοήγησης της εφαρμογής όταν υπάρχει διαθέσιμο «Πίσω στο …».'],en:['Demo is isolated from production operation.','Libraries are shared master data and are not operational records.','Do not rely on the browser Back button when the application provides a “Back to …” action.']},
    related:bi('Dashboard · Προφίλ · Βοήθεια · Demo','Dashboard · Profile · Help · Demo')
  }),
  item('dashboard','Dashboard','Dashboard','Η κεντρική εικόνα της εφαρμογής: προτεραιότητες, δείκτες, πρόσφατη δραστηριότητα και συγκριτικά analytics.','The application overview: priorities, indicators, recent activity and comparative analytics.',{
    purpose:bi('Να δίνει γρήγορη επιχειρησιακή εικόνα και να οδηγεί στις ενότητες που χρειάζονται προσοχή.','Provide a fast operational overview and route users to areas requiring attention.'),
    audience:bi('Διοίκηση, Επιτροπή Λοιμώξεων, Προϊστάμενος Λοιμώξεων, εξουσιοδοτημένοι χρήστες.','Management, Infection Control Committee, Infection Control Lead and authorised users.'),
    steps:{el:['Ελέγξτε τις κάρτες προτεραιοτήτων και τα βασικά KPIs.','Πατήστε «Νέα καταχώρηση» για να ξεκινήσετε νέα εργασία.','Χρησιμοποιήστε «Ανάλυση δεδομένων» για 6μηνο ή 12μηνο.','Επιλέξτε δείκτη και συγκρίνετε με την αμέσως προηγούμενη αντίστοιχη περίοδο.','Πατήστε σε στοιχείο/γράφημα όταν υπάρχει drill-down για να μεταφερθείτε στη σχετική λίστα.'],en:['Review priority cards and main KPIs.','Select New record to start a new workflow.','Use Data analysis for 6- or 12-month periods.','Choose an indicator and compare it with the immediately preceding equivalent period.','Select a chart/data point when drill-down is available to open the relevant filtered list.']},
    important:{el:['Οι μεταβολές και τα ποσοστά έχουν νόημα μόνο όταν υπάρχουν επαρκή δεδομένα και στις δύο περιόδους.','Το Dashboard δεν αντικαθιστά την αναλυτική καρτέλα της εγγραφής.'],en:['Changes and percentages are meaningful only when both comparison periods contain adequate data.','The Dashboard does not replace the detailed record workspace.']},
    related:bi('Δείκτες · Εργαστήριο · Ασθενείς · Ποιότητα','Indicators · Laboratory · Patients · Quality')
  }),
  item('patients','Ασθενείς & κλινική επιτήρηση','Patients & clinical surveillance','Αναζήτηση ασθενών και πλήρης ροή επιτήρησης: κλινική αξιολόγηση, δείγματα, αντιμικροβιακή αγωγή, απομόνωση, επανεκτίμηση και έκβαση.','Patient search and the complete surveillance workflow: clinical assessment, samples, antimicrobial therapy, isolation, reassessment and outcome.',{
    purpose:bi('Να συγκεντρώνει όλη την πληροφορία που σχετίζεται με ενεργή ή προηγούμενη επιτήρηση ενός ασθενή.','Keep all information related to active or previous patient surveillance in one place.'),
    audience:bi('Ομάδα λοιμώξεων, ιατροί ελεγκτές και εξουσιοδοτημένο κλινικό προσωπικό.','Infection control team, reviewing physicians and authorised clinical staff.'),
    steps:{el:['Βρείτε τον ασθενή με όνομα, κωδικό, ΑΜΚΑ, τμήμα, δωμάτιο ή διάγνωση.','Ανοίξτε την καρτέλα του ασθενή και ελέγξτε αν υπάρχει ενεργή επιτήρηση.','Στην Κλινική αξιολόγηση καταχωρήστε συμπτώματα, συσκευές και παράγοντες κινδύνου.','Στα Δείγματα & Αποτελέσματα παρακολουθήστε τις καλλιέργειες και τη σύνδεσή τους με το Εργαστήριο.','Στην Αντιμικροβιακή αγωγή καταχωρήστε φάρμακο, έναρξη/λήξη και σχετική έγκριση όπου απαιτείται.','Στην Απομόνωση καταγράψτε έναρξη, λήξη ή ακύρωση.','Χρησιμοποιήστε Επανεκτίμηση & Έκβαση για την πορεία του περιστατικού.','Το Ιστορικό & Αρχεία διατηρεί την ιχνηλασιμότητα της καρτέλας.'],en:['Find the patient by name, identifier, national ID, department, room or diagnosis.','Open the patient workspace and check for active surveillance.','In Clinical assessment record symptoms, devices and risk factors.','In Samples & Results follow cultures and their Laboratory links.','In Antimicrobial therapy record medication, start/end dates and approval where required.','In Isolation record start, end or cancellation.','Use Reassessment & Outcome to document the course of the case.','History & Files preserves traceability.']},
    important:{el:['Θετικό εργαστηριακό αποτέλεσμα μπορεί να ανοίξει ή να ενημερώσει ενεργή επιτήρηση.','Αρνητικό αποτέλεσμα δεν πρέπει από μόνο του να δημιουργεί ενεργή επιτήρηση.','Το κλείσιμο επιτήρησης κλειδώνει την ολοκληρωμένη κλινική ροή σύμφωνα με τα δικαιώματα.'],en:['A positive laboratory result can open or update active surveillance.','A negative result should not by itself create active surveillance.','Closing surveillance locks the completed clinical workflow according to permissions.']},
    related:bi('Εργαστήριο · Απομόνωση · Αντιβιοτικά · Bundles','Laboratory · Isolation · Antibiotics · Bundles')
  }),
  item('employees','Εργαζόμενοι','Employees','Κεντρική καρτέλα εργαζομένου με εμβολιασμούς, εκπαίδευση, Ιατρό Εργασίας και ιστορικό.','Central employee workspace with vaccinations, training, occupational health and history.',{
    purpose:bi('Να διατηρεί ενιαία εικόνα των στοιχείων εργαζομένου που σχετίζονται με πρόληψη και επιτήρηση.','Maintain a unified view of employee information related to prevention and surveillance.'),
    audience:bi('Ομάδα λοιμώξεων, Ιατρός Εργασίας, εξουσιοδοτημένοι διαχειριστές.','Infection control, Occupational Health and authorised administrators.'),
    steps:{el:['Αναζητήστε με όνομα και χρησιμοποιήστε φίλτρα Τμήματος/Ιδιότητας.','Ανοίξτε την καρτέλα του εργαζομένου.','Ελέγξτε τις καρτέλες Εμβολιασμοί, Εκπαίδευση, Ιατρός Εργασίας και Ιστορικό & Αρχεία.','Για μαζικές ενέργειες χρησιμοποιήστε τις αντίστοιχες λειτουργίες της ενότητας Εκπαίδευση ή Εμβολιασμοί.'],en:['Search by name and use Department/Professional category filters.','Open the employee workspace.','Review Vaccinations, Training, Occupational Health and History & Files tabs.','For bulk actions use the dedicated Training or Vaccination workflows.']},
    important:{el:['Τμήμα και Ιδιότητα πρέπει να προέρχονται από τις κοινές βιβλιοθήκες.','Η δημιουργία λογαριασμού χρήστη είναι διαφορετική ενέργεια από τη δημιουργία καρτέλας εργαζομένου.'],en:['Department and Professional category must come from shared libraries.','Creating a user account is a separate action from creating an employee record.']},
    related:bi('Εμβολιασμοί · Εκπαίδευση · Κέντρο Διαχείρισης','Vaccinations · Training · Management Center')
  }),
  item('environment','Επιφάνειες, Νερό & λοιπή επιτήρηση','Surfaces, Water & other surveillance','Περιβαλλοντική επιτήρηση και καταγραφή δειγμάτων ή ελέγχων που δεν ανήκουν στην κλινική καρτέλα ασθενή.','Environmental surveillance and recording of samples or checks outside the patient clinical workspace.',{
    purpose:bi('Να καταγράφει με τυποποιημένο τρόπο περιβαλλοντικούς ελέγχους και αποτελέσματα.','Record environmental controls and results in a standardised way.'),
    audience:bi('Ομάδα λοιμώξεων, εργαστήριο και εξουσιοδοτημένο προσωπικό.','Infection control, laboratory and authorised staff.'),
    steps:{el:['Επιλέξτε την κατάλληλη υποενότητα.','Καταχωρήστε ημερομηνία, σημείο/τμήμα, είδος δείγματος και αποτέλεσμα.','Ελέγξτε την ορθότητα πριν την αποθήκευση.','Χρησιμοποιήστε φίλτρα για έλεγχο τάσεων και επαναλαμβανόμενων ευρημάτων.'],en:['Choose the appropriate submodule.','Record date, location/department, sample type and result.','Verify correctness before saving.','Use filters to review trends and recurring findings.']},
    important:{el:['Μην χρησιμοποιείτε ελεύθερο κείμενο για Τμήμα όταν υπάρχει βιβλιοθήκη.','Η ονοματολογία πρέπει να παραμένει κοινή σε όλο το σύστημα.'],en:['Do not use free text for Department when a library value exists.','Naming must remain consistent throughout the system.']},
    related:bi('Εργαστήριο · Βιβλιοθήκες · Dashboard','Laboratory · Libraries · Dashboard')
  }),
  item('laboratory','Εργαστήριο','Laboratory','Διαχείριση δειγμάτων και αποτελεσμάτων, είτε για υπάρχοντα ασθενή είτε με υβριδική δημιουργία νέου ασθενή.','Sample and result management for an existing patient or through hybrid creation of a new patient.',{
    purpose:bi('Να συνδέει σωστά το μικροβιολογικό αποτέλεσμα με την κλινική επιτήρηση και τον ασθενή.','Correctly connect microbiology results with patient surveillance.'),
    audience:bi('Εργαστήριο και ομάδα λοιμώξεων.','Laboratory and infection control team.'),
    steps:{el:['Ξεκινήστε νέα καταχώρηση δείγματος.','Επιλέξτε υπάρχοντα ασθενή ή δημιουργήστε νέο μέσα από την ίδια ροή όταν απαιτείται.','Συμπληρώστε τύπο δείγματος, ημερομηνίες και μικροβιολογικά στοιχεία.','Καταχωρήστε αποτέλεσμα ως θετικό ή αρνητικό.','Σε θετικό αποτέλεσμα ελέγξτε τη σύνδεση/ενημέρωση της ενεργής επιτήρησης.','Σε αρνητικό αποτέλεσμα επιβεβαιώστε ότι δεν δημιουργήθηκε αδικαιολόγητη ενεργή επιτήρηση.'],en:['Start a new sample record.','Select an existing patient or create a new one within the same workflow when required.','Complete sample type, dates and microbiology details.','Record the result as positive or negative.','For a positive result verify linkage/update of active surveillance.','For a negative result verify that no unjustified active surveillance was created.']},
    important:{el:['Το αποτέλεσμα του Εργαστηρίου είναι κλινικά κρίσιμο δεδομένο· ελέγξτε ασθενή, ημερομηνία και μικροοργανισμό πριν την αποθήκευση.','Οι ειδοποιήσεις πρέπει να αφορούν τις πραγματικές εκκρεμότητες και όχι δοκιμαστικά δεδομένα.'],en:['Laboratory results are clinically critical; verify patient, date and microorganism before saving.','Notifications must reflect real pending items, not test data.']},
    related:bi('Ασθενείς · Μικροοργανισμοί · Ειδοποιήσεις','Patients · Microorganisms · Notifications')
  }),
  item('hand-hygiene','Υγιεινή Χεριών WHO','WHO Hand Hygiene','Καταχώρηση και αξιολόγηση παρατηρήσεων σύμφωνα με τη φόρμα WHO.','Recording and evaluation of observations using the WHO form.',{
    purpose:bi('Να υποστηρίζει τυποποιημένη παρατήρηση συμμόρφωσης και συγκρίσιμα αποτελέσματα.','Support standardised compliance observation and comparable results.'),
    audience:bi('Παρατηρητές υγιεινής χεριών και ομάδα λοιμώξεων.','Hand hygiene observers and infection control team.'),
    steps:{el:['Ανοίξτε την Υγιεινή Χεριών από την Πρόληψη.','Επιλέξτε τμήμα και στοιχεία παρατήρησης από τις διαθέσιμες βιβλιοθήκες.','Συμπληρώστε τις ευκαιρίες/ενδείξεις της φόρμας WHO.','Ελέγξτε τη συνολική καταχώρηση πριν την αποθήκευση.','Χρησιμοποιήστε τα φίλτρα και τους δείκτες για σύγκριση περιόδων ή τμημάτων.'],en:['Open Hand Hygiene from Prevention.','Select department and observation data from available libraries.','Complete WHO opportunities/indications.','Review the complete observation before saving.','Use filters and indicators to compare periods or departments.']},
    important:{el:['Η φόρμα πρέπει να εμφανίζεται πλήρως μεταφρασμένη στην επιλεγμένη γλώσσα.','Μαζική καταχώρηση χρησιμοποιείται μόνο όταν η διαδικασία το επιτρέπει.'],en:['The form must be fully translated in the selected language.','Bulk entry is used only when the workflow allows it.']},
    related:bi('Πρόληψη · Δείκτες · Τμήματα','Prevention · Indicators · Departments')
  }),
  item('prevention','Εμβολιασμοί, Αντιβιοτικά & Bundles','Vaccinations, Antibiotics & Bundles','Οι βασικές λειτουργίες πρόληψης για προσωπικό και ασθενείς.','Core prevention workflows for staff and patients.',{
    purpose:bi('Να συγκεντρώνει παρεμβάσεις πρόληψης που απαιτούν παρακολούθηση, συμμόρφωση ή έγκριση.','Bring together prevention interventions that require follow-up, compliance or approval.'),
    audience:bi('Ομάδα λοιμώξεων, Ιατρός Εργασίας, ιατροί ελεγκτές και εξουσιοδοτημένοι χρήστες.','Infection control, Occupational Health, reviewing physicians and authorised users.'),
    steps:{el:['Στους Εμβολιασμούς επιλέξτε ενεργό εργαζόμενο και καταγράψτε το σχετικό εμβόλιο/δόση.','Στα Προωθημένα Αντιβιοτικά χρησιμοποιήστε τη λίστα εγκρίσεων και όχι ελεύθερη παράλληλη καταχώρηση.','Στα Bundles επιλέξτε το κατάλληλο bundle και καταγράψτε τα επιμέρους στοιχεία συμμόρφωσης.','Ελέγξτε πάντα ημερομηνία, τμήμα και υπεύθυνο πριν την αποθήκευση.'],en:['In Vaccinations select an active employee and record vaccine/dose details.','For Restricted Antibiotics use the approval list rather than a parallel free-text workflow.','For Bundles select the relevant bundle and record each compliance element.','Always verify date, department and responsible user before saving.']},
    important:{el:['Οι βιβλιοθήκες φαρμάκων, εμβολίων και bundles πρέπει να αποτελούν την κοινή πηγή επιλογών.','Η έγκριση προωθημένου αντιβιοτικού δεν πρέπει να συγχέεται με απλή καταχώρηση θεραπείας.'],en:['Drug, vaccine and bundle libraries must remain the shared source of selectable values.','Restricted antibiotic approval is not the same as simply recording therapy.']},
    related:bi('Εργαζόμενοι · Ασθενείς · Κέντρο Διαχείρισης','Employees · Patients · Management Center')
  })
]
