import { bi, item } from './helpContentUtils'

export const adminHelpSections=[
  item('quality','Ποιότητα','Quality','Συμβάντα, audits, δείκτες και βελτιωτικές ενέργειες σε ενιαία ροή.','Incidents, audits, indicators and improvement actions in a unified workflow.',{
    purpose:bi('Να μετατρέπει ένα εύρημα ή συμβάν σε τεκμηριωμένη παρακολούθηση και, όπου χρειάζεται, σε βελτιωτική ενέργεια.','Turn a finding or incident into documented follow-up and, where needed, an improvement action.'),
    audience:bi('Ποιότητα, διοίκηση, επιτροπές και εξουσιοδοτημένοι υπεύθυνοι.','Quality, management, committees and authorised owners.'),
    steps:{el:['Καταχωρήστε συμβάν ή audit με τα απαιτούμενα στοιχεία.','Αξιολογήστε σοβαρότητα, κατηγορία και υπεύθυνο.','Όπου απαιτείται δημιουργήστε βελτιωτική ενέργεια από την ίδια ροή.','Συνδέστε με δείκτη όταν το εύρημα πρέπει να παρακολουθείται μετρήσιμα.','Χρησιμοποιήστε το ιστορικό για να ελέγχετε αλλαγές και ολοκλήρωση.'],en:['Record the incident or audit with required fields.','Assess severity, category and owner.','Create an improvement action from the same workflow where required.','Link an indicator when the finding should be measured over time.','Use history to review changes and completion.']},
    important:{el:['Μην δημιουργείτε διπλές διορθωτικές ενέργειες για το ίδιο εύρημα.','Η κατάσταση της ενέργειας πρέπει να ενημερώνεται μέχρι το πραγματικό κλείσιμο.'],en:['Avoid duplicate corrective actions for the same finding.','Action status should be updated until actual closure.']},
    related:bi('Δείκτες · Dashboard · Επιτροπές','Indicators · Dashboard · Committees')
  }),
  item('organization','Επιτροπές, Εκπαίδευση & Έγγραφα','Committees, Training & Documents','Οργανωτική τεκμηρίωση, συνεδριάσεις, παρουσιολόγια, εκπαιδευτικές δράσεις και αρχεία.','Organisational documentation, meetings, attendance, training activities and files.',{
    purpose:bi('Να διατηρεί την οργανωτική και εκπαιδευτική τεκμηρίωση συνδεδεμένη με τους πραγματικούς χρήστες/εργαζομένους.','Keep organisational and training documentation connected with real users/employees.'),
    audience:bi('Επιτροπές, εκπαιδευτές, ομάδα λοιμώξεων και διοίκηση.','Committees, trainers, infection control and management.'),
    steps:{el:['Στις Επιτροπές καταχωρήστε μέλη, ρόλους/καθήκοντα και συνεδρίες.','Στις συνεδρίες καταγράψτε παρόντες/απόντες, πρακτικά και επόμενη συνάντηση.','Στην Εκπαίδευση δημιουργήστε δράση και επιλέξτε μαζικά τους συμμετέχοντες όπου χρειάζεται.','Χρησιμοποιήστε παρουσιολόγιο και σχετικά αρχεία για πλήρη τεκμηρίωση.','Στα Έγγραφα χρησιμοποιήστε προβολή μέσα από την εφαρμογή όπου υποστηρίζεται.'],en:['In Committees record members, roles/duties and meetings.','For meetings record attendees/absentees, minutes and next meeting.','In Training create an activity and bulk-select participants when appropriate.','Use attendance and related files for complete documentation.','In Documents use in-app viewing where supported.']},
    important:{el:['Η ιδιότητα και το τμήμα εργαζομένου πρέπει να προέρχονται από τις κοινές βιβλιοθήκες.','Τα αρχεία τεκμηρίωσης πρέπει να συνδέονται με τη σωστή εγγραφή και όχι να παραμένουν ασύνδετα.'],en:['Employee professional category and department must come from shared libraries.','Documentation files should be linked to the correct record rather than left orphaned.']},
    related:bi('Εργαζόμενοι · Ποιότητα · Κέντρο Διαχείρισης','Employees · Quality · Management Center')
  }),
  item('management','Κέντρο Διαχείρισης','Management Center','Βιβλιοθήκες, δείκτες, ρόλοι, δικαιώματα, ερωτηματολόγια, bundles και παραμετροποίηση της εγκατάστασης.','Libraries, indicators, roles, permissions, questionnaires, bundles and installation configuration.',{
    purpose:bi('Να αποτελεί το μοναδικό σημείο διοικητικής παραμετροποίησης ώστε οι ίδιες επιλογές να χρησιμοποιούνται σε όλο το Healthcare Suite.','Act as the single configuration point so the same selectable values are used throughout Healthcare Suite.'),
    audience:bi('Διαχειριστές και ειδικά εξουσιοδοτημένοι χρήστες.','Administrators and specifically authorised users.'),
    steps:{el:['Διαχειριστείτε πρώτα τις Βιβλιοθήκες: Τμήματα, Ιδιότητες, Μικροοργανισμούς, Φάρμακα και λοιπά master data.','Ρυθμίστε Δείκτες, Ερωτηματολόγια και Bundles που χρησιμοποιούνται στις λειτουργικές ενότητες.','Στους Ρόλους & Δικαιώματα ορίστε ποιος βλέπει και ποιος μεταβάλλει κάθε περιοχή.','Δημιουργήστε λογαριασμό χρήστη μόνο όταν υπάρχει πραγματική ανάγκη πρόσβασης.','Μετά από αλλαγή σε master data ελέγξτε ότι η νέα επιλογή εμφανίζεται στις σχετικές φόρμες.'],en:['Manage Libraries first: Departments, Professional categories, Microorganisms, Drugs and other master data.','Configure Indicators, Questionnaires and Bundles used by operational modules.','In Roles & Permissions define who can view or modify each area.','Create a user account only when access is genuinely required.','After changing master data verify that the new option appears in related forms.']},
    important:{el:['Οι βιβλιοθήκες παραμένουν και στην καθαρή production εγκατάσταση. Οι λειτουργικές εγγραφές όχι.','Αποφύγετε διπλές τιμές όπως διαφορετικές ονομασίες για το ίδιο Τμήμα ή Ιδιότητα.','Οι αλλαγές δικαιωμάτων πρέπει να ελέγχονται με πραγματικό role test.'],en:['Libraries remain in a clean production installation; operational records do not.','Avoid duplicate values such as multiple names for the same Department or Professional category.','Permission changes should be verified with an actual role test.']},
    related:bi('Όλες οι ενότητες · Ρόλοι & Δικαιώματα · Demo','All modules · Roles & Permissions · Demo')
  }),
  item('roles','Ρόλοι, δικαιώματα & λογαριασμοί','Roles, permissions & accounts','Διαχείριση πρόσβασης με βάση ρόλο, τμήμα και πρόσθετες αρμοδιότητες.','Access management based on role, department and additional capabilities.',{
    purpose:bi('Να εξασφαλίζει ότι κάθε χρήστης βλέπει μόνο όσα απαιτεί ο ρόλος του.','Ensure each user sees only what their role requires.'),
    audience:bi('Διαχειριστές.','Administrators.'),
    steps:{el:['Επιλέξτε ή δημιουργήστε τον κατάλληλο ρόλο.','Ορίστε βασικό τμήμα και scope πρόσβασης.','Προσθέστε μόνο τις πρόσθετες αρμοδιότητες που χρειάζονται.','Δημιουργήστε/συνδέστε τον λογαριασμό χρήστη.','Κάντε δοκιμαστική είσοδο με τον συγκεκριμένο ρόλο και ελέγξτε sidebar, λίστες, προβολή και επεξεργασία.'],en:['Choose or create the appropriate role.','Set primary department and access scope.','Add only the additional capabilities required.','Create/link the user account.','Test-sign in with that role and verify sidebar, lists, viewing and editing.']},
    important:{el:['Η καρτέλα εργαζομένου δεν αποτελεί από μόνη της λογαριασμό σύνδεσης.','Μην αποθηκεύετε πραγματικούς κωδικούς πρόσβασης σε απλό κείμενο.','Η επαναφορά κωδικού πρέπει να γίνεται μέσω της υπηρεσίας ταυτοποίησης.'],en:['An employee record is not by itself a sign-in account.','Never store real passwords in plain text.','Password reset should be handled through the authentication service.']},
    related:bi('Προφίλ · Κέντρο Διαχείρισης · Ασφάλεια','Profile · Management Center · Security')
  }),
  item('lira','LIRA','LIRA','Βοηθητική περιοχή για ανάλυση, πλοήγηση και υποστήριξη του χρήστη χωρίς να αντικαθιστά κλινική κρίση.','Assisted analysis, navigation and user support without replacing clinical judgement.',{
    purpose:bi('Να βοηθά στην κατανόηση δεδομένων και στην πλοήγηση σε σύνθετες πληροφορίες.','Assist with understanding data and navigating complex information.'),
    audience:bi('Εξουσιοδοτημένοι χρήστες.','Authorised users.'),
    steps:{el:['Ανοίξτε τη LIRA από το βασικό μενού.','Δώστε σαφές ερώτημα σχετικό με τα διαθέσιμα δεδομένα ή τη χρήση της εφαρμογής.','Ελέγξτε την απάντηση πριν τη χρησιμοποιήσετε για επιχειρησιακή ή κλινική ενέργεια.','Μεταβείτε στην πρωτογενή εγγραφή όταν χρειάζεται επιβεβαίωση.'],en:['Open LIRA from the main navigation.','Provide a clear question related to available data or application use.','Review the response before using it for operational or clinical action.','Go to the source record whenever confirmation is needed.']},
    important:{el:['Η LIRA δεν αντικαθιστά τον υπεύθυνο επαγγελματία υγείας ούτε αποτελεί αυτόνομη κλινική απόφαση.','Οι πρωτογενείς εγγραφές παραμένουν η πηγή αλήθειας.'],en:['LIRA does not replace the responsible healthcare professional and is not an autonomous clinical decision-maker.','Source records remain the system of record.']},
    related:bi('Dashboard · Ασθενείς · Εργαστήριο · Βοήθεια','Dashboard · Patients · Laboratory · Help')
  }),
  item('profile','Προφίλ, γλώσσα & προσβασιμότητα','Profile, language & accessibility','Προσωπικές πληροφορίες πρόσβασης, επιλογή γλώσσας και ρυθμίσεις προσβασιμότητας.','Personal access information, language selection and accessibility settings.',{
    purpose:bi('Να δείχνει στον χρήστη με ποιον ρόλο και scope εργάζεται και να προσαρμόζει την παρουσίαση στις ανάγκες του.','Show the user which role and scope are active and adapt presentation to their needs.'),
    audience:bi('Όλοι οι χρήστες.','All users.'),
    steps:{el:['Ανοίξτε το Προφίλ από το όνομα χρήστη επάνω δεξιά.','Ελέγξτε ρόλο, βασικό τμήμα και πρόσθετες αρμοδιότητες.','Αλλάξτε γλώσσα από το EL/EN χωρίς να αλλάζει η λειτουργική κατάσταση της εφαρμογής.','Χρησιμοποιήστε το μενού Προσβασιμότητας για μέγεθος κειμένου, υψηλή αντίθεση ή reduced motion.'],en:['Open Profile from the user menu in the upper right.','Review role, primary department and additional capabilities.','Change language using EL/EN without changing application state.','Use Accessibility for text size, high contrast or reduced motion.']},
    important:{el:['Ρόλος, τμήμα και δικαιώματα δεν αλλάζουν από το Προφίλ· διαχειρίζονται από το Κέντρο Διαχείρισης.'],en:['Role, department and permissions are not changed from Profile; they are managed in the Management Center.']},
    related:bi('Ρόλοι & Δικαιώματα · Κέντρο Διαχείρισης','Roles & Permissions · Management Center')
  }),
  item('demo','Demo & καθαρή παραγωγική λειτουργία','Demo & clean production operation','Πώς διαχωρίζονται τα δοκιμαστικά δεδομένα από την πραγματική εγκατάσταση.','How demo data is separated from the real installation.',{
    purpose:bi('Να επιτρέπει εκπαίδευση και παρουσίαση χωρίς να αναμειγνύονται δοκιμαστικές εγγραφές με πραγματικά δεδομένα.','Allow training and presentation without mixing demo records with real data.'),
    audience:bi('Διαχειριστές, εκπαιδευτές και χρήστες επίδειξης.','Administrators, trainers and demo users.'),
    steps:{el:['Χρησιμοποιήστε «Είσοδος Demo» όταν θέλετε δοκιμαστικές εγγραφές.','Στην κανονική είσοδο οι λειτουργικές λίστες ξεκινούν χωρίς demo records.','Οι βιβλιοθήκες παραμένουν διαθέσιμες ως master data.','Μην χρησιμοποιείτε Demo για πραγματικές καταχωρήσεις.'],en:['Use Demo sign-in when test records are required.','In normal sign-in operational lists start without demo records.','Libraries remain available as master data.','Do not use Demo for real records.']},
    important:{el:['Ασθενείς, προσωπικό, συμβάντα, επιτροπές, εκπαιδεύσεις, έγγραφα και εργαστηριακές εγγραφές δεν πρέπει να παραδίδονται ως production seed data.'],en:['Patients, staff, incidents, committees, training, documents and laboratory records must not be shipped as production seed data.']},
    related:bi('Login · Κέντρο Διαχείρισης · Βιβλιοθήκες','Login · Management Center · Libraries')
  }),
  item('about','Σχετικά με την εφαρμογή','About the application','Πληροφορίες προϊόντος και έκδοσης.','Product and version information.',{
    purpose:bi('Να εμφανίζει με διακριτικό τρόπο την ταυτότητα και την τρέχουσα έκδοση της εφαρμογής.','Display product identity and current version without cluttering the user menu.'),
    audience:bi('Όλοι οι χρήστες και τεχνική υποστήριξη.','All users and technical support.'),
    steps:{el:['Healthcare Suite','Έκδοση 0.12.0-rc.20','Η παρούσα έκδοση περιλαμβάνει αναλυτικό Help Center, contextual guidance, συγκριτικά analytics και καθαρό διαχωρισμό Production/Demo.'],en:['Healthcare Suite','Version 0.12.0-rc.20','This release includes a detailed Help Center, contextual guidance, comparative analytics and clean Production/Demo separation.']},
    important:{el:['Η ένδειξη έκδοσης είναι πληροφοριακή και δεν αποτελεί λειτουργική ρύθμιση.'],en:['Version information is informational and is not a functional setting.']},
    related:bi('Βοήθεια · Τεχνική υποστήριξη','Help · Technical support')
  })
]
