import { bi, item } from './helpContentUtils'

export const adminHelpSections=[
  item('quality','Ποιότητα','Quality','Συμβάντα, audits, CAPA, Risk Register, δείκτες και αναφορές με πλήρη σύνδεση και traceability.','Incidents, audits, CAPA, Risk Register, indicators and reports with linked traceability.',{
    purpose:bi('Να υποστηρίζει τον κύκλο αναγνώριση → διερεύνηση → ενέργεια → έλεγχος αποτελεσματικότητας → βελτίωση.','Support the detect → investigate → act → verify effectiveness → improve cycle.'),
    audience:bi('Ποιότητα, διοίκηση, Επιτροπή Λοιμώξεων και εξουσιοδοτημένοι owners.','Quality, management, Infection Control Committee and authorised owners.'),
    steps:{el:['Στα Συμβάντα καταγράψτε γεγονός, σοβαρότητα, έκβαση, τμήμα και διερεύνηση.','Στα Audits χρησιμοποιήστε το κατάλληλο template, καταγράψτε findings και οριστικοποιήστε μόνο όταν το evidence είναι πλήρες.','Από εύρημα/συμβάν/δείκτη δημιουργήστε CAPA όταν απαιτείται, αποφεύγοντας διπλή ενέργεια για την ίδια πηγή.','Στην CAPA τεκμηριώστε root cause, action plan, owner, due date, evidence και effectiveness verification; CAPA closure requires verified effectiveness, severe-incident closure requires investigation ownership/conclusion and lessons learned, and risk acceptance/closure requires documented controls.','Στο Risk Register αξιολογήστε inherent/residual risk και προγραμματίστε review.','Στους Δείκτες ελέγξτε numerator, denominator, source, στόχο και definition version.','Χρησιμοποιήστε το Audit Trail στο Governance για ανεξάρτητη απόδειξη των αλλαγών.'],en:['In Incidents record event, severity, outcome, department and investigation.','In Audits use the appropriate template, record findings and finalise only when evidence is complete.','Create CAPA from a finding/incident/indicator when required, avoiding duplicate actions for one source.','In CAPA document root cause, action plan, owner, due date, evidence and effectiveness verification.','In Risk Register assess inherent/residual risk and schedule review.','For Indicators review numerator, denominator, source, target and definition version.','Use Governance Audit Trail as independent evidence of changes.']},
    important:{el:['Finalized audit evidence δεν πρέπει να τροποποιείται σαν draft.','CAPA δεν κλείνει μόνο επειδή ολοκληρώθηκε η ενέργεια· απαιτείται όπου προβλέπεται έλεγχος αποτελεσματικότητας.'],en:['Finalised audit evidence must not be edited like a draft.','CAPA is not closed merely because an action was completed; effectiveness verification is required where applicable.']},
    related:bi('Governance · Δείκτες · Έγγραφα · Εκπαίδευση','Governance · Indicators · Documents · Training')
  }),
  item('organization','Επιτροπές, Εκπαίδευση & Έγγραφα','Committees, Training & Documents','Οργανωτική τεκμηρίωση, συνεδριάσεις, παρουσιολόγια, εκπαιδευτικές δράσεις και αρχεία.','Organisational documentation, meetings, attendance, training activities and files.',{
    purpose:bi('Να διατηρεί την οργανωτική και εκπαιδευτική τεκμηρίωση συνδεδεμένη με τους πραγματικούς χρήστες/εργαζομένους.','Keep organisational and training documentation connected with real users/employees.'),
    audience:bi('Επιτροπές, εκπαιδευτές, ομάδα λοιμώξεων και διοίκηση.','Committees, trainers, infection control and management.'),
    steps:{el:['Στις Επιτροπές καταχωρήστε μέλη, ρόλους/καθήκοντα και συνεδρίες.','Στις συνεδρίες καταγράψτε παρόντες/απόντες, πρακτικά και επόμενη συνάντηση.','Στην Εκπαίδευση δημιουργήστε δράση και επιλέξτε μαζικά τους συμμετέχοντες όπου χρειάζεται.','Χρησιμοποιήστε παρουσιολόγιο και σχετικά αρχεία για πλήρη τεκμηρίωση.','Στα Έγγραφα χρησιμοποιήστε προβολή μέσα από την εφαρμογή όπου υποστηρίζεται.'],en:['In Committees record members, roles/duties and meetings.','For meetings record attendees/absentees, minutes and next meeting.','In Training create an activity and bulk-select participants when appropriate.','Use attendance and related files for complete documentation.','In Documents use in-app viewing where supported.']},
    important:{el:['Η ιδιότητα και το τμήμα εργαζομένου πρέπει να προέρχονται από τις κοινές βιβλιοθήκες.','Τα αρχεία τεκμηρίωσης πρέπει να συνδέονται με τη σωστή εγγραφή και όχι να παραμένουν ασύνδετα.'],en:['Employee professional category and department must come from shared libraries.','Documentation files should be linked to the correct record rather than left orphaned.']},
    related:bi('Εργαζόμενοι · Ποιότητα · Κέντρο Διαχείρισης','Employees · Quality · Management Center')
  }),
  item('management','Κέντρο Διαχείρισης','Management Center','Κεντρικό σημείο παραμετροποίησης για βιβλιοθήκες, δείκτες, φόρμες, ρόλους, λογαριασμούς και governance.','Central configuration point for libraries, indicators, forms, roles, accounts and governance.',{
    purpose:bi('Να διατηρεί κοινά master data και ελεγχόμενες διοικητικές ρυθμίσεις χωρίς να επιβαρύνει τις καθημερινές ροές.','Maintain shared master data and controlled administrative settings without burdening daily workflows.'),
    audience:bi('Διαχειριστές και ειδικά εξουσιοδοτημένοι χρήστες.','Administrators and specifically authorised users.'),
    steps:{el:['Στις Βιβλιοθήκες διαχειριστείτε Τμήματα, Ιδιότητες, Μικροοργανισμούς, Αντιβιοτικά, ερωτηματολόγια και λοιπά master data.','Στους Ρόλους & Δικαιώματα ρυθμίστε visibility, scope και capabilities.','Στους Χρήστες δημιουργήστε λογαριασμό μόνο για πραγματικό εργαζόμενο/ανάγκη πρόσβασης.','Στους Δείκτες διαχειριστείτε στόχο, direction, numerator/denominator definitions, owner, benchmark και governance version.','Στο Governance & Συμμόρφωση ελέγξτε Audit Trail, ειδοποιήσεις/κλιμάκωση, retention, continuity, privacy και competency gaps.','Μετά από διοικητική αλλαγή κάντε role/flow test αντί να θεωρείτε ότι η ρύθμιση είναι σωστή μόνο επειδή αποθηκεύτηκε.'],en:['In Libraries manage Departments, Professional categories, Microorganisms, Antibiotics, questionnaires and other master data.','In Roles & Permissions applies least-privilege controls; Management Center access is a protected rule reserved for Administrator configure visibility, scope and capabilities.','In Users create accounts only for real staff/access needs.','In Indicators manage target, direction, numerator/denominator definitions, owner, benchmark and governance version.','In Governance & Compliance review Audit Trail, notifications/escalation, retention, continuity, privacy and competency gaps.','After an administrative change perform a role/flow test rather than assuming it is correct because it saved.']},
    important:{el:['Οι λειτουργικές production εγγραφές δεν είναι master data και δεν πρέπει να seedάρονται.','Αλλαγές σε permissions και governance πρέπει να παραμένουν tenant-scoped.'],en:['Operational production records are not master data and must not be seeded.','Permission and governance changes must remain tenant-scoped.']},
    related:bi('Governance · Ρόλοι & Δικαιώματα εφαρμόζει least privilege· η πρόσβαση στο Κέντρο Διαχείρισης είναι προστατευμένος κανόνας αποκλειστικά για τον Διαχειριστή · Δείκτες · Βιβλιοθήκες','Governance · Roles & Permissions applies least-privilege controls; Management Center access is a protected rule reserved for Administrator · Indicators · Libraries')
  }),
  item('indicators','Δείκτες & Ανάλυση','Indicators & Analytics','Κεντρική παρακολούθηση KPIs με πηγή, numerator/denominator, στόχο, περίοδο, ιστορικό και συγκριτική ανάλυση.','Central KPI monitoring with source, numerator/denominator, target, period, history and comparative analytics.',{
    purpose:bi('Να παρέχει μετρήσιμη εικόνα και να διατηρεί provenance του τρόπου υπολογισμού.','Provide measurable oversight while preserving calculation provenance.'),
    audience:bi('Ποιότητα, Επιτροπή Λοιμώξεων, διοίκηση και εξουσιοδοτημένοι analysts.','Quality, Infection Control Committee, management and authorised analysts.'),
    steps:{el:['Χρησιμοποιήστε φίλτρα κατηγορίας, κατάστασης, συχνότητας και ημερομηνιών.','Ανοίξτε δείκτη για τρέχουσα τιμή, στόχο, numerator, denominator και source inputs.','Στο Management mode τεκμηριώστε formula, numerator/denominator definitions, exclusions, owner, benchmark και governance version.','Το definition history καταγράφει τις μεταβολές του ορισμού.','Η Ανάλυση συγκρίνει έτη/περιόδους για μικροβιολογία, λοιμώξεις, συμβάντα, εκπαίδευση και αντιμικροβιακά.','Οι δείκτες Antimicrobial Stewardship περιλαμβάνουν κατανάλωση DDD, ποσοστό εγκρίσεων προωθημένων αντιβιοτικών και εκκρεμή αιτήματα.'],en:['Use category, status, frequency and date filters.','Open an indicator for current value, target, numerator, denominator and source inputs.','In Management mode document formula, numerator/denominator definitions, exclusions, owner, benchmark and governance version.','Definition history records changes to the indicator definition.','Analytics compares years/periods across microbiology, infections, incidents, training and antimicrobials.','Antimicrobial Stewardship indicators include DDD consumption, restricted-antibiotic approval rate and pending requests.']},
    important:{el:['Όταν λείπει παρονομαστής, ένας rate δεν πρέπει να παρουσιάζεται ως συγκρίσιμος.','Αλλαγή formula/definition χρειάζεται νέα governance version και διατηρεί ιστορικό.'],en:['When a denominator is missing, a rate must not be presented as comparable.','Formula/definition changes require a new governance version and retain history.']},
    related:bi('Dashboard · LIRA · Ποιότητα · Αντιμικροβιακή Επιτήρηση','Dashboard · LIRA · Quality · Antimicrobial Surveillance')
  }),
  item('notifications','Ειδοποιήσεις & κλιμάκωση','Notifications & escalation','Κεντρικές ειδοποιήσεις για πραγματικές εκκρεμότητες με role filtering και governance thresholds.','Central alerts for real pending actions with role filtering and governance thresholds.',{
    purpose:bi('Να αναδεικνύει όσα απαιτούν ενέργεια χωρίς να γεμίζει το σύστημα με μελλοντικές ή δοκιμαστικές υπενθυμίσεις.','Surface items requiring action without flooding the system with future or test reminders.'),
    audience:bi('Οι αντίστοιχοι ρόλοι ανά πολιτική ειδοποίησης.','Roles targeted by each notification policy.'),
    steps:{el:['Ανοίξτε το καμπανάκι στο header για τις ενεργές ειδοποιήσεις.','Πατήστε ειδοποίηση για να ανοίξετε την πρωτογενή εγγραφή.','Οι ληξιπρόθεσμες CAPA, αναθεωρήσεις εγγράφων, κρίσιμα αποτελέσματα, σοβαρά συμβάντα, competency follow-up και εκπρόθεσμες ενέργειες επιτροπών μπορούν να διέπονται από governance policy. Οι οριστικοποιημένες συνεδριάσεις παραμένουν ιστορικά σταθερές, αλλά η κατάσταση των ενεργειών αποφάσεων μπορεί να ενημερώνεται μέχρι «Ολοκληρωμένη», οπότε η σχετική ειδοποίηση κλείνει.','Όταν ξεπεραστεί το escalation threshold η ειδοποίηση σημειώνεται ως «Κλιμακωμένη».','Οι πολιτικές ρυθμίζονται από Governance & Συμμόρφωση: enabled, severity, ώρες κλιμάκωσης, recipient roles και closed-loop.'],en:['Open the header bell for active notifications.','Select an alert to open its source record.','Overdue CAPA, document reviews, critical results, serious incidents, competency follow-up and overdue committee actions can be governed by policy. Finalized meeting records remain historically fixed, while decision-action status can be updated through Completed, which closes the related alert.','When the escalation threshold is exceeded the alert is marked Escalated.','Policies are configured in Governance & Compliance: enabled, severity, escalation hours, recipient roles and closed-loop.']},
    important:{el:['Κρίσιμο εργαστηριακό αποτέλεσμα παραμένει ενεργό μέχρι να τεκμηριωθεί γνωστοποίηση.','«Όλες διαβασμένες» κρύβει την ειδοποίηση για τον χρήστη· δεν αλλάζει την κλινική/ποιοτική κατάσταση της πρωτογενούς εγγραφής.'],en:['A critical laboratory result remains active until communication is documented.','Mark all read hides the alert for the user; it does not change the clinical/quality state of the source record.']},
    related:bi('Governance · Εργαστήριο · CAPA · Έγγραφα','Governance · Laboratory · CAPA · Documents')
  }),
  item('governance','Governance & Συμμόρφωση','Governance & Compliance','Διοικητικός χώρος για auditability, escalation, retention, business continuity, privacy και competency oversight.','Administrative workspace for auditability, escalation, retention, business continuity, privacy and competency oversight.',{
    purpose:bi('Να συγκεντρώνει τεκμήρια ελέγχου χωρίς να προσθέτει πεδία στις καθημερινές κλινικές φόρμες.','Centralise governance evidence without adding fields to daily clinical forms.'),
    audience:bi('Admin, Ποιότητα και κατάλληλα εξουσιοδοτημένοι υπεύθυνοι.','Admin, Quality and appropriately authorised owners.'),
    steps:{el:['Στο Audit Trail αναζητήστε ποιος άλλαξε τι, πότε και σε ποια οντότητα. Το log είναι read-only/append-only evidence.','Στις Ειδοποιήσεις & κλιμάκωση ρυθμίστε severity, threshold, recipient roles και closed-loop όπου απαιτείται.','Στη Διατήρηση δεδομένων ορίστε διάρκεια, disposition, owner και οργανωτική/νομική βάση. Η λήξη δεν προκαλεί αυτόματη destructive διαγραφή.','Στη Συνέχεια λειτουργίας τεκμηριώστε provider, scope, frequency, RPO/RTO και recovery runbook.','Καταγράψτε restore/failover/tabletop tests με evidence, actual RPO/RTO, findings και corrective action reference.','Στο Security & Privacy διατηρήστε το GDPR readiness checklist και ελέγξτε server-side security events.','Στα Κενά επάρκειας ελέγξτε ληγμένη/ανεπαρκή competency και ανάγκες επανεκπαίδευσης. Για ολοκληρωμένη εκπαίδευση με competency απαιτούνται αποτέλεσμα, αξιολογητής και ημερομηνία. Η «Επαρκής» αξιολόγηση χρειάζεται ισχύ, ενώ η ανάγκη επανεκπαίδευσης χρειάζεται τεκμηριωμένο σχέδιο/σημείωση και παραμένει open follow-up μέχρι νέα επαρκή αξιολόγηση.'],en:['In Audit Trail search who changed what, when and on which entity. The log is read-only/append-only evidence.','In Notifications & escalation configure severity, threshold, recipient roles and closed-loop where required.','In Data retention define duration, disposition, owner and organisational/legal basis. Expiry does not cause automatic destructive deletion.','In Business continuity document provider, scope, frequency, RPO/RTO and recovery runbook.','Record restore/failover/tabletop tests with evidence, actual RPO/RTO, findings and corrective-action reference.','In Security & Privacy maintain the GDPR readiness checklist and review server-side security events.','In Competency gaps review expired/insufficient competency and retraining needs. Completed competency-assessed training requires result, assessor and assessment date. A Competent result needs validity; retraining requires a documented plan/note and remains open follow-up until a new competent assessment.']},
    important:{el:['Το Governance Center υποστηρίζει ISO/JCI/ασφάλεια, αλλά δεν αποτελεί από μόνο του πιστοποίηση ή accreditation.','Πραγματικό backup και restore test πρέπει να εκτελούνται στην υποδομή και να τεκμηριώνονται εδώ. Στα ελεγχόμενα έγγραφα εφαρμόζεται διαχωρισμός καθηκόντων: ο συντάκτης/υποβάλλων δεν μπορεί να εγκρίνει ο ίδιος την έκδοση.'],en:['Governance Center supports ISO/JCI/security processes but is not by itself certification or accreditation.','Actual backups and restore tests must be performed in infrastructure and evidenced here. Controlled documents enforce segregation of duties: the preparer/submitter cannot approve the same version.']},
    related:bi('Ποιότητα · Ειδοποιήσεις · Ρόλοι · Εκπαίδευση · Έγγραφα','Quality · Notifications · Roles · Training · Documents')
  }),
  item('roles','Ρόλοι, δικαιώματα & λογαριασμοί','Roles, permissions & accounts','Διαχείριση πρόσβασης με βάση ρόλο, τμήμα και πρόσθετες αρμοδιότητες.','Access management based on role, department and additional capabilities.',{
    purpose:bi('Να εξασφαλίζει ότι κάθε χρήστης βλέπει μόνο όσα απαιτεί ο ρόλος του.','Ensure each user sees only what their role requires.'),
    audience:bi('Διαχειριστές.','Administrators.'),
    steps:{el:['Επιλέξτε ή δημιουργήστε τον κατάλληλο ρόλο.','Ορίστε βασικό τμήμα και scope πρόσβασης.','Προσθέστε μόνο τις πρόσθετες αρμοδιότητες που χρειάζονται.','Δημιουργήστε/συνδέστε τον λογαριασμό χρήστη.','Κάντε δοκιμαστική είσοδο με τον συγκεκριμένο ρόλο και ελέγξτε sidebar, λίστες, προβολή και επεξεργασία.'],en:['Choose or create the appropriate role.','Set primary department and access scope.','Add only the additional capabilities required.','Create/link the user account.','Test-sign in with that role and verify sidebar, lists, viewing and editing.']},
    important:{el:['Η καρτέλα εργαζομένου δεν αποτελεί από μόνη της λογαριασμό σύνδεσης.','Μην αποθηκεύετε πραγματικούς κωδικούς πρόσβασης σε απλό κείμενο.','Η επαναφορά κωδικού πρέπει να γίνεται μέσω της υπηρεσίας ταυτοποίησης.'],en:['An employee record is not by itself a sign-in account.','Never store real passwords in plain text.','Password reset should be handled through the authentication service.']},
    related:bi('Προφίλ · Κέντρο Διαχείρισης · Ασφάλεια','Profile · Management Center · Security')
  }),
  item('lira','LIRA','LIRA','Εξηγήσιμη, rule-based περιοχή Healthcare Intelligence που συσχετίζει τα δεδομένα της εφαρμογής χωρίς εξωτερικό AI model.','Explainable rule-based Healthcare Intelligence that correlates application data without an external AI model.',{
    purpose:bi('Να αναδεικνύει προτεραιότητες, τάσεις και κενά δεδομένων και να οδηγεί πάντα στην πρωτογενή πηγή.','Surface priorities, trends and data gaps while always linking back to source evidence.'),
    audience:bi('Εξουσιοδοτημένοι χρήστες επιτήρησης, ποιότητας και διοίκησης.','Authorised surveillance, quality and management users.'),
    steps:{el:['Ανοίξτε LIRA και χρησιμοποιήστε τις γρήγορες ερωτήσεις ή γράψτε ερώτημα.','Τα σήματα καλύπτουν MDR/XDR, CAPA, risks, προωθημένα αντιβιοτικά, έγγραφα και competency όταν υπάρχουν αντίστοιχα δεδομένα.','Κάθε σήμα εμφανίζει τη βάση/rule που το ενεργοποίησε και κουμπί «Άνοιγμα πηγής».','Ελέγξτε την ένδειξη Ποιότητα δεδομένων: αν λείπουν patient-days, οι denominator-based rates δεν πρέπει να ερμηνεύονται ως συγκρίσιμοι.','Χρησιμοποιήστε την πρωτογενή εγγραφή ως τελικό evidence πριν από κλινική ή διοικητική ενέργεια.'],en:['Open LIRA and use quick questions or type a question.','Signals cover MDR/XDR, CAPA, risks, restricted antimicrobials, documents and competency when corresponding data exist.','Each signal shows the rule/evidence basis that triggered it and an Open source action.','Review Data quality: if patient-days are missing, denominator-based rates must not be interpreted as comparable.','Use the source record as final evidence before any clinical or administrative action.']},
    important:{el:['Η LIRA είναι decision support, όχι αυτόνομη κλινική απόφαση.','Η τρέχουσα υλοποίηση χρησιμοποιεί deterministic calculations/rules και δεν στέλνει δεδομένα σε εξωτερικό LLM από τη σελίδα.'],en:['LIRA is decision support, not autonomous clinical decision-making.','The current implementation uses deterministic calculations/rules and sends no data to an external LLM from the page.']},
    related:bi('Δείκτες · Εργαστήριο · Ποιότητα · Εκπαίδευση · Έγγραφα','Indicators · Laboratory · Quality · Training · Documents')
  }),
  item('profile','Προφίλ, γλώσσα & προσβασιμότητα','Profile, language & accessibility','Προσωπικές πληροφορίες πρόσβασης, επιλογή γλώσσας και ρυθμίσεις προσβασιμότητας.','Personal access information, language selection and accessibility settings.',{
    purpose:bi('Να δείχνει στον χρήστη με ποιον ρόλο και scope εργάζεται και να προσαρμόζει την παρουσίαση στις ανάγκες του.','Show the user which role and scope are active and adapt presentation to their needs.'),
    audience:bi('Όλοι οι χρήστες.','All users.'),
    steps:{el:['Ανοίξτε το Προφίλ από το όνομα χρήστη επάνω δεξιά.','Ελέγξτε ρόλο, βασικό τμήμα και πρόσθετες αρμοδιότητες.','Αλλάξτε γλώσσα από το EL/EN χωρίς να αλλάζει η λειτουργική κατάσταση της εφαρμογής.','Χρησιμοποιήστε το μενού Προσβασιμότητας για μέγεθος κειμένου, υψηλή αντίθεση ή reduced motion.'],en:['Open Profile from the user menu in the upper right.','Review role, primary department and additional capabilities.','Change language using EL/EN without changing application state.','Use Accessibility for text size, high contrast or reduced motion.']},
    important:{el:['Ρόλος, τμήμα και δικαιώματα δεν αλλάζουν από το Προφίλ· διαχειρίζονται από το Κέντρο Διαχείρισης.'],en:['Role, department and permissions are not changed from Profile; they are managed in the Management Center.']},
    related:bi('Ρόλοι & Δικαιώματα · Κέντρο Διαχείρισης','Roles & Permissions applies least-privilege controls; Management Center access is a protected rule reserved for Administrator · Management Center')
  }),
  item('demo','Demo & καθαρή παραγωγική λειτουργία','Demo & clean production operation','Πώς διαχωρίζονται τα δοκιμαστικά δεδομένα από την πραγματική εγκατάσταση.','How demo data is separated from the real installation.',{
    purpose:bi('Να επιτρέπει εκπαίδευση και παρουσίαση χωρίς να αναμειγνύονται δοκιμαστικές εγγραφές με πραγματικά δεδομένα.','Allow training and presentation without mixing demo records with real data.'),
    audience:bi('Διαχειριστές, εκπαιδευτές και χρήστες επίδειξης.','Administrators, trainers and demo users.'),
    steps:{el:['Χρησιμοποιήστε «Είσοδος Demo» όταν θέλετε δοκιμαστικές εγγραφές.','Στην κανονική είσοδο οι λειτουργικές λίστες ξεκινούν χωρίς demo records.','Οι βιβλιοθήκες παραμένουν διαθέσιμες ως master data.','Μην χρησιμοποιείτε Demo για πραγματικές καταχωρήσεις.'],en:['Use Demo sign-in when test records are required.','In normal sign-in operational lists start without demo records.','Libraries remain available as master data.','Do not use Demo for real records.']},
    important:{el:['Ασθενείς, προσωπικό, συμβάντα, επιτροπές, εκπαιδεύσεις, έγγραφα και εργαστηριακές εγγραφές δεν πρέπει να παραδίδονται ως production seed data.'],en:['Patients, staff, incidents, committees, training, documents and laboratory records must not be shipped as production seed data.']},
    related:bi('Login · Κέντρο Διαχείρισης · Βιβλιοθήκες','Login · Management Center · Libraries')
  }),
  item('about','Σχετικά με την εφαρμογή','About the application','Πληροφορίες προϊόντος και έκδοσης.','Product and version information.',{
    purpose:bi('Να εμφανίζει με διακριτικό τρόπο την ταυτότητα και την τρέχουσα έκδοση της εφαρμογής.','Display product identity and current version without cluttering the user menu.'),
    audience:bi('Όλοι οι χρήστες και τεχνική υποστήριξη.','All users and technical support.'),
    steps:{el:['Healthcare Suite','Έκδοση 0.12.0-rc.108','Η παρούσα έκδοση περιλαμβάνει αναλυτικό Help Center, contextual guidance, συγκριτικά analytics και καθαρό διαχωρισμό Production/Demo.'],en:['Healthcare Suite','Version 0.12.0-rc.108','This release includes a detailed Help Center, contextual guidance, comparative analytics and clean Production/Demo separation.']},
    important:{el:['Η ένδειξη έκδοσης είναι πληροφοριακή και δεν αποτελεί λειτουργική ρύθμιση.'],en:['Version information is informational and is not a functional setting.']},
    related:bi('Βοήθεια · Τεχνική υποστήριξη','Help · Technical support')
  })
]
