import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Calculator, Download, Pill, Plus, Printer, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Badge, Button, Drawer, EntityCell, EntitySummary, FormActions, FormField, FormGrid, FormSection, ListWorkspace, PageChrome, PageHeader, StatCard } from '../../components/core'
import { confirmAction, notifyAction } from '../../components/core/feedback'
import { normalizeText, selectedRows, sortRows } from '../../core/utils/entityList'
import { downloadCsv, printRows } from '../../core/utils/listExport'
import { activeMasterItems, masterNames } from '../../services/masterDataService'
import { loadAntibioticDDD, loadDailyCensus } from '../../services/indicatorSourceDataService'
import { deleteIndicatorSourceRecordBackend, hydrateIndicatorBackend, saveIndicatorSourceRecordBackend } from '../../services/backend/indicatorBackendService'
import { APP_ROUTES } from '../../config/routes'
import { useI18n } from '../../i18n'
import './AntimicrobialSurveillance.css'

const EMPTY={date:'',department:'',antibiotic:'',atc:'',route:'',strength:'',strengthUnit:'mg',packSize:'',packages:'',dddGrams:'',aware:'',notes:''}
const ROUTES=['PO','IV','IM','PR','Inhaled','Other']
const AWARE=['Access','Watch','Reserve','Not classified']
const num=v=>Number(String(v??'').replace(',','.'))||0
const grams=(strength,unit)=>unit==='g'?num(strength):unit==='mcg'?num(strength)/1e6:num(strength)/1000
function calc(row){const totalGrams=grams(row.strength,row.strengthUnit)*num(row.packSize)*num(row.packages);const dddValue=num(row.dddGrams);const computed=dddValue?totalGrams/dddValue:0;return{totalGrams:totalGrams||num(row.totalGrams),ddd:computed||num(row.ddd)}}
function patientDaysFor(rows,department){return rows.filter(r=>!department||r.department===department).reduce((s,r)=>s+num(r.patientDays||r.totalPatients),0)}
function fmt(v,d=1){return new Intl.NumberFormat('el-GR',{maximumFractionDigits:d}).format(Number(v)||0)}

export default function AntimicrobialConsumptionPage(){
 const {language}=useI18n(); const L=(el,en)=>language==='en'?en:el; const navigate=useNavigate()
 const [records,setRecords]=useState(loadAntibioticDDD); const [saving,setSaving]=useState(false)
 useEffect(()=>{hydrateIndicatorBackend().then(data=>setRecords(data.antibioticDDD||[])).catch(()=>{})},[]); const [search,setSearch]=useState(''); const [department,setDepartment]=useState(''); const [sort,setSort]=useState({key:'date',direction:'desc'}); const [selectedKeys,setSelectedKeys]=useState([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(EMPTY)
 const departments=masterNames('departments'); const drugs=activeMasterItems('antibiotics')
 const filtered=useMemo(()=>{const q=normalizeText(search);return sortRows(records.filter(r=>(!department||r.department===department)&&(!q||normalizeText([r.antibiotic,r.atc,r.department,r.route,r.aware].join(' ')).includes(q))),sort)},[records,search,department,sort])
 const selected=useMemo(()=>selectedRows(filtered,selectedKeys),[filtered,selectedKeys]); const census=loadDailyCensus()
 const metrics=useMemo(()=>{const ddd=filtered.reduce((s,r)=>s+calc(r).ddd,0);const days=patientDaysFor(census,department);return{rows:filtered.length,ddd,days,rate:days?ddd/days*1000:0}},[filtered,department,census])
 function newRow(){setEditing(null);setForm({...EMPTY,date:new Date().toISOString().slice(0,10)});setOpen(true)}
 function edit(row){setEditing(row);setForm({...EMPTY,...row});setOpen(true)}
 function close(){setOpen(false);setEditing(null);setForm(EMPTY)}
 function field(k,v){setForm(c=>({...c,[k]:v}))}
 function chooseDrug(name){const d=drugs.find(x=>x.name===name)||{};setForm(c=>({...c,antibiotic:name,atc:d.atc||'',dddGrams:d.dddGrams||'',route:d.dddRoute||c.route||'',aware:d.aware||''}))}
 async function save(e){e.preventDefault();if(saving)return;if(!form.date||!form.antibiotic||!form.strength||!form.packSize||!form.packages||!form.dddGrams){notifyAction(L('Συμπληρώστε ημερομηνία, αντιμικροβιακό, περιεκτικότητα, μέγεθος/αριθμό συσκευασιών και WHO DDD.','Complete date, antimicrobial, strength, pack size/packages and WHO DDD.'));return}const c=calc(form);const row={...form,id:editing?.id||`AMC-${Date.now()}`,totalGrams:c.totalGrams,ddd:c.ddd,updatedAt:new Date().toISOString()};try{setSaving(true);const saved=await saveIndicatorSourceRecordBackend('antibiotic_ddd',row);setRecords(current=>current.some(x=>x.id===saved.id)?current.map(x=>x.id===saved.id?saved:x):[saved,...current]);notifyAction(L('Η κατανάλωση αποθηκεύτηκε στο Supabase.','Consumption record saved to Supabase.'),'success');close()}catch(error){notifyAction(error?.message||L('Η αποθήκευση απέτυχε.','Save failed.'),'error')}finally{setSaving(false)}}
 async function remove(){if(!editing||saving||!confirmAction(L('Να διαγραφεί η εγγραφή κατανάλωσης;','Delete this consumption record?')))return;try{setSaving(true);await deleteIndicatorSourceRecordBackend('antibiotic_ddd',editing.id);setRecords(current=>current.filter(x=>x.id!==editing.id));notifyAction(L('Η εγγραφή διαγράφηκε από το Supabase.','Consumption record deleted from Supabase.'),'success');close()}catch(error){notifyAction(error?.message||L('Η διαγραφή απέτυχε.','Delete failed.'),'error')}finally{setSaving(false)}}
 const columns=[{key:'date',label:L('Ημερομηνία','Date'),width:'125px',sortable:true},{key:'antibiotic',label:L('Αντιμικροβιακό','Antimicrobial'),sortable:true,render:r=><EntityCell primary={r.antibiotic} secondary={[r.atc,r.route,r.aware].filter(Boolean).join(' · ')}/>},{key:'department',label:L('Τμήμα','Department'),sortable:true,render:r=>r.department||L('Σύνολο νοσοκομείου','Hospital total')},{key:'packages',label:L('Συσκευασίες','Packages'),width:'120px'},{key:'ddd',label:'DDD',width:'110px',render:r=>fmt(calc(r).ddd,2)},{key:'rate',label:'DDD / 1.000 bed-days',width:'190px',render:r=>{const days=patientDaysFor(census,r.department);return days?fmt(calc(r).ddd/days*1000,2):'—'}}]
 const exportCols=[{label:'Date',value:r=>r.date},{label:'Antimicrobial',value:r=>r.antibiotic},{label:'ATC',value:r=>r.atc},{label:'Route',value:r=>r.route},{label:'Department',value:r=>r.department},{label:'Packages',value:r=>r.packages},{label:'Total grams',value:r=>calc(r).totalGrams},{label:'DDD',value:r=>calc(r).ddd},{label:'AWaRe',value:r=>r.aware}]
 return <PageChrome className="antimicrobial-page" header={<PageHeader title={L('Αντιμικροβιακή Επιτήρηση','Antimicrobial Surveillance')} description={L('Έγκριση περιορισμένης χρήσης και επιτήρηση κατανάλωσης με ATC/DDD.','Restricted-use approval and ATC/DDD consumption surveillance.')} actions={<Button icon={<Plus size={17}/>} onClick={newRow}>{L('Νέα κατανάλωση','New consumption')}</Button>}/> }>
  <div className="antimicrobial-tabs"><Button type="button" variant="secondary" onClick={()=>navigate(APP_ROUTES.PROMOTED_ANTIBIOTICS)}>{L('Προωθημένα Αντιβιοτικά','Restricted Antibiotics')}</Button><Button type="button" className="active">{L('Κατανάλωση Αντιμικροβιακών','Antimicrobial Consumption')}</Button></div>
  <div className="amc-method-note"><strong>WHO GLASS-AMC</strong><span>{L('DDD = συνολικά γραμμάρια δραστικής ουσίας ÷ WHO DDD. Ο νοσοκομειακός δείκτης εμφανίζεται ανά 1.000 ημέρες νοσηλείας.','DDD = total grams of active substance ÷ WHO DDD. The hospital indicator is shown per 1,000 patient-days.')}</span></div>
  <ListWorkspace stats={<EntitySummary columns={4}><StatCard compact icon={Pill} label={L('Εγγραφές','Records')} value={metrics.rows}/><StatCard compact icon={Calculator} label={L('Σύνολο DDD','Total DDD')} value={fmt(metrics.ddd,1)}/><StatCard compact icon={BarChart3} label={L('Ημέρες νοσηλείας','Patient-days')} value={fmt(metrics.days,0)}/><StatCard compact icon={BarChart3} label="DDD / 1.000 bed-days" value={metrics.days?fmt(metrics.rate,2):'—'}/></EntitySummary>} searchValue={search} onSearchChange={setSearch} searchPlaceholder={L('Αναζήτηση αντιμικροβιακού, ATC, τμήματος…','Search antimicrobial, ATC, department…')} filters={<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">{L('Όλα τα τμήματα','All departments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</select>} activeFilterCount={[search,department].filter(Boolean).length} onClearFilters={()=>{setSearch('');setDepartment('')}} selectedCount={selected.length} selectedLabel={L('εγγραφές','records')} onClearSelection={()=>setSelectedKeys([])} bulkActions={<><Button variant="secondary" size="sm" icon={<Printer size={16}/>} onClick={()=>printRows({title:'Antimicrobial Consumption — WHO ATC/DDD',columns:exportCols,rows:selected})}>{L('Εκτύπωση / PDF','Print / PDF')}</Button><Button variant="secondary" size="sm" icon={<Download size={16}/>} onClick={()=>downloadCsv({filename:'antimicrobial-consumption.csv',columns:exportCols,rows:selected})}>{L('Εξαγωγή CSV','Export CSV')}</Button></>} columns={columns} rows={filtered} getRowKey={r=>r.id} onRowClick={edit} selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys} sort={sort} onSortChange={setSort} emptyTitle={L('Δεν υπάρχουν δεδομένα κατανάλωσης','No consumption data')}/>
  <Drawer open={open} onClose={close} title={editing?L('Επεξεργασία κατανάλωσης','Edit consumption'):L('Νέα κατανάλωση αντιμικροβιακού','New antimicrobial consumption')} description={L('Καταχώρηση product-level δεδομένων για αυτόματο υπολογισμό DDD.','Product-level data entry for automatic DDD calculation.')} width={1100} position="center" footer={<FormActions form="amc-form" onCancel={close} extraActions={editing?<Button variant="danger" icon={<Trash2 size={16}/>} onClick={remove}>{L('Διαγραφή','Delete')}</Button>:null}/> }>
   <form id="amc-form" onSubmit={save}><FormSection title={L('Περίοδος & φάρμακο','Period & medicine')}><FormGrid columns={3}><FormField label={L('Ημερομηνία','Date')} required><input type="date" value={form.date} onChange={e=>field('date',e.target.value)}/></FormField><FormField label={L('Τμήμα','Department')}><select value={form.department} onChange={e=>field('department',e.target.value)}><option value="">{L('Σύνολο νοσοκομείου','Hospital total')}</option>{departments.map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label={L('Αντιμικροβιακό','Antimicrobial')} required><select value={form.antibiotic} onChange={e=>chooseDrug(e.target.value)}><option value="">{L('Επιλογή','Select')}</option>{drugs.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></FormField><FormField label="ATC5"><input value={form.atc} onChange={e=>field('atc',e.target.value)}/></FormField><FormField label={L('Οδός χορήγησης','Route')}><select value={form.route} onChange={e=>field('route',e.target.value)}><option value="">—</option>{ROUTES.map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="AWaRe"><select value={form.aware} onChange={e=>field('aware',e.target.value)}><option value="">—</option>{AWARE.map(x=><option key={x}>{x}</option>)}</select></FormField></FormGrid></FormSection>
   <FormSection title={L('Στοιχεία υπολογισμού WHO DDD','WHO DDD calculation data')}><FormGrid columns={4}><FormField label={L('Περιεκτικότητα ανά μονάδα','Strength per unit')} required><input type="number" min="0" step="any" value={form.strength} onChange={e=>field('strength',e.target.value)}/></FormField><FormField label={L('Μονάδα','Unit')}><select value={form.strengthUnit} onChange={e=>field('strengthUnit',e.target.value)}><option>mg</option><option>g</option><option>mcg</option></select></FormField><FormField label={L('Μονάδες ανά συσκευασία','Units per package')} required><input type="number" min="0" step="any" value={form.packSize} onChange={e=>field('packSize',e.target.value)}/></FormField><FormField label={L('Συσκευασίες που καταναλώθηκαν','Packages consumed')} required><input type="number" min="0" step="any" value={form.packages} onChange={e=>field('packages',e.target.value)}/></FormField><FormField label="WHO DDD (g)" required><input type="number" min="0" step="any" value={form.dddGrams} onChange={e=>field('dddGrams',e.target.value)}/></FormField></FormGrid><div className="amc-calculation"><span>{L('Συνολικά γραμμάρια','Total grams')} <strong>{fmt(calc(form).totalGrams,3)} g</strong></span><span>DDD <strong>{fmt(calc(form).ddd,2)}</strong></span></div></FormSection><FormSection title={L('Σημειώσεις','Notes')}><FormField><textarea rows="4" value={form.notes} onChange={e=>field('notes',e.target.value)}/></FormField></FormSection></form>
  </Drawer>
 </PageChrome>
}
