import { formatDate, todayIso } from '../../core/utils/dateTime'
import { confirmAction } from '../../components/core/feedback/index'
import { useEffect, useMemo, useState } from 'react'
import { useAppEvents } from '../../core/events'
import { AlertTriangle, CheckCircle2, ClipboardCheck, Download, FileSearch, Plus, Printer, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import DynamicFormRenderer from '../../components/forms/DynamicFormRenderer'
import {
  BackLink, Badge, Button, DateRangeFilter, Drawer, EntityCell, EntitySummary, FormActions, FormField, FormGrid,
  FormSection, LibraryField, ListWorkspace, PageChrome, PageHeader, StatCard,
} from '../../components/core'
import { downloadCsv, printRows } from '../../core/utils/listExport'
import { buildQuestionValidationSchema, validateValues } from '../../core/forms'
import { normalizeText, selectedRows, sortRows, uniqueSortedValues } from '../../core/utils/entityList'
import { calculateCompliance } from '../../services/formResponsesService'
import { FORM_TEMPLATES_EVENT, loadFormTemplates } from '../../services/formTemplatesService'
import { AUDITS_EVENT, deleteAuditExecution, loadAuditExecutions, upsertAuditExecution } from '../../services/qualityService'
import { createCapaFromSource } from '../../services/qualityWorkflowService'
import './QualityUnified.css'
import { masterNames } from '../../services/masterDataService'

const today = todayIso
const EMPTY=()=>({templateId:'',date:today(),department:'',auditor:'',scope:'',criteria:'',notes:'',status:'Ολοκληρωμένο',source:'',sourceType:''})
const displayDate = formatDate
function deriveFindings(template,answers){return(template?.questions||[]).filter(q=>q.scored&&answers?.[q.id]==='no').map((q,index)=>({id:`F-${Date.now()}-${index}`,questionId:q.id,title:q.label,severity:'Μείζον',status:'Ανοικτό',capaId:''}))}
const exportColumns=[{label:'Ημερομηνία',value:r=>r.date||''},{label:'Audit',value:r=>r.templateName||''},{label:'Τμήμα',value:r=>r.department||''},{label:'Ελεγκτής',value:r=>r.auditor||''},{label:'Συμμόρφωση',value:r=>r.compliance==null?'':`${r.compliance}%`},{label:'Ευρήματα',value:r=>(r.findings||[]).length},{label:'Κατάσταση',value:r=>r.status||''}]

export default function AuditsPage(){
 const navigate=useNavigate();const [searchParams,setSearchParams]=useSearchParams();const [templates,setTemplates]=useState(()=>loadFormTemplates().filter(t=>t.type==='audit'));const [rows,setRows]=useState(loadAuditExecutions);const [search,setSearch]=useState('');const [templateFilter,setTemplateFilter]=useState('');const [department,setDepartment]=useState('');const [findingFilter,setFindingFilter]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [sort,setSort]=useState({key:'date',direction:'desc'});const [selectedKeys,setSelectedKeys]=useState([]);const [drawerOpen,setDrawerOpen]=useState(false);const [editing,setEditing]=useState(null);const [meta,setMeta]=useState(EMPTY);const [answers,setAnswers]=useState({});const [errors,setErrors]=useState({})
 useAppEvents(FORM_TEMPLATES_EVENT, () => setTemplates(loadFormTemplates().filter(t => t.type === 'audit')))
 useAppEvents(AUDITS_EVENT, () => setRows(loadAuditExecutions()))
 useEffect(()=>{const source=searchParams.get('source');if(!source)return;setEditing(null);setMeta({...EMPTY(),source,sourceType:searchParams.get('sourceType')||'Συμβάν',department:searchParams.get('department')||'',scope:searchParams.get('scope')||''});setAnswers({});setErrors({});setDrawerOpen(true);setSearchParams({}, {replace:true})},[searchParams,setSearchParams])
 const selectedTemplate=templates.find(t=>t.id===meta.templateId);const departments=masterNames('departments');const filtered=useMemo(()=>{const q=normalizeText(search);return sortRows(rows.filter(r=>(!templateFilter||r.templateId===templateFilter)&&(!department||r.department===department)&&(!findingFilter||(findingFilter==='with'?(r.findings||[]).length>0:(r.findings||[]).length===0))&&(!from||r.date>=from)&&(!to||r.date<=to)&&(!q||normalizeText([r.id,r.templateName,r.department,r.auditor,r.scope,r.criteria].filter(Boolean).join(' ')).includes(q))),sort)},[rows,search,templateFilter,department,findingFilter,from,to,sort]);const selectedRowsData=useMemo(()=>selectedRows(filtered,selectedKeys),[filtered,selectedKeys]);const allFindings=rows.flatMap(r=>(r.findings||[]).map(f=>({...f,execution:r})));const completed=filtered.filter(r=>r.compliance!=null);const avg=completed.length?Math.round(completed.reduce((s,r)=>s+Number(r.compliance||0),0)/completed.length):0;const openFindings=allFindings.filter(f=>f.status!=='Κλειστό');const metrics={executions:filtered.length,average:avg,findings:openFindings.length,capa:allFindings.filter(f=>f.capaId).length}
 function openNew(templateId=''){setEditing(null);setMeta({...EMPTY(),templateId});setAnswers({});setErrors({});setDrawerOpen(true)}function openRecord(row){setEditing(row);setMeta({...EMPTY(),...row});setAnswers(row.answers||{});setErrors({});setDrawerOpen(true)}function close(){setDrawerOpen(false);setEditing(null);setMeta(EMPTY());setAnswers({});setErrors({})}
 function save(e){e.preventDefault();if(!selectedTemplate||!meta.department||!meta.auditor)return;const nextErrors=validateValues(answers,buildQuestionValidationSchema(selectedTemplate.questions));setErrors(nextErrors);if(Object.keys(nextErrors).length)return;const compliance=calculateCompliance(selectedTemplate,answers);const findings=editing?.findings?.length?editing.findings:deriveFindings(selectedTemplate,answers);upsertAuditExecution({...editing,...meta,templateName:selectedTemplate.name,answers,compliance,findings,status:'Ολοκληρωμένο'});setRows(loadAuditExecutions());close()}
 function remove(){if(!editing||!confirmAction('Να διαγραφεί η εκτέλεση audit;'))return;deleteAuditExecution(editing.id);setRows(loadAuditExecutions());close()}
 function createCapa(finding){if(!editing||finding.capaId)return;const record=createCapaFromSource({sourceId:editing.id,sourceType:'Audit',title:finding.title,department:editing.department,owner:editing.auditor,priority:finding.severity==='Κρίσιμο'?'Υψηλή':'Μέτρια',description:`Εύρημα από ${editing.templateName}`});const updated={...editing,findings:(editing.findings||[]).map(f=>f.id===finding.id?{...f,capaId:record.id}:f)};upsertAuditExecution(updated);setEditing(updated);setRows(loadAuditExecutions())}
 const columns=[{key:'date',label:'Ημερομηνία',width:'125px',sortable:true,render:r=>displayDate(r.date)},{key:'templateName',label:'Audit',sortable:true,render:r=><EntityCell primary={r.templateName||'—'} secondary={r.id||''}/>},{key:'department',label:'Τμήμα',sortable:true},{key:'auditor',label:'Ελεγκτής',sortable:true},{key:'compliance',label:'Συμμόρφωση',width:'155px',sortable:true,render:r=><div className="quality-score-cell"><div className="quality-score-cell__bar"><span style={{width:`${Number(r.compliance||0)}%`}}/></div><strong>{r.compliance==null?'—':`${r.compliance}%`}</strong></div>},{key:'findings',label:'Ευρήματα',width:'105px',render:r=><Badge tone={(r.findings||[]).length?'warning':'success'}>{(r.findings||[]).length}</Badge>},{key:'status',label:'Κατάσταση',width:'140px',render:r=><Badge tone="success">{r.status||'Ολοκληρωμένο'}</Badge>}]
 return <PageChrome className="quality-unified-page" back={<BackLink onClick={()=>navigate('/quality')}>Πίσω στο Quality Hub</BackLink>} header={<PageHeader title="Audit" description="Προγραμματισμός και εκτέλεση εσωτερικών audits με τεκμηριωμένα κριτήρια, ευρήματα και σύνδεση με ενέργειες βελτίωσης." actions={<div className="quality-inline-actions"><Button variant="secondary" icon={<FileSearch size={17}/>} onClick={()=>navigate('/forms/designer')}>Πρότυπα Audit</Button><Button icon={<Plus size={17}/>} onClick={()=>openNew()}>Νέο Audit</Button></div>}/> }>
  <ListWorkspace stats={<EntitySummary columns={4}><StatCard compact icon={ClipboardCheck} label="Εκτελέσεις" value={metrics.executions}/><StatCard compact icon={CheckCircle2} label="Μέση συμμόρφωση" value={`${metrics.average}%`}/><StatCard compact icon={AlertTriangle} label="Ανοικτά ευρήματα" value={metrics.findings} tone={metrics.findings?'warning':'default'}/><StatCard compact icon={CheckCircle2} label="Συνδεδεμένες CAPA" value={metrics.capa}/></EntitySummary>} searchValue={search} onSearchChange={setSearch} searchPlaceholder="Αναζήτηση audit, τμήματος ή ελεγκτή…" activeFilterCount={[search,templateFilter,department,findingFilter,from,to].filter(Boolean).length} onClearFilters={()=>{setSearch('');setTemplateFilter('');setDepartment('');setFindingFilter('');setFrom('');setTo('')}} filters={<><select value={templateFilter} onChange={e=>setTemplateFilter(e.target.value)}><option value="">Όλα τα πρότυπα</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Όλα τα τμήματα</option>{departments.map(x=><option key={x}>{x}</option>)}</select><select value={findingFilter} onChange={e=>setFindingFilter(e.target.value)}><option value="">Όλα τα ευρήματα</option><option value="with">Με ευρήματα</option><option value="without">Χωρίς ευρήματα</option></select><DateRangeFilter from={from} to={to} onFromChange={setFrom} onToChange={setTo}/></>} selectedCount={selectedRowsData.length} selectedLabel="audits" onClearSelection={()=>setSelectedKeys([])} bulkActions={<><Button variant="secondary" size="sm" icon={<Printer size={16}/>} onClick={()=>printRows({title:'Audits',columns:exportColumns,rows:selectedRowsData})}>Εκτύπωση / PDF</Button><Button variant="secondary" size="sm" icon={<Download size={16}/>} onClick={()=>downloadCsv({filename:'audits.csv',columns:exportColumns,rows:selectedRowsData})}>Εξαγωγή CSV</Button></>} columns={columns} rows={filtered} getRowKey={r=>r.id} onRowClick={openRecord} selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys} sort={sort} onSortChange={setSort} ariaLabel="Audits" emptyTitle="Δεν υπάρχουν audits" footer={<span>{filtered.length} εκτελέσεις</span>}/>
  <Drawer open={drawerOpen} onClose={close} title={editing?'Εκτέλεση Audit':'Νέο Audit'} description="Η ροή βασίζεται σε τεκμηριωμένα κριτήρια, αντικειμενικά ευρήματα και παρακολούθηση διορθωτικών ενεργειών." width={1180} position="center" footer={<FormActions form="audit-form" onCancel={close} extraActions={editing?<Button variant="danger" icon={<Trash2 size={16}/>} onClick={remove}>Διαγραφή</Button>:null}/> }>
   <form id="audit-form" className="quality-unified-form" onSubmit={save}><FormSection title="Στοιχεία Audit"><FormGrid columns={2}><FormField label="Πρότυπο" required><select required value={meta.templateId} disabled={Boolean(editing)} onChange={e=>{setMeta(c=>({...c,templateId:e.target.value}));setAnswers({});setErrors({})}}><option value="">Επιλέξτε πρότυπο</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></FormField><FormField label="Ημερομηνία" required><input type="date" required value={meta.date} onChange={e=>setMeta(c=>({...c,date:e.target.value}))}/></FormField><FormField label="Τμήμα" required><LibraryField hideLabel libraryKey="departments" value={meta.department} onChange={v=>setMeta(c=>({...c,department:v}))} placeholder="Επιλέξτε τμήμα"/></FormField><FormField label="Ελεγκτής" required><input required value={meta.auditor} onChange={e=>setMeta(c=>({...c,auditor:e.target.value}))}/></FormField><FormField label="Πεδίο / σκοπός"><input value={meta.scope||''} onChange={e=>setMeta(c=>({...c,scope:e.target.value}))}/></FormField><FormField label="Κριτήρια / πρότυπο αναφοράς"><input value={meta.criteria||''} onChange={e=>setMeta(c=>({...c,criteria:e.target.value}))}/></FormField>{meta.source&&<><FormField label="Πηγή"><input value={`${meta.sourceType||'Πηγή'} · ${meta.source}`} readOnly/></FormField><FormField label="Σύνδεση"><input value="Το Audit θα παραμείνει συνδεδεμένο με την αρχική εγγραφή" readOnly/></FormField></>}</FormGrid></FormSection>
   {selectedTemplate?<FormSection title="Checklist / κριτήρια ελέγχου" description={selectedTemplate.description||''}><DynamicFormRenderer template={selectedTemplate} answers={answers} onChange={setAnswers} errors={errors}/></FormSection>:<FormSection title="Checklist / κριτήρια ελέγχου"><div className="quality-odipy-note">Επιλέξτε πρότυπο Audit. Τα πρότυπα διαχειρίζονται κεντρικά στο Κέντρο Διαχείρισης / Form Designer ώστε να μην υπάρχει δεύτερος audit builder.</div></FormSection>}
   <FormSection title="Σημειώσεις"><FormField label="Γενικές παρατηρήσεις"><textarea rows="4" value={meta.notes||''} onChange={e=>setMeta(c=>({...c,notes:e.target.value}))}/></FormField></FormSection>
   {editing&&<FormSection title={`Ευρήματα (${(editing.findings||[]).length})`} description="Κάθε μη συμμόρφωση μπορεί να συνδεθεί με ξεχωριστή ενέργεια βελτίωσης."><div className="quality-finding-list">{!(editing.findings||[]).length?<div className="quality-odipy-note"><strong>Δεν υπάρχουν μη συμμορφώσεις.</strong> Το audit έχει καταγραφεί χωρίς αυτόματα ευρήματα.</div>:(editing.findings||[]).map(f=><div className="quality-finding-row" key={f.id}><div><strong>{f.title}</strong><div><Badge tone="warning">{f.severity||'Εύρημα'}</Badge></div></div><div>{f.capaId?<Badge tone="success">{f.capaId}</Badge>:<Badge>Χωρίς CAPA</Badge>}</div>{!f.capaId&&<Button variant="secondary" size="sm" onClick={()=>createCapa(f)}>Δημιουργία ενέργειας</Button>}</div>)}</div></FormSection>}
   </form>
  </Drawer>
 </PageChrome>
}