import { APP_ROUTES } from '../../config/routes'
import { formatDate, todayIso } from '../../core/utils/dateTime'
import { notifyAction, promptAction } from '../../components/core/feedback/index'
import { useEffect, useMemo, useState } from 'react'
import { useAppEvents } from '../../core/events'
import { AlertTriangle, CheckCircle2, ClipboardCheck, Download, FileSearch, Plus, Printer, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import DynamicFormRenderer from '../../components/forms/DynamicFormRenderer'
import {
  BackLink, Badge, Button, DateRangeFilter, Drawer, EntityCell, EntitySummary, FormActions, FormField, FormGrid,
  FormSection, LibraryField, ListWorkspace, PageChrome, PageHeader, StatCard,
} from '../../components/core'
import { downloadCsv, printRows } from '../../core/utils/listExport'
import { buildQuestionValidationSchema, validateValues } from '../../core/forms'
import { normalizeText, selectedRows, sortRows, uniqueSortedValues } from '../../core/utils/entityList'
import { calculateCompliance } from '../../services/formResponsesService'
import { FORM_TEMPLATES_EVENT, loadFormTemplates } from '../../services/formTemplatesService'
import { AUDITS_EVENT, loadAuditExecutions } from '../../services/qualityService'
import { deleteQualityAudit, loadQualityAudits, loadQualityCapa, saveQualityAudit, saveQualityCapa } from '../../services/backend/qualityBackendService'
import { createCapaFromSourceAsync } from '../../services/qualityWorkflowService'
import { useI18n } from '../../i18n'
import { qualityDisplayValue } from './qualityPresentation'
import './QualityUnified.css'
import { masterNames } from '../../services/masterDataService'

const today = todayIso
const EMPTY=()=>({templateId:'',date:today(),department:'',auditor:'',scope:'',criteria:'',notes:'',status:'Ολοκληρωμένο',source:'',sourceType:''})
const displayDate = formatDate
function deriveFindings(template,answers){return(template?.questions||[]).filter(q=>q.scored&&answers?.[q.id]==='no').map((q,index)=>({id:`F-${Date.now()}-${index}`,questionId:q.id,title:q.label,severity:'Μείζον',status:'Ανοικτό',capaId:''}))}
const buildExportColumns=(L)=>[{label:L('Ημερομηνία','Date'),value:r=>r.date||''},{label:'Audit',value:r=>r.templateName||''},{label:L('Τμήμα','Department'),value:r=>r.department||''},{label:L('Ελεγκτής','Auditor'),value:r=>r.auditor||''},{label:L('Συμμόρφωση','Compliance'),value:r=>r.compliance==null?'':`${r.compliance}%`},{label:L('Ευρήματα','Findings'),value:r=>(r.findings||[]).length},{label:L('Κατάσταση','Status'),value:r=>r.status||''}]

export default function AuditsPage(){
  const { language }=useI18n()
  const L=(el,en)=>language==='en'?en:el
  const exportColumns=buildExportColumns(L)
 const navigate=useNavigate();const [searchParams,setSearchParams]=useSearchParams();const [templates,setTemplates]=useState(()=>loadFormTemplates().filter(t=>t.type==='audit'));const [rows,setRows]=useState(loadAuditExecutions);const [search,setSearch]=useState('');const [templateFilter,setTemplateFilter]=useState('');const [department,setDepartment]=useState('');const [findingFilter,setFindingFilter]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [sort,setSort]=useState({key:'date',direction:'desc'});const [selectedKeys,setSelectedKeys]=useState([]);const [drawerOpen,setDrawerOpen]=useState(false);const [editing,setEditing]=useState(null);const [meta,setMeta]=useState(EMPTY);const [answers,setAnswers]=useState({});const [errors,setErrors]=useState({})
 useAppEvents(FORM_TEMPLATES_EVENT, () => setTemplates(loadFormTemplates().filter(t => t.type === 'audit')))
 useAppEvents(AUDITS_EVENT, () => setRows(loadAuditExecutions()))
 useEffect(()=>{const source=searchParams.get('source');if(!source)return;setEditing(null);setMeta({...EMPTY(),source,sourceType:searchParams.get('sourceType')||'Συμβάν',department:searchParams.get('department')||'',scope:searchParams.get('scope')||''});setAnswers({});setErrors({});setDrawerOpen(true);setSearchParams({}, {replace:true})},[searchParams,setSearchParams])
 const selectedTemplate=templates.find(t=>t.id===meta.templateId);const departments=masterNames('departments');const filtered=useMemo(()=>{const q=normalizeText(search);return sortRows(rows.filter(r=>(!templateFilter||r.templateId===templateFilter)&&(!department||r.department===department)&&(!findingFilter||(findingFilter==='with'?(r.findings||[]).length>0:(r.findings||[]).length===0))&&(!from||r.date>=from)&&(!to||r.date<=to)&&(!q||normalizeText([r.id,r.templateName,r.department,r.auditor,r.scope,r.criteria].filter(Boolean).join(' ')).includes(q))),sort)},[rows,search,templateFilter,department,findingFilter,from,to,sort]);const selectedRowsData=useMemo(()=>selectedRows(filtered,selectedKeys),[filtered,selectedKeys]);const allFindings=rows.flatMap(r=>(r.findings||[]).map(f=>({...f,execution:r})));const completed=filtered.filter(r=>r.compliance!=null);const avg=completed.length?Math.round(completed.reduce((s,r)=>s+Number(r.compliance||0),0)/completed.length):0;const openFindings=allFindings.filter(f=>f.status!=='Κλειστό');const metrics={executions:filtered.length,average:avg,findings:openFindings.length,capa:allFindings.filter(f=>f.capaId).length}
 function openNew(templateId=''){setEditing(null);setMeta({...EMPTY(),templateId});setAnswers({});setErrors({});setDrawerOpen(true)}function openRecord(row){setEditing(row);setMeta({...EMPTY(),...row});setAnswers(row.answers||{});setErrors({});setDrawerOpen(true)}function close(){setDrawerOpen(false);setEditing(null);setMeta(EMPTY());setAnswers({});setErrors({})}
 async function save(e){e.preventDefault();if(!selectedTemplate||!meta.department||!meta.auditor)return;const nextErrors=validateValues(answers,buildQuestionValidationSchema(selectedTemplate.questions));setErrors(nextErrors);if(Object.keys(nextErrors).length)return;const compliance=calculateCompliance(selectedTemplate,answers);const findings=editing?.findings?.length?editing.findings:deriveFindings(selectedTemplate,answers);await saveQualityAudit({...editing,...meta,templateName:selectedTemplate.name,answers,compliance,findings,status:'Ολοκληρωμένο'});setRows(await loadQualityAudits());close()}
 async function remove(){if(!editing)return;const reason=promptAction(L('Σύντομος λόγος ακύρωσης του Audit:','Short reason for cancelling this Audit:'));if(reason===null)return;if(!String(reason).trim()){notifyAction(L('Χρειάζεται ένας σύντομος λόγος ακύρωσης.','A short cancellation reason is required.'));return}await deleteQualityAudit(editing.id,String(reason).trim());setRows(await loadQualityAudits());close()}
 async function createCapa(finding){if(!editing||finding.capaId)return;const record=await createCapaFromSourceAsync({sourceId:editing.id,sourceType:'Audit',parentId:finding.id,title:finding.title,department:editing.department,owner:editing.auditor,priority:finding.severity==='Κρίσιμο'?'Υψηλή':'Μέτρια',description:`Εύρημα από ${editing.templateName}`});const updated={...editing,findings:(editing.findings||[]).map(f=>f.id===finding.id?{...f,capaId:record.id}:f)};await saveQualityAudit(updated);setEditing(updated);setRows(await loadQualityAudits())}
 async function updateFindingStatus(finding,nextStatus){
   if(!editing)return
   if(nextStatus==='Κλειστό'){
     if(!finding.capaId){notifyAction(L('Για να κλείσει εύρημα χρειάζεται πρώτα συνδεδεμένη CAPA.','A linked CAPA is required before closing a finding.'));return}
     const capa=(await loadQualityCapa()).find(item=>item.id===finding.capaId)
     if(!capa||capa.status!=='Ολοκληρωμένη'||capa.effectivenessStatus!=='Αποτελεσματική'){
       notifyAction(L('Το εύρημα κλείνει μόνο όταν η συνδεδεμένη CAPA έχει ολοκληρωθεί και επαληθευτεί ως αποτελεσματική.','The finding closes only after the linked CAPA is completed and verified as effective.'));return
     }
   }
   const updated={...editing,findings:(editing.findings||[]).map(f=>f.id===finding.id?{...f,status:nextStatus,statusUpdatedAt:new Date().toISOString()}:f)}
   await saveQualityAudit(updated);setEditing(updated);setRows(await loadQualityAudits())
 }
 const columns=[{key:'date',label:L('Ημερομηνία','Date'),width:'125px',sortable:true,render:r=>displayDate(r.date)},{key:'templateName',label:'Audit',sortable:true,render:r=><EntityCell primary={r.templateName||'—'} secondary={r.id||''}/>},{key:'department',label:L('Τμήμα','Department'),sortable:true},{key:'auditor',label:L('Ελεγκτής','Auditor'),sortable:true},{key:'compliance',label:L('Συμμόρφωση','Compliance'),width:'155px',sortable:true,render:r=><div className="quality-score-cell"><div className="quality-score-cell__bar"><span style={{width:`${Number(r.compliance||0)}%`}}/></div><strong>{r.compliance==null?'—':`${r.compliance}%`}</strong></div>},{key:'findings',label:L('Ευρήματα','Findings'),width:'105px',render:r=><Badge tone={(r.findings||[]).length?'warning':'success'}>{(r.findings||[]).length}</Badge>},{key:'status',label:L('Κατάσταση','Status'),width:'140px',render:r=><Badge tone="success">{qualityDisplayValue(r.status||'Ολοκληρωμένο',language)}</Badge>}]
 return <PageChrome className="quality-unified-page" back={<BackLink onClick={()=>navigate(APP_ROUTES.QUALITY)}>{L('Πίσω στο Quality Hub','Back to Quality Hub')}</BackLink>} header={<PageHeader title="Audit" description={L('Προγραμματισμός και εκτέλεση εσωτερικών audits με τεκμηριωμένα κριτήρια, ευρήματα και σύνδεση με ενέργειες βελτίωσης.','Plan and execute internal audits with documented criteria, findings and linked improvement actions.')} actions={<div className="quality-inline-actions"><Button variant="secondary" icon={<FileSearch size={17}/>} onClick={()=>navigate(APP_ROUTES.FORM_DESIGNER)}>{L('Πρότυπα Audit','Audit templates')}</Button><Button icon={<Plus size={17}/>} onClick={()=>openNew()}>{L('Νέο Audit','New Audit')}</Button></div>}/> }>
  <ListWorkspace stats={<EntitySummary columns={4}><StatCard compact icon={ClipboardCheck} label={L('Εκτελέσεις','Executions')} value={metrics.executions}/><StatCard compact icon={CheckCircle2} label={L('Μέση συμμόρφωση','Average compliance')} value={`${metrics.average}%`}/><StatCard compact icon={AlertTriangle} label={L('Ανοικτά ευρήματα','Open findings')} value={metrics.findings} tone={metrics.findings?'warning':'default'}/><StatCard compact icon={CheckCircle2} label={L('Συνδεδεμένες CAPA','Linked CAPA')} value={metrics.capa}/></EntitySummary>} searchValue={search} onSearchChange={setSearch} searchPlaceholder={L('Αναζήτηση audit, τμήματος ή ελεγκτή…','Search audit, department or auditor…')} activeFilterCount={[search,templateFilter,department,findingFilter,from,to].filter(Boolean).length} onClearFilters={()=>{setSearch('');setTemplateFilter('');setDepartment('');setFindingFilter('');setFrom('');setTo('')}} filters={<><select value={templateFilter} onChange={e=>setTemplateFilter(e.target.value)}><option value="">{L('Όλα τα πρότυπα','All templates')}</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">{L('Όλα τα τμήματα','All departments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</select><select value={findingFilter} onChange={e=>setFindingFilter(e.target.value)}><option value="">{L('Όλα τα ευρήματα','All findings')}</option><option value="with">{L("Με ευρήματα","With findings")}</option><option value="without">{L("Χωρίς ευρήματα","Without findings")}</option></select><DateRangeFilter from={from} to={to} onFromChange={setFrom} onToChange={setTo}/></>} selectedCount={selectedRowsData.length} selectedLabel="audits" onClearSelection={()=>setSelectedKeys([])} bulkActions={<><Button variant="secondary" size="sm" icon={<Printer size={16}/>} onClick={()=>printRows({title:'Audits',columns:exportColumns,rows:selectedRowsData})}>{L('Εκτύπωση / PDF','Print / PDF')}</Button><Button variant="secondary" size="sm" icon={<Download size={16}/>} onClick={()=>downloadCsv({filename:'audits.csv',columns:exportColumns,rows:selectedRowsData})}>{L('Εξαγωγή CSV','Export CSV')}</Button></>} columns={columns} rows={filtered} getRowKey={r=>r.id} onRowClick={openRecord} selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys} sort={sort} onSortChange={setSort} ariaLabel="Audits" emptyTitle={L('Δεν υπάρχουν audits','No audits')} footer={<span>{filtered.length} {L('εκτελέσεις','executions')}</span>}/>
  <Drawer open={drawerOpen} onClose={close} title={editing?L('Εκτέλεση Audit','Audit execution'):L('Νέο Audit','New Audit')} description={L('Η ροή βασίζεται σε τεκμηριωμένα κριτήρια, αντικειμενικά ευρήματα και παρακολούθηση διορθωτικών ενεργειών.','The workflow is based on documented criteria, objective findings and corrective-action follow-up.')} width={1180} position="center" footer={<FormActions form="audit-form" onCancel={close} disabled={Boolean(editing?.finalizedAt||editing?.archivedAt)} primaryLabel={editing?.archivedAt?L('Ακυρωμένο','Cancelled'):editing?.finalizedAt?L('Οριστικοποιημένο','Finalized'):undefined} extraActions={editing&&!editing.archivedAt?<Button variant="danger" icon={<Trash2 size={16}/>} onClick={remove}>{L('Ακύρωση εγγραφής','Cancel record')}</Button>:null}/> }>
   <form id="audit-form" className="quality-unified-form" onSubmit={save}><fieldset disabled={Boolean(editing?.finalizedAt||editing?.archivedAt)} className="quality-governance-fieldset"><FormSection title={L('Στοιχεία Audit','Audit details')}><FormGrid columns={2}><FormField label={L('Πρότυπο','Template')} required><select required value={meta.templateId} disabled={Boolean(editing)} onChange={e=>{setMeta(c=>({...c,templateId:e.target.value}));setAnswers({});setErrors({})}}><option value="">{L("Επιλέξτε πρότυπο","Select template")}</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></FormField><FormField label={L('Ημερομηνία','Date')} required><input type="date" required value={meta.date} onChange={e=>setMeta(c=>({...c,date:e.target.value}))}/></FormField><FormField label={L('Τμήμα','Department')} required><LibraryField hideLabel libraryKey="departments" value={meta.department} onChange={v=>setMeta(c=>({...c,department:v}))} placeholder={L('Επιλέξτε τμήμα','Select department')}/></FormField><FormField label={L('Ελεγκτής','Auditor')} required><input required value={meta.auditor} onChange={e=>setMeta(c=>({...c,auditor:e.target.value}))}/></FormField><FormField label={L('Πεδίο / σκοπός','Scope')}><input value={meta.scope||''} onChange={e=>setMeta(c=>({...c,scope:e.target.value}))}/></FormField><FormField label={L('Κριτήρια / πρότυπο αναφοράς','Criteria / reference standard')}><input value={meta.criteria||''} onChange={e=>setMeta(c=>({...c,criteria:e.target.value}))}/></FormField>{meta.source&&<><FormField label={L('Πηγή','Source')}><input value={`${meta.sourceType||'Πηγή'} · ${meta.source}`} readOnly/></FormField><FormField label={L('Σύνδεση','Link')}><input value={L('Το Audit θα παραμείνει συνδεδεμένο με την αρχική εγγραφή','The Audit remains linked to the source record')} readOnly/></FormField></>}</FormGrid></FormSection>
   {selectedTemplate?<FormSection title={L('Checklist / κριτήρια ελέγχου','Checklist / audit criteria')} description={selectedTemplate.description||''}><DynamicFormRenderer template={selectedTemplate} answers={answers} onChange={setAnswers} errors={errors}/></FormSection>:<FormSection title={L('Checklist / κριτήρια ελέγχου','Checklist / audit criteria')}><div className="quality-odipy-note">{L("Επιλέξτε πρότυπο Audit. Τα πρότυπα διαχειρίζονται κεντρικά στο Κέντρο Διαχείρισης / Form Designer ώστε να μην υπάρχει δεύτερος audit builder.","Select an Audit template. Templates are managed centrally in the Management Center / Form Designer so there is no second audit builder.")}</div></FormSection>}
   <FormSection title={L('Σημειώσεις','Notes')}><FormField label={L('Γενικές παρατηρήσεις','General notes')}><textarea rows="4" value={meta.notes||''} onChange={e=>setMeta(c=>({...c,notes:e.target.value}))}/></FormField></FormSection></fieldset>
   {editing?.finalizedAt&&!editing?.archivedAt&&<div className="quality-odipy-note"><strong>{L('Οριστικοποιημένο Audit.','Finalized Audit.')}</strong> {L('Το αρχικό τεκμήριο είναι κλειδωμένο. Μπορείτε ακόμη να συνδέσετε CAPA στα ευρήματα.','The original evidence is locked. You can still link CAPA to findings.')}</div>}
   {editing&&<FormSection title={`${L("Ευρήματα","Findings")} (${(editing.findings||[]).length})`} description={L("Κάθε μη συμμόρφωση μπορεί να συνδεθεί με ξεχωριστή ενέργεια βελτίωσης.","Each non-conformity can be linked to a separate improvement action.")}><div className="quality-finding-list">{!(editing.findings||[]).length?<div className="quality-odipy-note"><strong>{L('Δεν υπάρχουν μη συμμορφώσεις.','No non-conformities.')}</strong> {L('Το audit έχει καταγραφεί χωρίς αυτόματα ευρήματα.','The audit was recorded without automatic findings.')}</div>:(editing.findings||[]).map(f=><div className="quality-finding-row" key={f.id}><div><strong>{f.title}</strong><div className="quality-finding-badges"><Badge tone="warning">{qualityDisplayValue(f.severity,language)||L('Εύρημα','Finding')}</Badge><Badge tone={f.status==='Κλειστό'?'success':f.status==='Σε ενέργεια'?'info':'neutral'}>{qualityDisplayValue(f.status||'Ανοικτό',language)}</Badge></div></div><div>{f.capaId?<Badge tone="success">{f.capaId}</Badge>:<Badge>{L('Χωρίς CAPA','No CAPA')}</Badge>}</div><div className="quality-finding-actions">{!f.capaId&&<Button variant="secondary" size="sm" onClick={()=>createCapa(f)}>{L('Δημιουργία ενέργειας','Create action')}</Button>}{f.status!=='Σε ενέργεια'&&f.status!=='Κλειστό'&&<Button variant="secondary" size="sm" onClick={()=>updateFindingStatus(f,'Σε ενέργεια')}>{L('Σε ενέργεια','In action')}</Button>}{f.status!=='Κλειστό'&&<Button variant="secondary" size="sm" onClick={()=>updateFindingStatus(f,'Κλειστό')}>{L('Κλείσιμο','Close')}</Button>}</div></div>)}</div></FormSection>}
   </form>
  </Drawer>
 </PageChrome>
}