import { APP_ROUTES } from '../../config/routes'
import { formatDate, todayIso } from '../../core/utils/dateTime'
import { confirmAction, notifyAction } from '../../components/core/feedback/index'
import { useMemo, useState, useEffect } from 'react'
import { CheckCircle2, Download, Plus, Printer, RotateCcw, Sparkles, Target, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import {
  BackLink, Badge, Button, DateRangeFilter, Drawer, EntityCell, EntitySummary, FormActions, FormField, FormGrid,
  FormSection, LibraryField, ListWorkspace, PageChrome, PageHeader, StatCard, Timeline,
} from '../../components/core'
import { downloadCsv, printRows } from '../../core/utils/listExport'
import { normalizeText, selectedRows, sortRows, uniqueSortedValues } from '../../core/utils/entityList'
import { loadCapa, loadIncidents } from '../../services/qualityService'
import { loadAuditExecutions } from '../../services/qualityService'
import { deleteQualityCapa, loadQualityAudits, loadQualityCapa, loadQualityIncidents, saveQualityCapa } from '../../services/backend/qualityBackendService'
import { buildQualityTimeline, createCapaFromSource } from '../../services/qualityWorkflowService'
import { useRecordDeepLink } from '../../core/navigation/recordDeepLink'
import { useI18n } from '../../i18n'
import { qualityDisplayValue } from './qualityPresentation'
import './QualityUnified.css'
import { masterNames } from '../../services/masterDataService'

const TYPES=['Διορθωτική','Προληπτική','Βελτίωση διαδικασίας']
const PRIORITIES=['Χαμηλή','Μέτρια','Υψηλή','Κρίσιμη']
const STATUSES=['Ανοικτή','Σε εξέλιξη','Σε επαλήθευση','Ολοκληρωμένη','Ακυρωμένη']
const EFFECTIVENESS=['Εκκρεμεί','Αποτελεσματική','Μερικώς αποτελεσματική','Μη αποτελεσματική']
const EMPTY={title:'',source:'',sourceType:'',parentId:'',actionType:'Διορθωτική',owner:'',department:'',dueDate:'',priority:'Μέτρια',progress:0,status:'Ανοικτή',description:'',rootCause:'',plannedAction:'',evidence:'',effectivenessStatus:'Εκκρεμεί',effectivenessDate:'',effectivenessNotes:''}
const displayDate = formatDate
function statusTone(value){if(value==='Ολοκληρωμένη')return'success';if(value==='Ακυρωμένη')return'neutral';if(value==='Σε επαλήθευση')return'warning';return'info'}
const buildExportColumns=(L)=>[{label:'Κωδικός',value:r=>r.id||''},{label:L('Ενέργεια','Action'),value:r=>r.title||''},{label:'Πηγή',value:r=>r.source||''},{label:L('Τμήμα','Department'),value:r=>r.department||''},{label:L('Υπεύθυνος','Owner'),value:r=>r.owner||''},{label:L('Προθεσμία','Due date'),value:r=>r.dueDate||''},{label:L('Προτεραιότητα','Priority'),value:r=>r.priority||''},{label:L('Κατάσταση','Status'),value:r=>r.status||''},{label:'Αποτελεσματικότητα',value:r=>r.effectivenessStatus||''}]

export default function CapaPage(){
  const { language }=useI18n()
  const L=(el,en)=>language==='en'?en:el
  const exportColumns=buildExportColumns(L)
 const navigate=useNavigate();useEffect(()=>{Promise.all([loadQualityCapa(),loadQualityIncidents(),loadQualityAudits()]).then(([c])=>setRows(c)).catch(()=>{})},[]);const [searchParams,setSearchParams]=useSearchParams();const [rows,setRows]=useState(loadCapa);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [priority,setPriority]=useState('');const [department,setDepartment]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [sort,setSort]=useState({key:'dueDate',direction:'asc'});const [selectedKeys,setSelectedKeys]=useState([]);const [drawerOpen,setDrawerOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(EMPTY)
 const notificationLink=useRecordDeepLink(rows)
 useEffect(()=>{if(searchParams.get('record'))return;const source=searchParams.get('source');if(!source)return;setEditing(null);setForm({...EMPTY,source,sourceType:searchParams.get('sourceType')||'Άλλο',title:searchParams.get('title')||'',department:searchParams.get('department')||'',description:searchParams.get('description')||''});setDrawerOpen(true);setSearchParams({}, {replace:true})},[searchParams,setSearchParams])
 const departments=masterNames('departments');const filtered=useMemo(()=>{const q=normalizeText(search);return sortRows(rows.filter(r=>(!status||r.status===status)&&(!priority||r.priority===priority)&&(!department||r.department===department)&&(!from||r.dueDate>=from)&&(!to||r.dueDate<=to)&&(!q||normalizeText([r.id,r.title,r.source,r.owner,r.department,r.description,r.rootCause].filter(Boolean).join(' ')).includes(q))),sort)},[rows,search,status,priority,department,from,to,sort]);const selectedRowsData=useMemo(()=>selectedRows(filtered,selectedKeys),[filtered,selectedKeys]);const today=new Date().toISOString().slice(0,10);const metrics=useMemo(()=>({open:filtered.filter(r=>!['Ολοκληρωμένη','Ακυρωμένη'].includes(r.status)).length,overdue:filtered.filter(r=>r.dueDate&&r.dueDate<today&&!['Ολοκληρωμένη','Ακυρωμένη'].includes(r.status)).length,verify:filtered.filter(r=>r.status==='Σε επαλήθευση').length,effective:filtered.filter(r=>r.effectivenessStatus==='Αποτελεσματική').length}),[filtered,today])
 function setField(name,value){setForm(c=>({...c,[name]:value}))}function openNew(){setEditing(null);setForm(EMPTY);setDrawerOpen(true)}function openRecord(row){notificationLink.markOpened(row.id);setEditing(row);setForm({...EMPTY,...row,progress:Number(row.progress||0)});setDrawerOpen(true)}function close(){notificationLink.completeReview();setDrawerOpen(false);setEditing(null);setForm(EMPTY)}
 async function save(e){e.preventDefault();let record={...form,progress:Number(form.progress||0),id:editing?.id||`CAPA-${Date.now().toString().slice(-7)}`,updatedAt:new Date().toISOString(),createdAt:editing?.createdAt||new Date().toISOString()};if(record.status==='Ολοκληρωμένη'&&record.effectivenessStatus!=='Αποτελεσματική'){record={...record,status:'Σε επαλήθευση'};notifyAction(L('Η CAPA δεν μπορεί να κλείσει πριν επιβεβαιωθεί ως αποτελεσματική. Μεταφέρθηκε σε «Σε επαλήθευση».','CAPA cannot close before effectiveness is confirmed. It was moved to Verification.'))}if(record.effectivenessStatus==='Αποτελεσματική'&&record.effectivenessDate&&record.progress>=100)record.status='Ολοκληρωμένη';await saveQualityCapa(record);setRows(await loadQualityCapa());close()}
 async function remove(){if(!editing||!confirmAction(L('Να διαγραφεί η ενέργεια βελτίωσης;','Delete this improvement action?')))return;await deleteQualityCapa(editing.id);setRows(await loadQualityCapa());close()}
 async function createFollowUp(){if(!editing)return;const record=await saveQualityCapa({source:editing.source||editing.id,sourceType:editing.sourceType||'CAPA',parentId:editing.id,title:`Επανεξέταση: ${editing.title}`,department:editing.department,owner:editing.owner,priority:editing.priority,description:`Νέα ενέργεια μετά από μη αποτελεσματική CAPA ${editing.id}`,rootCause:editing.rootCause,status:'Ανοικτή',progress:0});setRows(await loadQualityCapa());notifyAction(`${L('Δημιουργήθηκε','Created')} ${record.id}`)}
 function openSource(){if(!editing?.source)return;if(editing.sourceType==='Συμβάν')navigate(`${APP_ROUTES.QUALITY_INCIDENTS}?record=${encodeURIComponent(editing.source)}`);else if(editing.sourceType==='Audit')navigate(APP_ROUTES.QUALITY_AUDITS);else if(editing.sourceType==='Δείκτης')navigate(APP_ROUTES.INDICATORS)}
 const sourceRecord=editing?.sourceType==='Συμβάν'?loadIncidents().find(r=>r.id===editing.source):editing?.sourceType==='Audit'?loadAuditExecutions().find(r=>r.id===editing.source):null
 const related=editing?rows.filter(r=>r.parentId===editing.id||r.id===editing.parentId):[];const timeline=editing?buildQualityTimeline({incident:editing.sourceType==='Συμβάν'?sourceRecord:null,audit:editing.sourceType==='Audit'?sourceRecord:null,capa:editing,relatedCapa:related,language}):[]
 const columns=[{key:'title',label:L('Ενέργεια','Action'),sortable:true,render:r=><EntityCell primary={r.title||'—'} secondary={`${r.id||''}${r.source?` · ${r.sourceType}: ${r.source}`:''}`}/>},{key:'department',label:L('Τμήμα','Department'),sortable:true},{key:'owner',label:L('Υπεύθυνος','Owner'),sortable:true},{key:'dueDate',label:L('Προθεσμία','Due date'),width:'130px',sortable:true,render:r=>displayDate(r.dueDate)},{key:'priority',label:L('Προτεραιότητα','Priority'),width:'120px',sortable:true,render:r=><Badge tone={['Κρίσιμη','Υψηλή'].includes(r.priority)?'danger':r.priority==='Μέτρια'?'warning':'neutral'}>{qualityDisplayValue(r.priority,language)||'—'}</Badge>},{key:'progress',label:L('Πρόοδος','Progress'),width:'150px',sortable:true,render:r=><div className="quality-score-cell"><div className="quality-score-cell__bar"><span style={{width:`${Math.max(0,Math.min(100,Number(r.progress||0)))}%`}}/></div><strong>{Number(r.progress||0)}%</strong></div>},{key:'status',label:L('Κατάσταση','Status'),width:'150px',sortable:true,render:r=><Badge tone={statusTone(r.status)}>{qualityDisplayValue(r.status,language)||'—'}</Badge>}]
 return <PageChrome className="quality-unified-page" back={<BackLink onClick={()=>navigate(APP_ROUTES.QUALITY)}>{L('Πίσω στο Quality Hub','Back to Quality Hub')}</BackLink>} header={<PageHeader title={L('Ενέργειες Βελτίωσης','Improvement Actions')} description={L('Ενιαία CAPA για συμβάντα, audits, δείκτες και άλλες πηγές, με υποχρεωτικό έλεγχο αποτελεσματικότητας πριν το κλείσιμο.','Unified CAPA for incidents, audits, indicators and other sources, with mandatory effectiveness verification before closure.')} actions={<Button icon={<Plus size={17}/>} onClick={openNew}>{L('Νέα CAPA','New CAPA')}</Button>}/> }>
  <ListWorkspace stats={<EntitySummary columns={4}><StatCard compact icon={Sparkles} label={L('Ανοικτές','Open')} value={metrics.open}/><StatCard compact icon={Target} label={L('Εκπρόθεσμες','Overdue')} value={metrics.overdue} tone={metrics.overdue?'warning':'default'}/><StatCard compact icon={CheckCircle2} label={L('Σε επαλήθευση','In verification')} value={metrics.verify}/><StatCard compact icon={CheckCircle2} label={L('Αποτελεσματικές','Effective')} value={metrics.effective} tone="success"/></EntitySummary>} searchValue={search} onSearchChange={setSearch} searchPlaceholder={L('Αναζήτηση CAPA, πηγής ή υπευθύνου…','Search CAPA, source or owner…')} activeFilterCount={[search,status,priority,department,from,to].filter(Boolean).length} onClearFilters={()=>{setSearch('');setStatus('');setPriority('');setDepartment('');setFrom('');setTo('')}} filters={<><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{L('Όλες οι καταστάσεις','All statuses')}</option>{STATUSES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">{L('Όλες οι προτεραιότητες','All priorities')}</option>{PRIORITIES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">{L('Όλα τα τμήματα','All departments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</select><DateRangeFilter label={L('Προθεσμία','Due date')} from={from} to={to} onFromChange={setFrom} onToChange={setTo}/></>} selectedCount={selectedRowsData.length} selectedLabel="CAPA" onClearSelection={()=>setSelectedKeys([])} bulkActions={<><Button variant="secondary" size="sm" icon={<Printer size={16}/>} onClick={()=>printRows({title:'CAPA',columns:exportColumns,rows:selectedRowsData})}>{L('Εκτύπωση / PDF','Print / PDF')}</Button><Button variant="secondary" size="sm" icon={<Download size={16}/>} onClick={()=>downloadCsv({filename:'capa.csv',columns:exportColumns,rows:selectedRowsData})}>{L('Εξαγωγή CSV','Export CSV')}</Button></>} columns={columns} rows={filtered} getRowKey={r=>r.id} onRowClick={openRecord} selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys} sort={sort} onSortChange={setSort} ariaLabel={L('Ενέργειες βελτίωσης','Improvement actions')} emptyTitle={L('Δεν υπάρχουν CAPA','No CAPA records')} highlightedKey={notificationLink.highlightedId} footer={<span>{filtered.length} {L('εγγραφές','records')}</span>}/>
  <Drawer open={drawerOpen} onClose={close} title={editing?L('Επεξεργασία CAPA','Edit CAPA'):L('Νέα CAPA','New CAPA')} description={L('Από την αιτία και το σχέδιο δράσης έως την επαλήθευση της πραγματικής αποτελεσματικότητας.','From root cause and action plan to verification of actual effectiveness.')} width={1140} position="center" footer={<FormActions form="capa-form" onCancel={close} extraActions={editing?<div className="quality-inline-actions">{form.effectivenessStatus==='Μη αποτελεσματική'&&<Button variant="secondary" icon={<RotateCcw size={16}/>} onClick={createFollowUp}>{L('Νέα CAPA','New CAPA')}</Button>}<Button variant="danger" icon={<Trash2 size={16}/>} onClick={remove}>{L('Διαγραφή','Delete')}</Button></div>:null}/> }>
   <form id="capa-form" className="quality-unified-form" onSubmit={save}>
    {editing&&<FormSection title={L('Ροή Ποιότητας','Quality Workflow')} description={L("Πλήρης αλυσίδα από την αρχική πηγή έως την επαλήθευση και το κλείσιμο.","Complete chain from source to verification and closure.")}><Timeline items={timeline} empty={<div className="quality-odipy-note">{L("Δεν υπάρχει ακόμη ιστορικό ροής.","No workflow history yet.")}</div>}/></FormSection>}
    <FormSection title={L('Πηγή και ταξινόμηση','Source and classification')}><FormGrid columns={2}><FormField label={L('Τίτλος','Title')} required><input required value={form.title} onChange={e=>setField('title',e.target.value)}/></FormField><FormField label={L('Τύπος ενέργειας','Action type')}><select value={form.actionType} onChange={e=>setField('actionType',e.target.value)}>{TYPES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField><FormField label={L('Πηγή / κωδικός','Source / code')}><input value={form.source||''} onChange={e=>setField('source',e.target.value)}/></FormField><FormField label={L('Τύπος πηγής','Source type')}><select value={form.sourceType||''} onChange={e=>setField('sourceType',e.target.value)}><option value="">—</option>{['Συμβάν','Audit','Έλεγχος','Δείκτης','Παράπονο','Επιτροπή','Άλλο'].map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField></FormGrid>{editing?.source&&<div className="quality-source-link"><Badge tone="info">{editing.sourceType}</Badge><strong>{editing.source}</strong>{['Συμβάν','Audit','Δείκτης'].includes(editing.sourceType)&&<Button type="button" variant="secondary" size="sm" onClick={openSource}>{L('Προβολή πηγής','View source')}</Button>}</div>}</FormSection>
    <FormSection title={L('Ανάλυση βασικής αιτίας','Root cause analysis')} description={L("Καταγράψτε την αιτία και όχι μόνο το σύμπτωμα του προβλήματος.","Record the cause, not only the symptom of the problem.")}><FormField label={L('Περιγραφή προβλήματος','Problem description')}><textarea rows="4" value={form.description||''} onChange={e=>setField('description',e.target.value)}/></FormField><FormField label={L('Root Cause / βασική αιτία','Root cause')}><textarea rows="4" value={form.rootCause||''} onChange={e=>setField('rootCause',e.target.value)} placeholder={L('Τι επέτρεψε να συμβεί ή να επαναληφθεί;','What allowed this to happen or recur?')}/></FormField><FormField label={L('Σχέδιο δράσης','Action plan')} required><textarea rows="4" required value={form.plannedAction||''} onChange={e=>setField('plannedAction',e.target.value)}/></FormField></FormSection>
    <FormSection title={L('Ανάθεση και παρακολούθηση','Assignment and follow-up')}><FormGrid columns={2}><FormField label={L('Τμήμα','Department')}><LibraryField hideLabel libraryKey="departments" value={form.department||''} onChange={v=>setField('department',v)} placeholder={L('Επιλέξτε τμήμα','Select department')}/></FormField><FormField label={L('Υπεύθυνος','Owner')} required><input required value={form.owner||''} onChange={e=>setField('owner',e.target.value)}/></FormField><FormField label={L('Προθεσμία','Due date')} required><input required type="date" value={form.dueDate||''} onChange={e=>setField('dueDate',e.target.value)}/></FormField><FormField label={L('Προτεραιότητα','Priority')}><select value={form.priority} onChange={e=>setField('priority',e.target.value)}>{PRIORITIES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField><FormField label={L('Πρόοδος %','Progress %')}><input type="number" min="0" max="100" value={form.progress} onChange={e=>setField('progress',e.target.value)}/></FormField><FormField label={L('Κατάσταση','Status')}><select value={form.status} onChange={e=>setField('status',e.target.value)}>{STATUSES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField></FormGrid><FormField label={L('Τεκμήρια υλοποίησης','Implementation evidence')}><textarea rows="3" value={form.evidence||''} onChange={e=>setField('evidence',e.target.value)}/></FormField></FormSection>
    <FormSection title={L('Έλεγχος αποτελεσματικότητας','Effectiveness verification')} description={L("Η CAPA κλείνει μόνο όταν έχει επαληθευτεί ως αποτελεσματική.","CAPA closes only after effectiveness is verified.")}><div className="quality-effectiveness"><FormField label={L('Αποτέλεσμα','Result')}><select value={form.effectivenessStatus} onChange={e=>setField('effectivenessStatus',e.target.value)}>{EFFECTIVENESS.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField><FormField label={L('Ημερομηνία επαλήθευσης','Verification date')}><input type="date" value={form.effectivenessDate||''} onChange={e=>setField('effectivenessDate',e.target.value)}/></FormField><FormField label={L('Παρατηρήσεις','Notes')}><input value={form.effectivenessNotes||''} onChange={e=>setField('effectivenessNotes',e.target.value)}/></FormField></div>{form.effectivenessStatus==='Μη αποτελεσματική'&&<div className="quality-followup-note">{L("Η ενέργεια κρίθηκε μη αποτελεσματική. Δημιουργήστε νέα CAPA ώστε να διατηρηθεί η συνέχεια και το ιστορικό της διερεύνησης.","The action was ineffective. Create a new CAPA to preserve continuity and investigation history.")}</div>}</FormSection>
   </form>
  </Drawer>
 </PageChrome>
}