import { formatDate, todayIso } from '../../core/utils/dateTime'
import { confirmAction, notifyAction } from '../../components/core/feedback/index'
import { useMemo, useState, useEffect } from 'react'
import { CheckCircle2, Download, Plus, Printer, RotateCcw, Sparkles, Target, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import {
  BackLink, Badge, Button, DateRangeFilter, Drawer, EntityCell, EntitySummary, FormActions, FormField, FormGrid,
  FormSection, LibraryField, ListWorkspace, PageChrome, PageHeader, StatCard, Timeline,
} from '../../components/core'
import { downloadCsv, printRows } from '../../core/utils/listExport'
import { normalizeText, selectedRows, sortRows, uniqueSortedValues } from '../../core/utils/entityList'
import { loadCapa, loadIncidents, saveCapa } from '../../services/qualityService'
import { loadAuditExecutions } from '../../services/qualityService'
import { buildQualityTimeline, createCapaFromSource } from '../../services/qualityWorkflowService'
import { useRecordDeepLink } from '../../core/navigation/recordDeepLink'
import './QualityUnified.css'
import { masterNames } from '../../services/masterDataService'

const TYPES=['Διορθωτική','Προληπτική','Βελτίωση διαδικασίας']
const PRIORITIES=['Χαμηλή','Μέτρια','Υψηλή','Κρίσιμη']
const STATUSES=['Ανοικτή','Σε εξέλιξη','Σε επαλήθευση','Ολοκληρωμένη','Ακυρωμένη']
const EFFECTIVENESS=['Εκκρεμεί','Αποτελεσματική','Μερικώς αποτελεσματική','Μη αποτελεσματική']
const EMPTY={title:'',source:'',sourceType:'',parentId:'',actionType:'Διορθωτική',owner:'',department:'',dueDate:'',priority:'Μέτρια',progress:0,status:'Ανοικτή',description:'',rootCause:'',plannedAction:'',evidence:'',effectivenessStatus:'Εκκρεμεί',effectivenessDate:'',effectivenessNotes:''}
const displayDate = formatDate
function statusTone(value){if(value==='Ολοκληρωμένη')return'success';if(value==='Ακυρωμένη')return'neutral';if(value==='Σε επαλήθευση')return'warning';return'info'}
const exportColumns=[{label:'Κωδικός',value:r=>r.id||''},{label:'Ενέργεια',value:r=>r.title||''},{label:'Πηγή',value:r=>r.source||''},{label:'Τμήμα',value:r=>r.department||''},{label:'Υπεύθυνος',value:r=>r.owner||''},{label:'Προθεσμία',value:r=>r.dueDate||''},{label:'Προτεραιότητα',value:r=>r.priority||''},{label:'Κατάσταση',value:r=>r.status||''},{label:'Αποτελεσματικότητα',value:r=>r.effectivenessStatus||''}]

export default function CapaPage(){
 const navigate=useNavigate();const [searchParams,setSearchParams]=useSearchParams();const [rows,setRows]=useState(loadCapa);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [priority,setPriority]=useState('');const [department,setDepartment]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [sort,setSort]=useState({key:'dueDate',direction:'asc'});const [selectedKeys,setSelectedKeys]=useState([]);const [drawerOpen,setDrawerOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(EMPTY)
 const notificationLink=useRecordDeepLink(rows)
 useEffect(()=>{if(searchParams.get('record'))return;const source=searchParams.get('source');if(!source)return;setEditing(null);setForm({...EMPTY,source,sourceType:searchParams.get('sourceType')||'Άλλο',title:searchParams.get('title')||'',department:searchParams.get('department')||'',description:searchParams.get('description')||''});setDrawerOpen(true);setSearchParams({}, {replace:true})},[searchParams,setSearchParams])
 const departments=masterNames('departments');const filtered=useMemo(()=>{const q=normalizeText(search);return sortRows(rows.filter(r=>(!status||r.status===status)&&(!priority||r.priority===priority)&&(!department||r.department===department)&&(!from||r.dueDate>=from)&&(!to||r.dueDate<=to)&&(!q||normalizeText([r.id,r.title,r.source,r.owner,r.department,r.description,r.rootCause].filter(Boolean).join(' ')).includes(q))),sort)},[rows,search,status,priority,department,from,to,sort]);const selectedRowsData=useMemo(()=>selectedRows(filtered,selectedKeys),[filtered,selectedKeys]);const today=new Date().toISOString().slice(0,10);const metrics=useMemo(()=>({open:filtered.filter(r=>!['Ολοκληρωμένη','Ακυρωμένη'].includes(r.status)).length,overdue:filtered.filter(r=>r.dueDate&&r.dueDate<today&&!['Ολοκληρωμένη','Ακυρωμένη'].includes(r.status)).length,verify:filtered.filter(r=>r.status==='Σε επαλήθευση').length,effective:filtered.filter(r=>r.effectivenessStatus==='Αποτελεσματική').length}),[filtered,today])
 function setField(name,value){setForm(c=>({...c,[name]:value}))}function openNew(){setEditing(null);setForm(EMPTY);setDrawerOpen(true)}function openRecord(row){notificationLink.markOpened(row.id);setEditing(row);setForm({...EMPTY,...row,progress:Number(row.progress||0)});setDrawerOpen(true)}function close(){notificationLink.completeReview();setDrawerOpen(false);setEditing(null);setForm(EMPTY)}
 function save(e){e.preventDefault();let record={...form,progress:Number(form.progress||0),id:editing?.id||`CAPA-${Date.now().toString().slice(-7)}`,updatedAt:new Date().toISOString(),createdAt:editing?.createdAt||new Date().toISOString()};if(record.status==='Ολοκληρωμένη'&&record.effectivenessStatus!=='Αποτελεσματική'){record={...record,status:'Σε επαλήθευση'};notifyAction('Η CAPA δεν μπορεί να κλείσει πριν επιβεβαιωθεί ως αποτελεσματική. Μεταφέρθηκε σε «Σε επαλήθευση».')}if(record.effectivenessStatus==='Αποτελεσματική'&&record.effectivenessDate&&record.progress>=100)record.status='Ολοκληρωμένη';const next=editing?rows.map(r=>r.id===editing.id?record:r):[record,...rows];setRows(saveCapa(next));close()}
 function remove(){if(!editing||!confirmAction('Να διαγραφεί η ενέργεια βελτίωσης;'))return;setRows(saveCapa(rows.filter(r=>r.id!==editing.id)));close()}
 function createFollowUp(){if(!editing)return;const record=createCapaFromSource({sourceId:editing.source||editing.id,sourceType:editing.sourceType||'CAPA',parentId:editing.id,title:`Επανεξέταση: ${editing.title}`,department:editing.department,owner:editing.owner,priority:editing.priority,description:`Νέα ενέργεια μετά από μη αποτελεσματική CAPA ${editing.id}`,rootCause:editing.rootCause});setRows(loadCapa());notifyAction(`Δημιουργήθηκε ${record.id}`)}
 function openSource(){if(!editing?.source)return;if(editing.sourceType==='Συμβάν')navigate(`/quality/incidents?record=${encodeURIComponent(editing.source)}`);else if(editing.sourceType==='Audit')navigate('/quality/audits');else if(editing.sourceType==='Δείκτης')navigate('/indicators')}
 const sourceRecord=editing?.sourceType==='Συμβάν'?loadIncidents().find(r=>r.id===editing.source):editing?.sourceType==='Audit'?loadAuditExecutions().find(r=>r.id===editing.source):null
 const related=editing?rows.filter(r=>r.parentId===editing.id||r.id===editing.parentId):[];const timeline=editing?buildQualityTimeline({incident:editing.sourceType==='Συμβάν'?sourceRecord:null,audit:editing.sourceType==='Audit'?sourceRecord:null,capa:editing,relatedCapa:related}):[]
 const columns=[{key:'title',label:'Ενέργεια',sortable:true,render:r=><EntityCell primary={r.title||'—'} secondary={`${r.id||''}${r.source?` · ${r.sourceType}: ${r.source}`:''}`}/>},{key:'department',label:'Τμήμα',sortable:true},{key:'owner',label:'Υπεύθυνος',sortable:true},{key:'dueDate',label:'Προθεσμία',width:'130px',sortable:true,render:r=>displayDate(r.dueDate)},{key:'priority',label:'Προτεραιότητα',width:'120px',sortable:true,render:r=><Badge tone={['Κρίσιμη','Υψηλή'].includes(r.priority)?'danger':r.priority==='Μέτρια'?'warning':'neutral'}>{r.priority||'—'}</Badge>},{key:'progress',label:'Πρόοδος',width:'150px',sortable:true,render:r=><div className="quality-score-cell"><div className="quality-score-cell__bar"><span style={{width:`${Math.max(0,Math.min(100,Number(r.progress||0)))}%`}}/></div><strong>{Number(r.progress||0)}%</strong></div>},{key:'status',label:'Κατάσταση',width:'150px',sortable:true,render:r=><Badge tone={statusTone(r.status)}>{r.status||'—'}</Badge>}]
 return <PageChrome className="quality-unified-page" back={<BackLink onClick={()=>navigate('/quality')}>Πίσω στο Quality Hub</BackLink>} header={<PageHeader title="Ενέργειες Βελτίωσης" description="Ενιαία CAPA για συμβάντα, audits, δείκτες και άλλες πηγές, με υποχρεωτικό έλεγχο αποτελεσματικότητας πριν το κλείσιμο." actions={<Button icon={<Plus size={17}/>} onClick={openNew}>Νέα CAPA</Button>}/> }>
  <ListWorkspace stats={<EntitySummary columns={4}><StatCard compact icon={Sparkles} label="Ανοικτές" value={metrics.open}/><StatCard compact icon={Target} label="Εκπρόθεσμες" value={metrics.overdue} tone={metrics.overdue?'warning':'default'}/><StatCard compact icon={CheckCircle2} label="Σε επαλήθευση" value={metrics.verify}/><StatCard compact icon={CheckCircle2} label="Αποτελεσματικές" value={metrics.effective} tone="success"/></EntitySummary>} searchValue={search} onSearchChange={setSearch} searchPlaceholder="Αναζήτηση CAPA, πηγής ή υπευθύνου…" activeFilterCount={[search,status,priority,department,from,to].filter(Boolean).length} onClearFilters={()=>{setSearch('');setStatus('');setPriority('');setDepartment('');setFrom('');setTo('')}} filters={<><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Όλες οι καταστάσεις</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Όλες οι προτεραιότητες</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Όλα τα τμήματα</option>{departments.map(x=><option key={x}>{x}</option>)}</select><DateRangeFilter label="Προθεσμία" from={from} to={to} onFromChange={setFrom} onToChange={setTo}/></>} selectedCount={selectedRowsData.length} selectedLabel="CAPA" onClearSelection={()=>setSelectedKeys([])} bulkActions={<><Button variant="secondary" size="sm" icon={<Printer size={16}/>} onClick={()=>printRows({title:'CAPA',columns:exportColumns,rows:selectedRowsData})}>Εκτύπωση / PDF</Button><Button variant="secondary" size="sm" icon={<Download size={16}/>} onClick={()=>downloadCsv({filename:'capa.csv',columns:exportColumns,rows:selectedRowsData})}>Εξαγωγή CSV</Button></>} columns={columns} rows={filtered} getRowKey={r=>r.id} onRowClick={openRecord} selectedKeys={selectedKeys} onSelectionChange={setSelectedKeys} sort={sort} onSortChange={setSort} ariaLabel="Ενέργειες βελτίωσης" emptyTitle="Δεν υπάρχουν CAPA" highlightedKey={notificationLink.highlightedId} footer={<span>{filtered.length} εγγραφές</span>}/>
  <Drawer open={drawerOpen} onClose={close} title={editing?'Επεξεργασία CAPA':'Νέα CAPA'} description="Από την αιτία και το σχέδιο δράσης έως την επαλήθευση της πραγματικής αποτελεσματικότητας." width={1140} position="center" footer={<FormActions form="capa-form" onCancel={close} extraActions={editing?<div className="quality-inline-actions">{form.effectivenessStatus==='Μη αποτελεσματική'&&<Button variant="secondary" icon={<RotateCcw size={16}/>} onClick={createFollowUp}>Νέα CAPA</Button>}<Button variant="danger" icon={<Trash2 size={16}/>} onClick={remove}>Διαγραφή</Button></div>:null}/> }>
   <form id="capa-form" className="quality-unified-form" onSubmit={save}>
    {editing&&<FormSection title="Ροή Ποιότητας" description="Πλήρης αλυσίδα από την αρχική πηγή έως την επαλήθευση και το κλείσιμο."><Timeline items={timeline} empty={<div className="quality-odipy-note">Δεν υπάρχει ακόμη ιστορικό ροής.</div>}/></FormSection>}
    <FormSection title="Πηγή και ταξινόμηση"><FormGrid columns={2}><FormField label="Τίτλος" required><input required value={form.title} onChange={e=>setField('title',e.target.value)}/></FormField><FormField label="Τύπος ενέργειας"><select value={form.actionType} onChange={e=>setField('actionType',e.target.value)}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Πηγή / κωδικός"><input value={form.source||''} onChange={e=>setField('source',e.target.value)}/></FormField><FormField label="Τύπος πηγής"><select value={form.sourceType||''} onChange={e=>setField('sourceType',e.target.value)}><option value="">—</option><option>Συμβάν</option><option>Audit</option><option>Έλεγχος</option><option>Δείκτης</option><option>Παράπονο</option><option>Επιτροπή</option><option>Άλλο</option></select></FormField></FormGrid>{editing?.source&&<div className="quality-source-link"><Badge tone="info">{editing.sourceType}</Badge><strong>{editing.source}</strong>{['Συμβάν','Audit','Δείκτης'].includes(editing.sourceType)&&<Button type="button" variant="secondary" size="sm" onClick={openSource}>Προβολή πηγής</Button>}</div>}</FormSection>
    <FormSection title="Ανάλυση βασικής αιτίας" description="Καταγράψτε την αιτία και όχι μόνο το σύμπτωμα του προβλήματος."><FormField label="Περιγραφή προβλήματος"><textarea rows="4" value={form.description||''} onChange={e=>setField('description',e.target.value)}/></FormField><FormField label="Root Cause / βασική αιτία"><textarea rows="4" value={form.rootCause||''} onChange={e=>setField('rootCause',e.target.value)} placeholder="Τι επέτρεψε να συμβεί ή να επαναληφθεί;"/></FormField><FormField label="Σχέδιο δράσης" required><textarea rows="4" required value={form.plannedAction||''} onChange={e=>setField('plannedAction',e.target.value)}/></FormField></FormSection>
    <FormSection title="Ανάθεση και παρακολούθηση"><FormGrid columns={2}><FormField label="Τμήμα"><LibraryField hideLabel libraryKey="departments" value={form.department||''} onChange={v=>setField('department',v)} placeholder="Επιλέξτε τμήμα"/></FormField><FormField label="Υπεύθυνος" required><input required value={form.owner||''} onChange={e=>setField('owner',e.target.value)}/></FormField><FormField label="Προθεσμία" required><input required type="date" value={form.dueDate||''} onChange={e=>setField('dueDate',e.target.value)}/></FormField><FormField label="Προτεραιότητα"><select value={form.priority} onChange={e=>setField('priority',e.target.value)}>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Πρόοδος %"><input type="number" min="0" max="100" value={form.progress} onChange={e=>setField('progress',e.target.value)}/></FormField><FormField label="Κατάσταση"><select value={form.status} onChange={e=>setField('status',e.target.value)}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></FormField></FormGrid><FormField label="Τεκμήρια υλοποίησης"><textarea rows="3" value={form.evidence||''} onChange={e=>setField('evidence',e.target.value)}/></FormField></FormSection>
    <FormSection title="Έλεγχος αποτελεσματικότητας" description="Η CAPA κλείνει μόνο όταν έχει επαληθευτεί ως αποτελεσματική."><div className="quality-effectiveness"><FormField label="Αποτέλεσμα"><select value={form.effectivenessStatus} onChange={e=>setField('effectivenessStatus',e.target.value)}>{EFFECTIVENESS.map(x=><option key={x}>{x}</option>)}</select></FormField><FormField label="Ημερομηνία επαλήθευσης"><input type="date" value={form.effectivenessDate||''} onChange={e=>setField('effectivenessDate',e.target.value)}/></FormField><FormField label="Παρατηρήσεις"><input value={form.effectivenessNotes||''} onChange={e=>setField('effectivenessNotes',e.target.value)}/></FormField></div>{form.effectivenessStatus==='Μη αποτελεσματική'&&<div className="quality-followup-note">Η ενέργεια κρίθηκε μη αποτελεσματική. Δημιουργήστε νέα CAPA ώστε να διατηρηθεί η συνέχεια και το ιστορικό της διερεύνησης.</div>}</FormSection>
   </form>
  </Drawer>
 </PageChrome>
}