import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Plus, ShieldCheck, Target, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { APP_ROUTES } from '../../config/routes'
import { BackLink, Badge, Button, Drawer, EntityCell, EntitySummary, FormActions, FormField, FormGrid, FormSection, LibraryField, ListWorkspace, PageChrome, PageHeader, StatCard } from '../../components/core'
import { notifyAction, promptAction } from '../../components/core/feedback/index'
import { normalizeText, sortRows } from '../../core/utils/entityList'
import { loadRisks } from '../../services/qualityService'
import { archiveQualityRisk, loadQualityRisks, saveQualityRisk } from '../../services/backend/qualityBackendService'
import { createCapaFromSourceAsync } from '../../services/qualityWorkflowService'
import { masterNames } from '../../services/masterDataService'
import { useI18n } from '../../i18n'
import { qualityDisplayValue } from './qualityPresentation'
import './QualityUnified.css'

const CATEGORIES=['Κλινικός','Λοίμωξη / IPC','Φάρμακα','Εργαστήριο','Προσωπικό','Εξοπλισμός','Υποδομές','Πληροφορίες / δεδομένα','Άλλο']
const STATUSES=['Ανοικτός','Υπό έλεγχο','Αποδεκτός','Κλειστός','Ακυρωμένος']
const EMPTY={title:'',category:'Κλινικός',description:'',department:'',likelihood:2,severity:2,controls:'',actions:'',owner:'',reviewDate:'',status:'Ανοικτός',residualLikelihood:2,residualSeverity:2}
const level=score=>score>=16?'Κρίσιμος':score>=10?'Υψηλός':score>=5?'Μέτριος':'Χαμηλός'
const tone=score=>score>=16?'danger':score>=10?'warning':score>=5?'info':'success'

export default function RisksPage(){
  const {language}=useI18n(); const L=(el,en)=>language==='en'?en:el; const navigate=useNavigate(); const [params,setParams]=useSearchParams()
  const [rows,setRows]=useState(loadRisks); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [department,setDepartment]=useState(''); const [sort,setSort]=useState({key:'riskScore',direction:'desc'}); const [drawerOpen,setDrawerOpen]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(EMPTY)
  useEffect(()=>{loadQualityRisks().then(setRows).catch(()=>{})},[])
  useEffect(()=>{const id=params.get('record');if(!id)return;const row=rows.find(x=>x.id===id);if(row){setEditing(row);setForm({...EMPTY,...row});setDrawerOpen(true)}setParams({}, {replace:true})},[params,rows,setParams])
  const departments=masterNames('departments')
  const filtered=useMemo(()=>{const q=normalizeText(search);return sortRows(rows.filter(r=>(!status||r.status===status)&&(!department||r.department===department)&&(!q||normalizeText([r.id,r.title,r.category,r.department,r.owner,r.description].join(' ')).includes(q))),sort)},[rows,search,status,department,sort])
  const metrics=useMemo(()=>({open:filtered.filter(r=>!['Κλειστός','Ακυρωμένος'].includes(r.status)).length,high:filtered.filter(r=>Number(r.riskScore)>=10&&!['Κλειστός','Ακυρωμένος'].includes(r.status)).length,critical:filtered.filter(r=>Number(r.riskScore)>=16&&!['Κλειστός','Ακυρωμένος'].includes(r.status)).length,due:filtered.filter(r=>r.reviewDate&&r.reviewDate<new Date().toISOString().slice(0,10)&&!['Κλειστός','Ακυρωμένος'].includes(r.status)).length}),[filtered])
  const score=Math.max(1,Math.min(5,Number(form.likelihood||1)))*Math.max(1,Math.min(5,Number(form.severity||1)))
  const residualScore=Math.max(1,Math.min(5,Number(form.residualLikelihood||1)))*Math.max(1,Math.min(5,Number(form.residualSeverity||1)))
  const setField=(name,value)=>setForm(c=>({...c,[name]:value})); const openNew=()=>{setEditing(null);setForm(EMPTY);setDrawerOpen(true)}; const openRecord=row=>{setEditing(row);setForm({...EMPTY,...row});setDrawerOpen(true)}; const close=()=>{setDrawerOpen(false);setEditing(null);setForm(EMPTY)}
  async function save(e){e.preventDefault();await saveQualityRisk({...form,id:editing?.id||undefined,riskScore:score,residualScore,createdAt:editing?.createdAt});setRows(await loadQualityRisks());close()}
  async function archive(){if(!editing)return;const reason=promptAction(L('Σύντομος λόγος ακύρωσης του κινδύνου:','Short reason for cancelling this risk:'));if(reason===null)return;if(!String(reason).trim()){notifyAction(L('Χρειάζεται ένας σύντομος λόγος.','A short reason is required.'));return}await archiveQualityRisk(editing.id,String(reason).trim());setRows(await loadQualityRisks());close()}
  async function createCapa(){if(!editing)return;await createCapaFromSourceAsync({sourceId:editing.id,sourceType:'Κίνδυνος',title:`Μείωση κινδύνου: ${editing.title}`,department:editing.department,owner:editing.owner||'Ομάδα Ποιότητας',priority:Number(editing.riskScore)>=16?'Κρίσιμη':Number(editing.riskScore)>=10?'Υψηλή':'Μέτρια',description:editing.description,rootCause:'',});notifyAction(L('Δημιουργήθηκε CAPA για τον κίνδυνο.','A CAPA was created for this risk.'))}
  const columns=[{key:'title',label:L('Κίνδυνος','Risk'),sortable:true,render:r=><EntityCell primary={r.title||'—'} secondary={`${r.id||''} · ${qualityDisplayValue(r.category,language)||r.category}`}/>},{key:'department',label:L('Τμήμα','Department'),sortable:true},{key:'riskScore',label:L('Αρχικό ρίσκο','Initial risk'),width:'130px',sortable:true,render:r=><Badge tone={tone(Number(r.riskScore))}>{Number(r.riskScore)} · {qualityDisplayValue(level(Number(r.riskScore)),language)}</Badge>},{key:'residualScore',label:L('Υπολειπόμενο','Residual'),width:'130px',sortable:true,render:r=><Badge tone={tone(Number(r.residualScore))}>{Number(r.residualScore)} · {qualityDisplayValue(level(Number(r.residualScore)),language)}</Badge>},{key:'owner',label:L('Υπεύθυνος','Owner'),sortable:true},{key:'reviewDate',label:L('Επανέλεγχος','Review'),sortable:true},{key:'status',label:L('Κατάσταση','Status'),width:'130px',render:r=><Badge tone={r.status==='Κλειστός'?'success':r.status==='Ακυρωμένος'?'neutral':'info'}>{qualityDisplayValue(r.status,language)}</Badge>}]
  return <PageChrome className="quality-unified-page" back={<BackLink onClick={()=>navigate(APP_ROUTES.QUALITY)}>{L('Πίσω στο Quality Hub','Back to Quality Hub')}</BackLink>} header={<PageHeader title={L('Μητρώο Κινδύνων','Risk Register')} description={L('Απλή καταγραφή και προτεραιοποίηση κινδύνων με αυτόματο risk score.','Simple risk recording and prioritization with automatic risk scoring.')} actions={<Button icon={<Plus size={17}/>} onClick={openNew}>{L('Νέος κίνδυνος','New risk')}</Button>}/> }>
    <ListWorkspace stats={<EntitySummary columns={4}><StatCard compact icon={ShieldCheck} label={L('Ανοικτοί','Open')} value={metrics.open}/><StatCard compact icon={Target} label={L('Υψηλοί','High')} value={metrics.high} tone={metrics.high?'warning':'default'}/><StatCard compact icon={AlertTriangle} label={L('Κρίσιμοι','Critical')} value={metrics.critical} tone={metrics.critical?'warning':'default'}/><StatCard compact icon={AlertTriangle} label={L('Εκπρόθεσμοι έλεγχοι','Overdue reviews')} value={metrics.due} tone={metrics.due?'warning':'default'}/></EntitySummary>} searchValue={search} onSearchChange={setSearch} searchPlaceholder={L('Αναζήτηση κινδύνου, τμήματος ή υπευθύνου…','Search risk, department or owner…')} activeFilterCount={[search,status,department].filter(Boolean).length} onClearFilters={()=>{setSearch('');setStatus('');setDepartment('')}} filters={<><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{L('Όλες οι καταστάσεις','All statuses')}</option>{STATUSES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">{L('Όλα τα τμήματα','All departments')}</option>{departments.map(x=><option key={x}>{x}</option>)}</select></>} columns={columns} rows={filtered} getRowKey={r=>r.id} onRowClick={openRecord} sort={sort} onSortChange={setSort} ariaLabel={L('Μητρώο κινδύνων','Risk register')} emptyTitle={L('Δεν υπάρχουν κίνδυνοι','No risks')} footer={<span>{filtered.length} {L('εγγραφές','records')}</span>}/>
    <Drawer open={drawerOpen} onClose={close} title={editing?L('Κίνδυνος','Risk'):L('Νέος κίνδυνος','New risk')} description={L('Συμπληρώστε μόνο τα βασικά. Η βαθμολογία υπολογίζεται αυτόματα.','Enter only the essentials. Scoring is automatic.')} width={980} position="center" footer={<FormActions form="risk-form" onCancel={close} disabled={Boolean(editing?.archivedAt)} extraActions={editing&&!editing.archivedAt?<div className="quality-inline-actions"><Button variant="secondary" onClick={createCapa}>{L('Δημιουργία CAPA','Create CAPA')}</Button><Button variant="danger" icon={<Trash2 size={16}/>} onClick={archive}>{L('Ακύρωση','Cancel')}</Button></div>:null}/> }>
      <form id="risk-form" className="quality-unified-form" onSubmit={save}><fieldset disabled={Boolean(editing?.archivedAt)} className="quality-governance-fieldset">
        <FormSection title={L('Ο κίνδυνος','The risk')}><FormGrid columns={2}><FormField label={L('Τίτλος','Title')} required><input required value={form.title} onChange={e=>setField('title',e.target.value)}/></FormField><FormField label={L('Κατηγορία','Category')}><select value={form.category} onChange={e=>setField('category',e.target.value)}>{CATEGORIES.map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField><FormField label={L('Τμήμα','Department')}><LibraryField hideLabel libraryKey="departments" value={form.department} onChange={v=>setField('department',v)} placeholder={L('Επιλέξτε τμήμα','Select department')}/></FormField><FormField label={L('Υπεύθυνος','Owner')}><input value={form.owner} onChange={e=>setField('owner',e.target.value)}/></FormField></FormGrid><FormField label={L('Τι μπορεί να συμβεί;','What could happen?')}><textarea rows="3" value={form.description} onChange={e=>setField('description',e.target.value)}/></FormField></FormSection>
        <FormSection title={L('Αξιολόγηση','Assessment')} description={L('1 = χαμηλό, 5 = πολύ υψηλό.','1 = low, 5 = very high.')}><FormGrid columns={3}><FormField label={L('Πιθανότητα','Likelihood')}><input type="number" min="1" max="5" value={form.likelihood} onChange={e=>setField('likelihood',e.target.value)}/></FormField><FormField label={L('Σοβαρότητα','Severity')}><input type="number" min="1" max="5" value={form.severity} onChange={e=>setField('severity',e.target.value)}/></FormField><FormField label={L('Risk score','Risk score')}><div className="quality-risk-score"><Badge tone={tone(score)}>{score} · {qualityDisplayValue(level(score),language)}</Badge></div></FormField></FormGrid></FormSection>
        <FormSection title={L('Μέτρα και παρακολούθηση','Controls and follow-up')}><FormField label={L('Υπάρχοντα μέτρα','Existing controls')}><textarea rows="3" value={form.controls} onChange={e=>setField('controls',e.target.value)}/></FormField><FormField label={L('Τι άλλο πρέπει να γίνει;','What else needs to be done?')}><textarea rows="3" value={form.actions} onChange={e=>setField('actions',e.target.value)}/></FormField><FormGrid columns={2}><FormField label={L('Ημερομηνία επανελέγχου','Review date')}><input type="date" value={form.reviewDate} onChange={e=>setField('reviewDate',e.target.value)}/></FormField><FormField label={L('Κατάσταση','Status')}><select value={form.status} onChange={e=>setField('status',e.target.value)}>{STATUSES.filter(x=>x!=='Ακυρωμένος').map(x=><option key={x} value={x}>{qualityDisplayValue(x,language)}</option>)}</select></FormField></FormGrid><div className="quality-risk-transition"><div className="quality-risk-transition__stage"><strong>{L('Αρχικός κίνδυνος','Initial risk')}</strong><div className="quality-risk-score"><Badge tone={tone(score)}>{score} · {qualityDisplayValue(level(score),language)}</Badge></div></div><div className="quality-risk-transition__arrow">→</div><div className="quality-risk-transition__stage"><strong>{L('Μετά τα μέτρα ελέγχου','After controls')}</strong><div className="quality-risk-score"><Badge tone={tone(residualScore)}>{residualScore} · {qualityDisplayValue(level(residualScore),language)}</Badge></div></div></div><FormGrid columns={2}><FormField label={L('Υπολειπόμενη πιθανότητα','Residual likelihood')}><input type="number" min="1" max="5" value={form.residualLikelihood} onChange={e=>setField('residualLikelihood',e.target.value)}/></FormField><FormField label={L('Υπολειπόμενη σοβαρότητα','Residual severity')}><input type="number" min="1" max="5" value={form.residualSeverity} onChange={e=>setField('residualSeverity',e.target.value)}/></FormField></FormGrid></FormSection>
      </fieldset></form>
    </Drawer>
  </PageChrome>
}
