export const masterDataSections = [
{
    id: 'departments',
    label: 'Τμήματα',
    icon: '🏥',
    description: 'Τμήματα, μονάδες και χώροι του νοσοκομείου.',
    columns: ['name', 'code', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'code', label: 'Κωδικός' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'dep-1', name: 'ΜΕΘ', code: 'ICU', status: 'Ενεργό' },
      { id: 'dep-2', name: 'Χειρουργείο', code: 'OR', status: 'Ενεργό' },
      { id: 'dep-3', name: 'Παθολογική', code: 'PATH', status: 'Ενεργό' },
      { id: 'dep-4', name: 'Αποστείρωση', code: 'CSSD', status: 'Ενεργό' },
      { id: 'dep-5', name: 'Αιμοκάθαρση', code: 'HD', status: 'Ενεργό' },
    ],
  },
{
    id: 'microorganisms',
    label: 'Μικροοργανισμοί',
    icon: '🦠',
    description: 'Κεντρικό λεξικό μικροοργανισμών και χαρακτηριστικών.',
    columns: ['name', 'group', 'resistance', 'status'],
    fields: [
      { id: 'name', label: 'Επιστημονική ονομασία', required: true },
      {
        id: 'group',
        label: 'Ομάδα',
        type: 'select',
        options: ['Βακτήριο', 'Ιός', 'Μύκητας', 'Παράσιτο'],
      },
      {
        id: 'gram',
        label: 'Gram',
        type: 'select',
        options: ['', 'Θετικό', 'Αρνητικό', 'Δεν εφαρμόζεται'],
      },
      {
        id: 'resistance',
        label: 'Χαρακτηρισμός',
        type: 'select',
        options: ['', 'MDR', 'XDR', 'PDR', 'MRSA', 'VRE', 'CRE', 'ESBL'],
      },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      {
        id: 'mic-1',
        name: 'Klebsiella pneumoniae',
        group: 'Βακτήριο',
        gram: 'Αρνητικό',
        resistance: 'CRE',
        status: 'Ενεργό',
      },
      {
        id: 'mic-2',
        name: 'Escherichia coli',
        group: 'Βακτήριο',
        gram: 'Αρνητικό',
        resistance: 'ESBL',
        status: 'Ενεργό',
      },
      {
        id: 'mic-3',
        name: 'Staphylococcus aureus',
        group: 'Βακτήριο',
        gram: 'Θετικό',
        resistance: 'MRSA',
        status: 'Ενεργό',
      },
      {
        id: 'mic-4',
        name: 'Acinetobacter baumannii',
        group: 'Βακτήριο',
        gram: 'Αρνητικό',
        resistance: 'MDR',
        status: 'Ενεργό',
      },
      {
        id: 'mic-5',
        name: 'Candida auris',
        group: 'Μύκητας',
        gram: 'Δεν εφαρμόζεται',
        resistance: 'MDR',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'antibiotics',
    label: 'Αντιβιοτικά / Φάρμακα',
    icon: '💊',
    description: 'Αντιμικροβιακά φάρμακα, ομάδες και κωδικοί.',
    columns: ['name', 'category', 'atc', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'category', label: 'Κατηγορία' },
      { id: 'atc', label: 'ATC5 κωδικός' },
      { id: 'dddRoute', label: 'Οδός WHO DDD', type: 'select', options: ['PO','IV','IM','PR','Inhaled','Other'] },
      { id: 'dddGrams', label: 'WHO DDD (g)', type: 'number' },
      { id: 'aware', label: 'WHO AWaRe', type: 'select', options: ['Access','Watch','Reserve','Not classified'] },
      { id: 'restricted', label: 'Προωθημένο / περιορισμένης χρήσης', type: 'checkbox' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      {
        id: 'ab-1',
        name: 'Meropenem',
        category: 'Carbapenems',
        atc: 'J01DH02',
        restricted: true,
        status: 'Ενεργό',
      },
      {
        id: 'ab-2',
        name: 'Vancomycin',
        category: 'Glycopeptides',
        atc: 'J01XA01',
        status: 'Ενεργό',
      },
      {
        id: 'ab-3',
        name: 'Colistin',
        category: 'Polymyxins',
        atc: 'J01XB01',
        restricted: true,
        status: 'Ενεργό',
      },
      {
        id: 'ab-4',
        name: 'Linezolid',
        category: 'Oxazolidinones',
        atc: 'J01XX08',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'sample-types',
    label: 'Είδη Δειγμάτων',
    icon: '🧫',
    description: 'Κλινικά, περιβαλλοντικά και εργαστηριακά δείγματα.',
    columns: ['name', 'category', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      {
        id: 'category',
        label: 'Κατηγορία',
        type: 'select',
        options: ['Ασθενής', 'Προσωπικό', 'Περιβάλλον', 'Νερό'],
      },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'sam-1', name: 'Αίμα', category: 'Ασθενής', status: 'Ενεργό' },
      { id: 'sam-2', name: 'Ούρα', category: 'Ασθενής', status: 'Ενεργό' },
      { id: 'sam-3', name: 'Πτύελα', category: 'Ασθενής', status: 'Ενεργό' },
      { id: 'sam-4', name: 'BAL', category: 'Ασθενής', status: 'Ενεργό' },
      {
        id: 'sam-5',
        name: 'Επίχρισμα επιφάνειας',
        category: 'Περιβάλλον',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'body-sites',
    label: 'Θέσεις Σώματος',
    icon: '🩺',
    description: 'Ανατομικές θέσεις και συστήματα.',
    columns: ['name', 'code', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'code', label: 'Κωδικός' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'bs-1', name: 'Αναπνευστικό', code: 'RESP', status: 'Ενεργό' },
      { id: 'bs-2', name: 'Ουροποιητικό', code: 'URIN', status: 'Ενεργό' },
      { id: 'bs-3', name: 'Αίμα', code: 'BLOOD', status: 'Ενεργό' },
      { id: 'bs-4', name: 'Δέρμα', code: 'SKIN', status: 'Ενεργό' },
    ],
  },
{
    id: 'infection-types',
    label: 'Τύποι Λοιμώξεων',
    icon: '🚑',
    description: 'Κατηγορίες λοιμώξεων και κωδικοί επιτήρησης.',
    columns: ['name', 'code', 'category', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'code', label: 'Κωδικός' },
      { id: 'category', label: 'Κατηγορία' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      {
        id: 'inf-1',
        name: 'Λοίμωξη ουροποιητικού σχετιζόμενη με καθετήρα',
        code: 'CAUTI',
        category: 'HAI',
        status: 'Ενεργό',
      },
      {
        id: 'inf-2',
        name: 'Λοίμωξη αιματικής ροής σχετιζόμενη με κεντρική γραμμή',
        code: 'CLABSI',
        category: 'HAI',
        status: 'Ενεργό',
      },
      {
        id: 'inf-3',
        name: 'Πνευμονία σχετιζόμενη με αναπνευστήρα',
        code: 'VAP',
        category: 'HAI',
        status: 'Ενεργό',
      },
      {
        id: 'inf-4',
        name: 'Λοίμωξη χειρουργικού πεδίου',
        code: 'SSI',
        category: 'HAI',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'isolation-types',
    label: 'Τύποι Απομόνωσης',
    icon: '🛏',
    description: 'Μέτρα απομόνωσης και προφυλάξεων.',
    columns: ['name', 'code', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'code', label: 'Κωδικός' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'iso-1', name: 'Επαφής', code: 'CONTACT', status: 'Ενεργό' },
      { id: 'iso-2', name: 'Σταγονιδίων', code: 'DROPLET', status: 'Ενεργό' },
      { id: 'iso-3', name: 'Αερογενής', code: 'AIRBORNE', status: 'Ενεργό' },
      {
        id: 'iso-4',
        name: 'Προστατευτική',
        code: 'PROTECTIVE',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'devices',
    label: 'Υλικά / Συσκευές',
    icon: '🧴',
    description: 'Καθετήρες, συσκευές και ιατροτεχνολογικός εξοπλισμός.',
    columns: ['name', 'category', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'category', label: 'Κατηγορία' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      {
        id: 'dev-1',
        name: 'Κεντρικός φλεβικός καθετήρας',
        category: 'Καθετήρας',
        status: 'Ενεργό',
      },
      {
        id: 'dev-2',
        name: 'Ουροκαθετήρας',
        category: 'Καθετήρας',
        status: 'Ενεργό',
      },
      {
        id: 'dev-3',
        name: 'Αναπνευστήρας',
        category: 'Αναπνευστική υποστήριξη',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'environment-points',
    label: 'Περιβαλλοντικά Σημεία',
    icon: '🧹',
    description: 'Σημεία δειγματοληψίας χώρων και επιφανειών.',
    columns: ['name', 'category', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'category', label: 'Κατηγορία' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'env-1', name: 'Νιπτήρας', category: 'Υγρή επιφάνεια', status: 'Ενεργό' },
      { id: 'env-2', name: 'Πόμολο', category: 'Συχνή επαφή', status: 'Ενεργό' },
      {
        id: 'env-3',
        name: 'Κάγκελο κλίνης',
        category: 'Συχνή επαφή',
        status: 'Ενεργό',
      },
      {
        id: 'env-4',
        name: 'Πληκτρολόγιο',
        category: 'Εξοπλισμός',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'water-points',
    label: 'Σημεία Νερού',
    icon: '💧',
    description: 'Σημεία δειγματοληψίας δικτύου και ειδικών εγκαταστάσεων.',
    columns: ['name', 'category', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'category', label: 'Κατηγορία' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'wat-1', name: 'Βρύση', category: 'Δίκτυο', status: 'Ενεργό' },
      { id: 'wat-2', name: 'Ντους', category: 'Δίκτυο', status: 'Ενεργό' },
      {
        id: 'wat-3',
        name: 'Αντίστροφη όσμωση',
        category: 'Αιμοκάθαρση',
        status: 'Ενεργό',
      },
      { id: 'wat-4', name: 'Δεξαμενή', category: 'Αποθήκευση', status: 'Ενεργό' },
    ],
  },
{
    id: 'professional-categories',
    label: 'Επαγγελματικές Κατηγορίες',
    icon: '👨‍⚕️',
    description: 'Κατηγορίες επαγγελματιών για WHO και λοιπούς ελέγχους.',
    columns: ['name', 'code', 'status'],
    fields: [
      { id: 'name', label: 'Ονομασία', required: true },
      { id: 'code', label: 'Κωδικός' },
      {
        id: 'status',
        label: 'Κατάσταση',
        type: 'select',
        options: ['Ενεργό', 'Ανενεργό'],
      },
    ],
    initialItems: [
      { id: 'pro-1', name: 'Ιατρός', code: 'DR', status: 'Ενεργό' },
      {
        id: 'pro-2',
        name: 'Νοσηλευτής / Νοσηλεύτρια',
        code: 'NURSE',
        status: 'Ενεργό',
      },
      {
        id: 'pro-3',
        name: 'Βοηθός Νοσηλευτή',
        code: 'NA',
        status: 'Ενεργό',
      },
      {
        id: 'pro-4',
        name: 'Βοηθητικό προσωπικό',
        code: 'AUX',
        status: 'Ενεργό',
      },
    ],
  },
{
    id: 'surveillance-reasons',
    label: 'Λόγοι Επιτήρησης',
    icon: '🩺',
    description: 'Κεντρικές επιλογές για έναρξη επιτήρησης ασθενούς.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'symptoms',
    label: 'Συμπτώματα',
    icon: '🌡️',
    description: 'Συμπτώματα για την κλινική αξιολόγηση ασθενών.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'risk-factors',
    label: 'Παράγοντες Κινδύνου',
    icon: '⚠️',
    description: 'Παράγοντες κινδύνου για την κλινική αξιολόγηση.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'infection-sites',
    label: 'Εστίες / Τύποι Λοίμωξης',
    icon: '🫁',
    description: 'Εστίες λοίμωξης που χρησιμοποιούνται στην επιτήρηση.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'sample-categories',
    label: 'Κατηγορίες Δειγμάτων',
    icon: '🧪',
    description: 'Αρχικό, screening, φορεία και επανέλεγχος.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'sample-repeat-purposes',
    label: 'Λόγοι Επανελέγχου',
    icon: '🔁',
    description: 'Αρνητικοποίηση, επιμονή, υποτροπή, επαναλοίμωξη και θεραπεία.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'notifiable-diseases',
    label: 'Δηλούμενα Νοσήματα',
    icon: '📄',
    description: 'Κεντρική βιβλιοθήκη νοσημάτων και χρόνου υποχρεωτικής δήλωσης.',
    columns: ['name', 'deadline', 'status'],
    fields: [{ id: 'name', label: 'Νόσημα', required: true }, { id: 'deadline', label: 'Χρόνος δήλωσης', type: 'select', options: ['Αμέσως','24ωρο','Εβδομάδα'] }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [],
  },
{
    id: 'antiseptic-products',
    label: 'Προϊόντα Αντισηπτικών',
    icon: '🧴',
    description: 'Αλκοολούχα αντισηπτικά και συσκευασίες για παρακολούθηση κατανάλωσης.',
    columns: ['name', 'volumeMl', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'volumeMl', label: 'Συσκευασία (ml)' }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [{ id: 'ant-prod-1', name: 'Αλκοολούχο αντισηπτικό χεριών', volumeMl: '500', status: 'Ενεργό' }],
  },
{
    id: 'waste-types',
    label: 'Κατηγορίες Αποβλήτων',
    icon: '♻️',
    description: 'Κατηγορίες υγειονομικών αποβλήτων για τις μετρήσεις.',
    columns: ['name', 'code', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'code', label: 'Κωδικός' }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [{ id: 'waste-1', name: 'Μολυσματικά απόβλητα', code: 'EAYM', status: 'Ενεργό' }, { id: 'waste-2', name: 'Αιχμηρά', code: 'SHARPS', status: 'Ενεργό' }, { id: 'waste-3', name: 'Φαρμακευτικά', code: 'PHARMA', status: 'Ενεργό' }, { id: 'waste-4', name: 'Αστικού τύπου', code: 'MSW', status: 'Ενεργό' }],
  },
{
    id: 'audit-types',
    label: 'Τύποι Ελέγχων Πρόληψης',
    icon: '✅',
    description: 'Πρότυπα audits και checklists.',
    columns: ['name', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [{ id: 'audit-1', name: 'Υγιεινή χεριών', status: 'Ενεργό' }, { id: 'audit-2', name: 'Χρήση ΜΑΠ', status: 'Ενεργό' }, { id: 'audit-3', name: 'Καθαριότητα περιβάλλοντος', status: 'Ενεργό' }],
  },
{
    id: 'bundle-types',
    label: 'Τύποι Bundles',
    icon: '📦',
    description: 'Bundles πρόληψης λοιμώξεων.',
    columns: ['name', 'code', 'status'],
    fields: [{ id: 'name', label: 'Ονομασία', required: true }, { id: 'code', label: 'Κωδικός' }, { id: 'status', label: 'Κατάσταση', type: 'select', options: ['Ενεργό', 'Ανενεργό'] }],
    initialItems: [{ id: 'bundle-1', name: 'CLABSI Bundle', code: 'CLABSI', status: 'Ενεργό' }, { id: 'bundle-2', name: 'CAUTI Bundle', code: 'CAUTI', status: 'Ενεργό' }, { id: 'bundle-3', name: 'VAP Bundle', code: 'VAP', status: 'Ενεργό' }, { id: 'bundle-4', name: 'SSI Bundle', code: 'SSI', status: 'Ενεργό' }],
  }
]
