export const APP_ROUTES = Object.freeze({
  ROOT: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CORE: '/core',
  PATIENTS: '/patients',
  EMPLOYEES: '/employees',
  LABORATORY: '/laboratory',
  SURVEILLANCE: '/surveillance',
  INDICATORS: '/indicators',
  QUALITY: '/quality',
  PREVENTION: '/prevention',
  ORGANIZATION: '/organization',
  TRAINING: '/training',
  COMMITTEES: '/committees',
  DOCUMENTS: '/documents',
  REPORTS: '/reports',
  LIRA: '/lira',
  SETTINGS: '/settings',
  NOTIFIABLE_DISEASES: '/records/notifiable-diseases',
  VACCINATIONS: '/prevention/vaccinations',
  PROMOTED_ANTIBIOTICS: '/prevention/promoted-antibiotics',
  HAND_HYGIENE: '/prevention/hand-hygiene',
  ANTISEPTIC_CONSUMPTION: '/prevention/antiseptic-consumption',
  WASTE: '/prevention/waste',
  PREVENTION_AUDITS: '/prevention/audits',
  BUNDLES: '/prevention/bundles',
  INFECTIONS: '/surveillance/infections',
  ISOLATIONS: '/surveillance/isolations',
  PATIENT_SAMPLES: '/surveillance/patient-samples',
  QUALITY_INCIDENTS: '/quality/incidents',
  QUALITY_AUDITS: '/quality/audits',
  QUALITY_CAPA: '/quality/capa',
  QUALITY_INDICATORS: '/quality/indicators',
  STUDIO_DEVELOPER: '/studio/developer',
  STUDIO_INDICATORS: '/studio/indicators',
  STUDIO_WORKFLOWS: '/studio/workflows',
  STUDIO_RULES: '/studio/rules',
  STUDIO_NOTIFICATIONS: '/studio/notifications',
  STUDIO_DASHBOARDS: '/studio/dashboards',
  STUDIO_AI: '/studio/ai',
  STUDIO_SECURITY: '/studio/security',
  STUDIO_USERS: '/studio/users',
  STUDIO_ROLES: '/studio/roles',
  STUDIO_SETTINGS: '/studio/settings',
  STUDIO: '/studio',
  FORM_DESIGNER: '/forms/designer',
  PATIENT_WORKFLOW: '/patients/:patientId/workflow',
  EMPLOYEE_WORKSPACE: '/employees/:employeeId/workspace',
  LABORATORY_NEW_WORKSPACE: '/laboratory/new/workspace',
  LABORATORY_RECORD_WORKSPACE: '/laboratory/:sourceType/:recordId/workspace',
  LABORATORY_VIEW: '/laboratory/:view',
  SURVEILLANCE_PATIENTS: '/surveillance/patients',
  SURVEILLANCE_STAFF_SAMPLES: '/surveillance/staff-samples',
  SURVEILLANCE_ENVIRONMENT: '/surveillance/environment',
  WATER: '/water',
})

export const routeFor = Object.freeze({
  patientWorkflow: (patientId) => `${APP_ROUTES.PATIENTS}/${patientId}/workflow`,
  employeeWorkspace: (employeeId) => `${APP_ROUTES.EMPLOYEES}/${employeeId}/workspace`,
  laboratoryView: (view) => `${APP_ROUTES.LABORATORY}/${view}`,
  laboratoryNewWorkspace: () => APP_ROUTES.LABORATORY_NEW_WORKSPACE,
  laboratoryRecordWorkspace: (sourceType, recordId) => `${APP_ROUTES.LABORATORY}/${sourceType}/${recordId}/workspace`,
})
