import { useEffect,useMemo,useState } from 'react'
import { useAppEvents } from '../../core/events'
import { useNavigate } from 'react-router-dom'
import { ArrowRight,CalendarClock,FileWarning,FolderOpen,GraduationCap,Plus,UsersRound,UserRoundCog } from 'lucide-react'
import { loadEmployees,EMPLOYEES_EVENT } from '../../services/employeesService'
import { loadCommittees,loadDocuments,loadTraining,ORGANIZATION_EVENT } from '../../services/organizationService'
import StatCard from '../../components/core/StatCard/StatCard'
import './OrganizationPages.css'
export default function OrganizationCenterPage(){
 const navigate=useNavigate();const[v,setV]=useState(0);useAppEvents([ORGANIZATION_EVENT,EMPLOYEES_EVENT],()=>setV(x=>x+1),{includeStorage:true})
 const data=useMemo(()=>({employees:loadEmployees(),training:loadTraining(),committees:loadCommittees(),documents:loadDocuments()}),[v]);const today=new Date().toISOString().slice(0,10);const soon=new Date(Date.now()+30*864e5).toISOString().slice(0,10)
 const active=data.employees.filter(x=>x.status!=='Ανενεργό').length,vaccinations=data.employees.reduce((n,x)=>n+(x.vaccinations||[]).length,0),occupationalDue=data.employees.reduce((n,x)=>n+(x.occupationalVisits||[]).filter(v=>v.nextVisit&&v.nextVisit<=soon).length,0),upcoming=data.training.filter(x=>x.status!=='Ολοκληρωμένη'&&x.date>=today).length,meetings=data.committees.filter(x=>x.nextMeeting>=today&&x.nextMeeting<=soon).length,reviews=data.documents.filter(x=>x.reviewDate&&x.reviewDate<=soon&&x.status!=='Καταργημένο').length
 const activity=[...data.training.map(x=>({date:x.date,title:x.title,meta:`Εκπαίδευση · ${x.department||'Όλα τα τμήματα'}`})),...data.committees.map(x=>({date:x.nextMeeting,title:x.name,meta:'Επόμενη συνεδρίαση'})),...data.documents.map(x=>({date:x.updatedAt,title:x.title,meta:`Έγγραφο · ${x.code}`}))].filter(x=>x.date).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,7)
 return <section className="organization-page"><header className="organization-hero"><div><div className="organization-hero__eyebrow">Οργάνωση</div><h1>Επισκόπηση Οργάνωσης</h1><p>Ενιαία εικόνα προσωπικού, εκπαιδεύσεων, επιτροπών και ελεγχόμενων εγγράφων.</p></div><button type="button" className="organization-button" onClick={()=>navigate('/training')}><Plus size={18}/> Νέα εκπαίδευση</button></header>
 <div className="organization-kpis"><StatCard icon={UserRoundCog} label="Ενεργοί εργαζόμενοι" value={active} subtitle={`${vaccinations} εμβολιασμοί · ${occupationalDue} επανέλεγχοι`} tone="success"/><StatCard icon={GraduationCap} label="Προσεχείς εκπαιδεύσεις" value={upcoming} subtitle="Προγραμματισμένες δράσεις"/><StatCard icon={UsersRound} label="Συνεδριάσεις 30 ημερών" value={meetings} subtitle="Ενεργές επιτροπές και ομάδες"/><StatCard icon={FileWarning} label="Έγγραφα προς αναθεώρηση" value={reviews} subtitle="Εντός των επόμενων 30 ημερών" tone={reviews ? "warning" : "default"}/></div>
 <div className="organization-grid"><article className="organization-card"><div className="organization-card__head"><div><h2>Γρήγορες ενέργειες</h2><span>Κεντρική πρόσβαση στις λειτουργίες οργάνωσης</span></div></div><div className="organization-actions"><Action icon={<UserRoundCog/>} title="Εργαζόμενοι" text="Καρτέλες και στοιχεία προσωπικού" onClick={()=>navigate('/employees')}/><Action icon={<GraduationCap/>} title="Εκπαίδευση" text="Προγράμματα, συμμετοχές και ισχύς" onClick={()=>navigate('/training')}/><Action icon={<UsersRound/>} title="Επιτροπές" text="Μέλη, συνεδριάσεις και αποφάσεις" onClick={()=>navigate('/committees')}/><Action icon={<FolderOpen/>} title="Έγγραφα" text="Εκδόσεις, ιδιοκτήτες και αναθεωρήσεις" onClick={()=>navigate('/documents')}/></div></article>
 <article className="organization-card"><div className="organization-card__head"><div><h2>Τι χρειάζεται προσοχή</h2><span>Αυτόματη οργανωτική σύνοψη</span></div><CalendarClock size={21}/></div><div className="organization-list"><Summary title={`${reviews} έγγραφα προς αναθεώρηση`} text="Ελέγξτε ιδιοκτήτη, έκδοση και ημερομηνία ισχύος." tone={reviews?'warning':'success'}/><Summary title={`${meetings} συνεδριάσεις εντός 30 ημερών`} text="Προετοιμασία ημερήσιας διάταξης και προσκλήσεων." tone="success"/><Summary title={`${upcoming} προγραμματισμένες εκπαιδεύσεις`} text="Έλεγχος παρουσιολογίου, συμμετεχόντων και εκπαιδευτικού υλικού." tone="success"/><Summary title={`${occupationalDue} επανέλεγχοι ιατρού εργασίας`} text="Επόμενες επισκέψεις που έχουν προγραμματιστεί εντός της περιόδου." tone={occupationalDue?'warning':'success'}/></div></article></div>
 <article className="organization-card"><div className="organization-card__head"><h2>Πρόσφατη και προσεχής δραστηριότητα</h2><button type="button" className="organization-button organization-button--ghost" onClick={()=>navigate('/documents')}>Όλες οι ενότητες <ArrowRight size={16}/></button></div><div className="organization-list">{activity.map((x,i)=><div className="organization-list-item" key={`${x.title}-${i}`}><div><strong>{x.title}</strong><small>{x.meta}</small></div><span className="organization-pill">{x.date}</span></div>)}</div></article></section>
}
function Action({icon,title,text,onClick}){return <button type="button" className="organization-action" onClick={onClick}><span className="organization-action__icon">{icon}</span><span><strong>{title}</strong><small>{text}</small></span></button>}
function Summary({title,text,tone}){return <div className="organization-list-item"><div><strong>{title}</strong><small>{text}</small></div><span className={`organization-pill organization-pill--${tone}`}>Έλεγχος</span></div>}
