import { Activity, CheckCircle2, ClipboardList, FlaskConical, LogIn, LogOut, Pill, RefreshCcw, ShieldAlert } from 'lucide-react'
import { eventDateTimeKey, getDeviceRecords, getTherapies, isRepeatSample, sampleMicroorganismLabel, sampleResistanceLabel } from './patientWorkflowUtils'
import { patientDisplayValue } from './patientPresentation'

export function buildPatientTimeline({ patient, cases, samples, isolations, notifiableDiseases = [], language = 'el' }) {
  const L = (el, en) => language === 'en' ? en : el
  const items = []
  if (patient.admissionDate) items.push({ type: 'admission', id: patient.id, clickable: false, date: patient.admissionDate, time: patient.admissionTime || '', title: L('Εισαγωγή ασθενούς', 'Patient admission'), description: [patient.room, patient.primaryDiagnosis].filter(Boolean).join(' · ') || L('Έναρξη νοσηλείας', 'Start of hospital stay'), icon: <LogIn size={15} /> })
  cases.forEach((item) => {
    if (item.startDate) items.push({ type: 'case', id: item.id, date: item.startDate, time: item.startTime || '', title: L('Έναρξη επιτήρησης', 'Surveillance started'), description: patientDisplayValue(item.reason, language) || L('Χωρίς καταχωρημένη αιτία', 'No reason recorded'), clinicalCaseId: item.id, targetTab: 'assessment', recordType: 'case', recordId: item.id, icon: <ClipboardList size={15} />, badge: patientDisplayValue(item.status || 'Ενεργό', language), badgeTone: item.status === 'Κλειστό' ? 'success' : 'warning' })
    getTherapies(item).forEach((therapy) => {
      if (therapy.startDate) items.push({ type: 'therapy', id: therapy.id, date: therapy.startDate, time: therapy.startTime || '', title: `Έναρξη ${therapy.antibiotic || 'αντιμικροβιακής αγωγής'}`, clinicalCaseId: item.id, targetTab: 'care', recordType: 'therapy', recordId: therapy.id, description: [therapy.dosage, therapy.frequency, therapy.route].filter(Boolean).join(' · '), icon: <Pill size={15} />, tone: 'warning' })
      if (therapy.endDate) items.push({ type: 'therapy-end', id: therapy.id, date: therapy.endDate, time: therapy.endTime || '', title: `Λήξη ${therapy.antibiotic || 'αντιμικροβιακής αγωγής'}`, clinicalCaseId: item.id, targetTab: 'care', recordType: 'therapy', recordId: therapy.id, description: therapy.indication || 'Ολοκλήρωση αγωγής', icon: <CheckCircle2 size={15} />, tone: 'success' })
    })
    getDeviceRecords(item).forEach((device) => {
      if (device.startDate) items.push({ type: 'device', id: device.id, date: device.startDate, title: `${L('Έναρξη συσκευής', 'Device started')} · ${patientDisplayValue(device.type, language)}`, clinicalCaseId: item.id, targetTab: 'assessment', recordType: 'device', recordId: device.id, description: device.related && device.related !== 'Όχι' ? `${L('Συσχέτιση με λοίμωξη', 'Association with infection')}: ${patientDisplayValue(device.related, language)}` : 'Χωρίς τεκμηριωμένη συσχέτιση', icon: <Activity size={15} /> })
      if (device.endDate) items.push({ type: 'device-end', id: device.id, date: device.endDate, title: `${L('Αφαίρεση συσκευής', 'Device removed')} · ${patientDisplayValue(device.type, language)}`, clinicalCaseId: item.id, targetTab: 'assessment', recordType: 'device', recordId: device.id, description: device.notes || 'Ολοκλήρωση χρήσης', icon: <CheckCircle2 size={15} />, tone: 'success' })
    })
    if (item.review?.date) items.push({ type: 'review', id: item.id, date: item.review.date, title: L('Επανεκτίμηση', 'Reassessment'), clinicalCaseId: item.id, targetTab: 'care', recordType: 'review', recordId: item.id, description: item.review.outcome || item.review.notes || L('Κλινική επανεκτίμηση', 'Clinical reassessment'), icon: <RefreshCcw size={15} /> })
    if (item.close?.date) items.push({ type: 'case-close', id: item.id, date: item.close.date, title: L('Κλείσιμο επιτήρησης', 'Surveillance closed'), clinicalCaseId: item.id, targetTab: 'assessment', recordType: 'case', recordId: item.id, description: item.close.result || L('Ολοκλήρωση περιστατικού', 'Episode completed'), icon: <CheckCircle2 size={15} />, tone: 'success' })
  })
  samples.forEach((item) => items.push({ type: 'sample', id: item.id, date: item.collectionDate, time: item.collectionTime || '', clinicalCaseId: item.clinicalCaseId, targetTab: 'samples', recordType: 'sample', recordId: item.id, title: `${patientDisplayValue(isRepeatSample(item) ? (item.repeatPurpose || 'Επανέλεγχος') : (item.category || 'Δείγμα'), language)} · ${patientDisplayValue(item.sampleType, language) || L('Άγνωστος τύπος', 'Unknown type')}`, description: sampleMicroorganismLabel(item) ? `${sampleMicroorganismLabel(item)}${sampleResistanceLabel(item) ? ` · ${sampleResistanceLabel(item)}` : ''}` : L('Αναμονή μικροβιολογικού αποτελέσματος', 'Awaiting microbiology result'), icon: <FlaskConical size={15} />, badge: patientDisplayValue(item.status || 'Εκκρεμεί', language), badgeTone: item.status === 'Θετικό' ? 'danger' : item.status === 'Αρνητικό' ? 'success' : 'neutral', tone: item.status === 'Θετικό' ? 'danger' : '' }))
  isolations.forEach((item) => {
    if (item.startDate) items.push({ type: 'isolation', id: item.id, date: item.startDate, time: item.startTime || '', clinicalCaseId: item.clinicalCaseId, targetTab: 'care', recordType: 'isolation', recordId: item.id, title: L('Έναρξη απομόνωσης', 'Isolation started'), description: `${patientDisplayValue(item.isolationType || 'Απομόνωση', language)}${item.pathogen ? ` · ${item.pathogen}` : ''}`, icon: <ShieldAlert size={15} />, badge: patientDisplayValue(item.status || 'Ενεργή', language), badgeTone: item.status === 'Ενεργή' ? 'danger' : 'neutral', tone: 'danger' })
    if (item.endDate) items.push({ type: 'isolation-end', id: item.id, date: item.endDate, time: item.endTime || '', clinicalCaseId: item.clinicalCaseId, targetTab: 'care', recordType: 'isolation', recordId: item.id, title: L('Λήξη απομόνωσης', 'Isolation ended'), description: item.pathogen || item.isolationType || 'Ολοκλήρωση μέτρων απομόνωσης', icon: <CheckCircle2 size={15} />, tone: 'success' })
  })
  notifiableDiseases.forEach((item) => { const eventDate = item.declarationDate || item.diagnosisDate; if (eventDate) items.push({ type: 'notifiable', id: item.id, recordType: 'notifiable', recordId: item.id, date: eventDate, title: L('Δηλούμενο νόσημα', 'Notifiable disease'), description: `${item.disease || 'Νόσημα'} · ${item.status || 'Πρόχειρο'}`, icon: <ShieldAlert size={15} />, badge: item.deadline || '', badgeTone: item.status === 'Δηλώθηκε' ? 'success' : 'warning', tone: item.status === 'Δηλώθηκε' ? 'success' : 'warning' }) })
  const dischargeDate = patient.dischargeDate || (patient.status === 'Εξιτήριο' ? patient.exitDate : '')
  if (dischargeDate) items.push({ type: 'discharge', id: patient.id, clickable: false, date: dischargeDate, time: patient.dischargeTime || '', title: L('Έξοδος ασθενούς', 'Patient discharge'), description: patient.dischargeOutcome || L('Εξιτήριο', 'Discharged'), icon: <LogOut size={15} />, tone: 'success' })
  return items.filter((item) => item.date).sort((a, b) => eventDateTimeKey(a).localeCompare(eventDateTimeKey(b)))
}


