const EN = {
  'Επιτροπή': 'Committee',
  'Ομάδα εργασίας': 'Working group',
  'Συμβούλιο': 'Council',
  'Ενεργή': 'Active',
  'Ανενεργή': 'Inactive',
  'Αίμα': 'Blood',
  'Ούρα': 'Urine',
  'Πτύελα': 'Sputum',
  'Ρινικό επίχρισμα': 'Nasal swab',
  'Φαρυγγικό επίχρισμα': 'Throat swab',
  'Ορθικό επίχρισμα': 'Rectal swab',
  'Άκρο καθετήρα': 'Catheter tip',
  'ΕΝΥ': 'CSF',
  'Κόπρανα': 'Stool',
  'Ενεργό': 'Active',
  'Ανενεργό': 'Inactive',
  'Εκκρεμεί': 'Pending',
  'Πρόσκληση': 'Invited',
  'Ενεργός': 'Active',
  'Ανενεργός': 'Disabled',
  'Θετικό': 'Positive',
  'Αρνητικό': 'Negative',
  'Εκκρεμές': 'Pending',
  'Άνδρας': 'Male',
  'Γυναίκα': 'Female',
  'Άλλο / μη δηλωμένο': 'Other / not specified',
  'Γρίπη': 'Influenza',
  'Ηπατίτιδα Β': 'Hepatitis B',
  'Ανεμευλογιά': 'Varicella',
  'Τέτανος / Διφθερίτιδα': 'Tetanus / Diphtheria',
  'Κλινική εκπαίδευση': 'Clinical training',
  'Ποιότητα': 'Quality',
  'Εισαγωγική': 'Induction',
  'Υποχρεωτική': 'Mandatory',
  'Σε εξέλιξη': 'In progress',
  'Ολοκληρωμένη': 'Completed',
  'Ακυρωμένη': 'Cancelled',
  'Παρών': 'Present',
  'Απών': 'Absent',
  'Δικαιολογημένος': 'Excused',
  'Δεν ολοκλήρωσε': 'Did not complete',
  'Ασφάλεια': 'Safety',
  'Πρόληψη λοιμώξεων': 'Infection prevention',
  'Υγιεινή χεριών': 'Hand hygiene',
  'Άλλο': 'Other',
  'Προγραμματισμένη': 'Scheduled',
  'Προγραμματισμένος': 'Scheduled',
  'Κατάλληλος': 'Fit',
  'Κατάλληλος με περιορισμούς': 'Fit with restrictions',
  'Προσωρινά μη κατάλληλος': 'Temporarily unfit',
}
export function employeeDisplayValue(value, language='el') {
  if (value == null || value === '') return value
  return language === 'en' ? (EN[String(value)] || value) : value
}
export function employeeOptions(values=[], language='el') {
  return values.map((value) => ({ value, label: employeeDisplayValue(value, language) }))
}
